function abilstrig_bee_scr(argument0) {
	//-------------------------------------------------<<**********<<{Auto: Sting}>>**********>>-------------------------------------------------
	if(abil==0){
	if(check==1){
	check=0
	damage=0.7
	with(Me){
	if(abilpassivespell.damageextra==1){
	other.damage+=0.1
	}}
	sped=3.5
	vsp=0
	delay=10
	direction=Me.direction
	useaudio=1
	spellsnd=audio_emitter_create()
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play_on(spellsnd,choose(snd_bee_stinger1,snd_bee_stinger1),false,8)
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play_on(spellsnd,choose(snd_scarecrow_wheat1,snd_scarecrow_wheat2),false,8)
	}else{
	sfx_play_on(spellsnd,choose(snd_bee_stinger1,snd_bee_stinger1),false,8)
	}}

	for(i=0;i<3;i+=1){
	if(i==0){
	stingerone=instance_create(x,y,Dummy_two_object)
	stingerone.delay=0
	created=stingerone
	}else{
	if(i==1){
	stingertwo=instance_create(x,y,Dummy_two_object)
	stingertwo.delay=4
	created=stingertwo
	}else{
	stingerthree=instance_create(x,y,Dummy_two_object)
	stingerthree.delay=8
	created=stingerthree
	}}
	with(created){
	check=1
	pin=101
	mask_index=dummy_spr
	}}}

	if(instance_exists(stingerone)||instance_exists(stingertwo)||instance_exists(stingerthree)){
	//ADJUST CHECK
	if(delay>=0){
	delay-=1
	//direction=Me.direction
	y=Me.y+15.5
	image_angle=0
	if(Control.con_h_up||Control.conp_h_up){
	vsp=-sped/2
	if(direction==0){
	image_angle+=45
	}else{
	image_angle-=45
	}
	}else{
	if(Control.con_h_down||Control.conp_h_down){
	vsp=sped/2
	if(direction==0){
	image_angle-=45
	}else{
	image_angle+=45
	}}else{
	option=0
	vsp=0
	}}
	if(direction==0){
	x=Me.x+12
	hsp=sped
	image_xscale=1
	}else{
	hsp=-sped
	image_xscale=-1
	}}else{

	//Bee Passive
	if(delay==-1){
	delay-=1
	if(Me.abilpassivespell.damageextra==1){
	beecreated=instance_create(x,y,Dummy_two_object)
	with(beecreated){
	delay=44
	pin=105
	damage=1
	image_speed=0.1
	target=-2
	hsp=other.hsp/2
	vsp=other.vsp/2
	with(Dummy_two_object){
	if(pin==100){
	other.sprite_index=sprite_index
	}}}}}

	if(instance_exists(stingerthree)){
	x=stingerthree.x
	y=stingerthree.y
	}}

	//ALWAYS
	for(i=0;i<3;i+=1){
	if(i==0){
	created=stingerone
	}else{
	if(i==1){
	created=stingertwo
	}else{
	created=stingerthree
	}}
	if(instance_exists(created)){
	with(created){
	if(delay<=0){
	if(check==1){
	duration=16
	mask_index=sprite_index
	check=0
	image_xscale=other.image_xscale
	x=other.x
	y=other.y
	hsp=other.hsp
	vsp=other.vsp
	phase=0
	targetsave=0
	creator=other.creator
	damage=other.damage
	option=other.option
	startanim=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	startanimspr=abil_bee1_dis1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	startanimspr=abil_bee1_dis1_witch
	}else{
	startanimspr=abil_bee1_dis1_witch
	}}
	startanimdur=24

	image_angle=other.image_angle
	grav=0
	image_speed=0.3
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bee1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee1_witch
	}else{
	sprite_index=abil_bee1
	}}}

	x+=hsp
	y+=vsp
	if(hsp!=0){
	if(duration>0){
	duration-=1
	}else{
	phase=-1
	hsp=0
	}}

	//SPELL
	enemyhit=instance_place(x,y,ProjEn)
	if(enemyhit!=noone){
	if(enemyhit.abil==2){
	enemyhit.phase=-1
	deathphase=1
	}}

	if(phase!=-2){
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	phase=-1
	}


	target=instance_place(x,y,Enemy)
	if(target!=noone){
	with(target){
	other.targetsave=id
	if(debuffeffect==100){
	bonusdamage=other.damage/2
	}else{
	bonusdamage=0
	}
	dr+=(other.damage+bonusdamage)*Control.itemsArray[0,4]
	drdraw+=(other.damage+bonusdamage)*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}
	phase=-1
	}
	if(phase==-1){
	phase=-2
	hsp=0
	vsp=0
	poisondelay=400
	poisontick=0
	damage=0.35
	poisonobject=noone
	if(targetsave!=0){
	with(targetsave){
	chance=-1
	if(debuff_Array[0,0]==0){
	debuff_Array[0,0]=1
	debuff_Array[0,1]=other.poisondelay
	chance=1
	other.chance=0
	}else{
	if(debuff_Array[1,0]==0&&debuff_Array[0,0]!=1){
	debuff_Array[1,0]=1
	debuff_Array[1,1]=other.poisondelay
	chance=1
	other.chance=1
	}else{
	if(debuff_Array[2,0]==0&&debuff_Array[0,0]!=1&&debuff_Array[1,0]!=1){
	debuff_Array[2,0]=1
	debuff_Array[2,1]=other.poisondelay
	chance=1
	other.chance=2
	}}}
	if(debuff_Array[0,0]==1){
	debuff_Array[0,1]=other.poisondelay
	}else{
	if(debuff_Array[1,0]==1){
	debuff_Array[1,1]=other.poisondelay
	}else{
	if(debuff_Array[2,0]==1){
	debuff_Array[2,1]=other.poisondelay
	}}}
	if(chance==-1){
	other.targetsave=0
	}}}

	image_index=0
	image_speed=0.15
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	poisonspr=abil_bee1_poison1
	poisonsprtwo=abil_bee1_dis1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	poisonspr=abil_bee1_poison1_witch
	poisonsprtwo=abil_bee1_dis1_witch
	}else{
	poisonspr=abil_bee1_poison1
	poisonsprtwo=abil_bee1_dis1
	}}
	sprite_index=poisonspr
	}

	}else{
	if(targetsave==0){
	if(poisonobject!=noone){
	with(poisonobject){
	instance_destroy()
	}}
	image_angle+=irandom_range(90,270)
	if(image_index>=((image_number-2)/2)-1){
	sprite_index=poisonsprtwo
	}
	if(image_index>=image_number-2){
	instance_destroy()
	}}else{

	if(instance_exists(targetsave)){
	if(!instance_exists(poisonobject)){
	poisonobject=instance_create(x,y,Dummy_two_object)
	with(poisonobject){
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bee1_poison1_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee1_poison1_witch_spr
	}else{
	sprite_index=abil_bee1_poison1_spr
	}}
	visible=false
	pin=103
	}}

	poisonobject.x=x
	poisonobject.y=y
	if(targetsave.hurt>0){
	poisonobject.visible=true
	}else{
	poisonobject.visible=false
	}
	image_angle+=irandom_range(90,270)
	if(targetsave.debuff_Array[chance,1]>0){
	targetsave.debuff_Array[chance,1]-=1
	x=targetsave.x+targetsave.xmid
	y=targetsave.y+targetsave.ymid

	if(targetsave.debuff_Array[chance,1] mod 10==0){
	if(sprite_index==poisonspr){
	sprite_index=poisonsprtwo
	}else{
	sprite_index=poisonspr
	}}

	if(targetsave.debuff_Array[chance,1] mod 40==0){
	with(targetsave){
	if(debuffeffect==100){
	bonusdamage=other.damage/2
	}else{
	bonusdamage=0
	}
	dr+=(other.damage+bonusdamage)*Control.itemsArray[0,4]
	drdraw+=(other.damage+bonusdamage)*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}
	}

	}else{
	with(poisonobject){
	instance_destroy()
	}
	targetsave.debuff_Array[chance]=0
	targetsave.hurtcolor=c_maroon
	targetsave=0
	}}else{
	targetsave=0
	}}}}else{
	delay-=1
	visible=false
	if(delay==0){
	visible=true
	}}}}}}else{
	duration=0
	deathphase=1
	}

	}else{
	//-------------------------------------------------<<**********<<{ABILTWO: SWARM}>>**********>>-------------------------------------------------
	if(abil==2){
	if(check==1){
	//BEE HIVE BEE
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play(choose(snd_bee_swarm1,snd_bee_swarm2,snd_bee_swarm3),8,false)
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play(choose(snd_scarecrow_crow1,snd_scarecrow_crow2),8,false)
	}else{
	sfx_play(choose(snd_bee_swarm1,snd_bee_swarm2,snd_bee_swarm3),8,false)
	}}
	duration=30
	extracheck=0
	check=0
	with(Dummy_two_object){
	if(pin==100){
	target=Me
	targettype=3
	}}
	}

	if(Me.hsp!=0){
	extracheck=1
	}else{
	extracheck=0
	}

	Control.charcdArray[Me.charid,2]=Control.abilArray[2,1]
	if(Me.grounded==1){
	phase=-1
	}

	with(Dummy_two_object){
	if(pin==100){
	spellduration=other.duration
	}}

	if(phase==-1||Control.con_p_w||Control.conp_p_w||Control.con_p_space||Control.conp_p_space){
	if(extracheck==1||Control.con_p_w||Control.conp_p_w||Control.con_p_space||Control.conp_p_space){
	with(Dummy_two_object){
	if(pin==100){
	if(targettype==3){
	target=Me
	targettype=2
	}}}}
	if(Me.grounded==1){
	with(Dummy_two_object){
	if(pin==100){
	if(targettype==3){
	target=Me
	targettype=2
	}}}
	instance_destroy()
	}}}else{
	//-------------------------------------------------<<**********<<{ABILTHREE: Honey}>>**********>>-------------------------------------------------
	if(abil==1){
	if(phase!=-5){
	if(check==1){
	check=0
	damage=0
	immune=0
	movespeed=2
	target=0
	extradelay=600
	extradelaytotal=600
	eat=0
	placecheck=0

	//BEE HIVE BEE
	with(Dummy_two_object){
	if(pin==100){
	target=other.id
	targettype=1
	}}

	duration=240
	startanim=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	startanimspr=abil_bee1_dis1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	startanimspr=abil_bee1_dis1_witch
	}else{
	startanimspr=abil_bee1_dis1
	}}
	startanimdur=24
	useaudio=1
	spellsnd=audio_emitter_create()
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play_on(spellsnd,choose(snd_bee_swarm1,snd_bee_swarm2,snd_bee_swarm3),false,8)
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play_on(spellsnd,choose(snd_scarecrow_pumpkin1,snd_scarecrow_pumpkin2),false,8)
	}else{
	sfx_play(choose(snd_bee_swarm1,snd_bee_swarm2,snd_bee_swarm3),8,false)
	}}

	hsp=0
	vsp=0
	grav=5
	//y-=2
	if(direction==0){
	hsp=movespeed
	image_index=1
	}else{
	hsp=-movespeed
	image_index=-1
	}
	if(option==1){
	vsp=(movespeed/2)
	if(creator.direction==0){
	direction-=20
	}else{
	direction+=20
	}
	}else{
	if(option==2){
	vsp=(movespeed/2)*-1
	if(creator.direction==0){
	direction+=20
	}else{
	direction-=20
	}}}

	grav=0
	image_speed=0.15
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bee2
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee2_witch
	}else{
	sprite_index=abil_bee2
	}}}

	//Movement
	extrarange=35
	if(x<__view_get( e__VW.XView, 0 )-extrarange||x>__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )+extrarange||y<__view_get( e__VW.YView, 0 )-extrarange||y>__view_get( e__VW.YView, 0 )+__view_get( e__VW.HView, 0 )+extrarange){
	//duration=0
	}
	x+=hsp
	y+=vsp
	//image_angle+=hsp*10

	//SPELL
	enemyhit=instance_place(x,y,ProjEn)
	if(enemyhit!=noone){
	if(enemyhit.abil==2){
	enemyhit.phase=-1
	deathphase=1
	}}

	if(phase!=-5){
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	phase=-1
	}

	target=instance_place(x,y,Enemy)
	if(target!=noone){
	phase=-1
	}
	if(phase==-1){
	phase=-5
	hsp=0
	vsp=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bee2_part2
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee2_part2_witch
	}else{
	sprite_index=abil_bee1_dis1
	}}
	image_index=9
	image_speed=0
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	image_index=0
	image_speed=0.15
	pin=102
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bee1_dis1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee1_dis1
	}else{
	sprite_index=abil_bee1_dis1
	}}}}

	}}else{


	//DEBUFF
	if(eat>0){
	image_index=(extradelay/extradelaytotal)*7
	extradelay-=1
	eat-=1
	}
	if(extradelay<=90){
	if(extradelay==90){
	visible=false
	}else{
	if(extradelay==82){
	visible=true
	}else{
	if(extradelay==60){
	visible=false
	}else{
	if(extradelay==52){
	visible=true
	}else{
	if(extradelay==30){
	visible=false
	}else{
	if(extradelay==22){
	visible=true
	}}}}}}}

	with(selfcreated){
	x=other.x
	y=other.y
	image_angle+=irandom_range(90,270)
	visible=other.visible
	}

	if(check==1){
	check=0
	}
	if(target!=noone){
	if(instance_exists(target)){
	if(placecheck==0){
	if(x>=(target.x+target.sprite_width/2)-1&&x<=(target.x+target.sprite_width/2)+1&&y>=(target.y+target.sprite_height/2)-1&&y<=(target.y+target.sprite_height/2)+1){
	if(x<(target.x+target.sprite_width/2)-1){
	x+=1
	}else{
	if(x>(target.x+target.sprite_width/2)+1){
	x-=1
	}}
	if(y<(target.y+target.sprite_height/2)-1){
	y+=1
	}else{
	if(y>(target.y+target.sprite_height/2)+1){
	y-=1
	}}}else{
	placecheck=1
	}}else{
	x=target.x+target.xmid
	y=target.y+target.ymid
	}
	if(extradelay>0){
	if(target.hurt<=0){
	target.image_blend=make_color_rgb(231,170,72)
	target.debuffeffect=100
	}
	extradelay-=1
	if(extradelay==0){
	target.image_blend=c_white
	target.debuffeffect=0
	}}else{
	deathphase=1
	}}else{
	deathphase=1
	}}else{
	target=instance_place(x,y,Enemy)
	if(extradelay>0){
	extradelay-=1
	}else{
	deathphase=1
	}}}}}
	}



}
