function forest_one_scr() {

	if(check==1){
	//CHEST LOOTS
	with(Control){
	chestitemone=0
	chestitemtwo=0
	}
	//Me.x=5712
	//Me.y=272
	doorone=0
	doortwo=0
	check=0
	//Save Book
	created=instance_create(3456,16,Item)
	created.itemtype=5
	created=instance_create(5056,16,Item)
	created.itemtype=5
	created=instance_create(5600,80,Item)
	created.itemtype=5
	//Dream Bottles
	//rm1
	with(Control){
	rmcheck=1
	musicchange=w1_act1_theme1_music
	if(actchoose==1){

	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,5]==0){
	created=instance_create(608,128,Item)
	with(created){
	itemtype=4
	iden=5
	}}
	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,6]==0){
	created=instance_create(2258,85,Item)
	with(created){
	itemtype=4
	iden=6
	}}
	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,7]==0){
	created=instance_create(2496,16,Item)
	with(created){
	itemtype=4
	iden=7
	}}
	}else{
	//rm2
	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,5]==0){
	created=instance_create(3376,224,Item)
	with(created){
	itemtype=4
	iden=5
	}}
	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,6]==0){
	created=instance_create(5056,304,Item)
	with(created){
	itemtype=4
	iden=6
	}}
	if(levelsArray[owLevels[charArray[charselected,6],charArray[charselected,7]]+actchoose-1,7]==0){
	created=instance_create(5424,0,Item)
	with(created){
	itemtype=4
	iden=7
	}}}
	}

	//Doors
	instance_create(3040,160,Door_obj)
	instance_create(5456,64,Door_obj)
	instance_create(5472,64,Door_obj)
	instance_create(5488,64,Door_obj)
	instance_create(5504,64,Door_obj)
	//Act 2
	if(Control.actchoose==2){
	created=instance_create(5632,80,Enemy)
	with(created){
	enemytype=2
	dir=1
	}
	created=instance_create(3344,128,Enemy)
	with(created){
	enemytype=2
	dir=1
	}
	/*
	created=instance_create(3072,48,Enemy)
	with(created){
	enemytype=2
	dir=0
	}
	created=instance_create(3072,112,Enemy)
	with(created){
	enemytype=2
	dir=0
	}
	*/
	created=instance_create(3168,48,Enemy)
	with(created){
	enemytype=2
	dir=1
	}
	created=instance_create(3168,112,Enemy)
	with(created){
	enemytype=2
	dir=1
	}
	//Type 2
	created=instance_create(2672,192,Enemy)
	with(created){
	enemytype=2
	dir=0
	key=1
	}
	created=instance_create(5040,160,Enemy)
	with(created){
	enemytype=2
	dir=0
	key=1
	}
	created=instance_create(5040,240,Enemy)
	with(created){
	enemytype=2
	dir=0
	key=1
	}
	created=instance_create(5424,192,Enemy)
	with(created){
	enemytype=2
	dir=1
	key=1
	}
	created=instance_create(5424,272,Enemy)
	with(created){
	enemytype=2
	dir=1
	key=1
	}
	}
	//Act 1
	if(Control.actchoose==1){

	instance_create(0,0,Tutorial_obj)

	created=instance_create(2384,160,Enemy)
	with(created){
	enemytype=2
	dir=1
	}
	created=instance_create(800,158,Enemy)
	with(created){
	enemytype=2
	dir=1
	}}
	}
	if(instance_exists(Dummy_object)){
	with(Me){
	hit=instance_place(x,y,Dummy_object)
	if(hit!=noone){
	if(hit.pin==10){
	//Effect
	debuff=1
	debufftimer=16
	if(hit.dir==1){
	debuffopt=-1.25
	}else{
	debuffopt=1.25
	}
	hit.hp=0
	}}
	}

	//leaves
	with(Dummy_object){
	if(pin==10){
	if(instance_place(x,y,Solid)||hp<=0){
	instance_destroy()
	}
	if(instance_place(x,y,Enemy)&&duration<85){
	instance_destroy()
	}
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	if(tick==1){
	if(y<starty+2){
	y+=random_range(0.25,0.4)
	image_angle+=6
	}else{
	tick=0
	}}else{
	if(tick==0){
	if(y>starty-2){
	y-=random_range(0.25,0.4)
	image_angle-=6
	}else{
	tick=1
	}}}
	if(dir==1){
	x-=sped
	}else{
	x+=sped
	}
	}else{

	//SIGN
	if(pin==80){
	if(check==1){
	check=0
	delay=0
	}
	hit=instance_place(x,y,Me)
	if(hit!=noone){
	if(created==0&&delay<=0){
	delay=60
	created=instance_create(__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 ),__view_get( e__VW.YView, 0 )+__view_get( e__VW.HView, 0 ),Dummy_object)
	with(created){
	pin=81
	image_speed=0
	sprite_index=actchoose_spr
	image_index=31
	}}else{
	if(instance_exists(created)&&created!=0){
	created.x=__view_get( e__VW.XView, 0 )
	created.y=__view_get( e__VW.YView, 0 )
	if(Control.con_p_escape||Control.con_p_enter||Control.con_p_e||Control.conp_p_space||Control.conp_p_q||Control.conp_p_enter||Control.conp_p_space){
	with(created){
	instance_destroy()
	}
	created=0
	}}}

	}else{
	if(delay>0){
	if(created!=0&&delay==60){
	with(created){
	instance_destroy()
	}
	created=0
	}
	delay-=1
	}
	}}else{
	}

	}}}

	//BEE HIVE BEE
	with(Dummy_object){
	if(pin==2){
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	if(actualx<Me.x+10+xoffset-movespeed){
	x+=movespeed
	actualx+=movespeed
	image_xscale=1
	}else{
	if(actualx>Me.x+10+xoffset+movespeed){
	x-=movespeed
	actualx-=movespeed
	image_xscale=-1
	}}
	if(actualy<Me.y+10+yoffset-movespeed){
	y+=movespeed
	actualy+=movespeed
	}else{
	if(actualy>Me.y+10+yoffset+movespeed){
	y-=movespeed
	actualy-=movespeed
	}}

	if(tickx!=-1){
	if(tickx==0){
	if(x<actualx+4){
	x+=0.05
	}else{
	tickx=1
	}}else{
	if(x>actualx-4){
	x-=0.05
	}else{
	tickx=0
	}}}

	if(ticky!=-1){
	if(ticky==0){
	if(y<actualy+4){
	y+=0.05
	}else{
	ticky=1
	}}else{
	if(y>actualy-4){
	y-=0.05
	}else{
	ticky=0
	}}}

	if(instance_position(x,y,Me)){
	with(Me){
	if(dmgsafety<=0){
	dmgsafety=6
	//DAMAGE
	debuff=1
	debufftimer=6
	if(x+10<other.x){
	debuffopt=-1.5
	}else{
	debuffopt=1.5
	}
	dr+=1
	drdraw+=1
	if(hurt<=0){
	hurttick=1
	}}}
	instance_destroy()
	}}
	}

	//Door Lock
	if(doorone==0){
	if(Me.x>5042){
	doorone=1
	created=instance_create(5024,64,Door_obj)
	created.locked=0
	created.image_index=3
	}}
	if(doortwo==0){
	if(Me.x>5696&&Me.y>96){
	//Mini boss
	Control.rmcheck=1
	Control.musicchange=w1_act1_theme2_music
	created=instance_create(5760,100,Enemy)
	with(created){
	enemytype=4
	merange=1000
	dir=1
	}
	doortwo=1
	created=instance_create(5664,288,Door_obj)
	created.locked=0
	created.image_index=3
	}}



}
