function mewep_scr(argument0) {
	//Idle
	if(argument0==0){
	wepdrawx=7
	wepdrawy=17
	wepangle=15
	persondrawx=0
	persondrawy=0
	action=0
	}else{
	if(argument0==1){
	wepdrawx=9
	wepdrawy=17
	wepangle=180
	persondrawx=0
	persondrawy=0
	action=0
	}else{
	//Walk
	//right
	if(argument0==2){
	action=-1
	if(image_index>=0&&image_index<1){
	wepdrawx=7
	wepdrawy=17
	wepangle=0
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=1&&image_index<2){
	wepdrawx=6
	wepdrawy=16
	wepangle=-22
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=2&&image_index<3){
	wepdrawx=6
	wepdrawy=15
	wepangle=-45
	persondrawx=1
	persondrawy=0
	}else{
	if(image_index>=3&&image_index<4){
	wepdrawx=7
	wepdrawy=17
	wepangle=-22
	persondrawx=1
	persondrawy=1
	}else{
	if(image_index>=4&&image_index<5){
	wepdrawx=7
	wepdrawy=17
	wepangle=0
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=5&&image_index<6){
	wepdrawx=8
	wepdrawy=16
	wepangle=22
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=6&&image_index<7){
	wepdrawx=11
	wepdrawy=16
	wepangle=45
	persondrawx=1
	persondrawy=0
	}else{
	if(image_index>=7){
	wepdrawx=7
	wepdrawy=17
	wepangle=22
	persondrawx=1
	persondrawy=1
	}}}}}}}}
	}else{
	//left
	if(argument0==3){
	action=-1
	if(image_index>=0&&image_index<1){
	wepdrawx=9
	wepdrawy=17
	wepangle=180
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=1&&image_index<2){
	wepdrawx=8
	wepdrawy=16
	wepangle=158
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=2&&image_index<3){
	wepdrawx=6
	wepdrawy=16
	wepangle=135
	persondrawx=-1
	persondrawy=0
	}else{
	if(image_index>=3&&image_index<4){
	wepdrawx=7
	wepdrawy=17
	wepangle=158
	persondrawx=-1
	persondrawy=1
	}else{
	if(image_index>=4&&image_index<5){
	wepdrawx=9
	wepdrawy=17
	wepangle=180
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=5&&image_index<6){
	wepdrawx=10
	wepdrawy=16
	wepangle=202
	persondrawx=0
	persondrawy=0
	}else{
	if(image_index>=6&&image_index<7){
	wepdrawx=11
	wepdrawy=16
	wepangle=225
	persondrawx=-1
	persondrawy=0
	}else{
	if(image_index>=7){
	wepdrawx=12
	wepdrawy=17
	wepangle=202
	persondrawx=-1
	persondrawy=1
	}}}}}}}}

	}else{
	//Jump
	if(argument0==4){
	action=1
	wepdrawx=6
	wepdrawy=16
	wepangle=22
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==5){
	action=1
	wepdrawx=9
	wepdrawy=16
	wepangle=158
	persondrawx=0
	persondrawy=0
	}else{
	//Fall
	if(argument0==6){
	action=2
	wepdrawx=5
	wepdrawy=16
	wepangle=-15
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==7){
	action=2
	wepdrawx=7
	wepdrawy=16
	wepangle=195
	persondrawx=0
	persondrawy=0
	}else{
	//Looku
	if(argument0==8){
	wepdrawx=7
	wepdrawy=17
	wepangle=0
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==9){
	wepdrawx=9
	wepdrawy=17
	wepangle=180
	persondrawx=0
	persondrawy=0
	}else{
	//Duck
	if(argument0==10){
	wepdrawx=0
	wepdrawy=0
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==11){
	wepdrawx=0
	wepdrawy=0
	persondrawx=0
	persondrawy=0
	}else{
	//Slam
	if(argument0==12){
	action=3
	if(slamcd>0){
	wepdrawx=8
	wepdrawy=17
	wepangle=90
	}else{
	wepdrawx=10
	wepdrawy=17
	wepangle=270
	}
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==13){
	action=3
	if(slamcd>0){
	wepdrawx=8
	wepdrawy=17
	wepangle=90
	}else{
	wepdrawx=10
	wepdrawy=17
	wepangle=270
	}
	persondrawx=0
	persondrawy=0
	}else{
	//Wall
	if(argument0==14){
	action=4
	wepdrawx=8
	wepdrawy=16
	wepangle=90
	persondrawx=0
	persondrawy=0
	}else{
	if(argument0==15){
	action=4
	wepdrawx=6
	wepdrawy=16
	wepangle=90
	persondrawx=0
	persondrawy=0
	}else{
	//Attack
	//abilArray[]abilarray_add(abilnumber,Mana,Cooldown,Damage,Casttime,Speed,Size,Action,Animdel,Wepdrawx,Wepdrawy,WepAngle1,WepAngle2)
	if(argument0==16){
	if(animdel<(Control.abilArray[Control.charselected,7])/2){
	action=5
	wepdrawx=Control.abilArray[abilselected,8]+3
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=Control.abilArray[abilselected,10]
	persondrawx=0
	persondrawy=0
	}else{
	action=6
	wepdrawx=Control.abilArray[abilselected,8]+1
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=Control.abilArray[abilselected,11]
	persondrawx=1
	persondrawy=0
	}
	}else{
	if(argument0==17){
	if(animdel<(Control.abilArray[abilselected,7])/2){
	action=5
	wepdrawx=Control.abilArray[abilselected,8]-3
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=180-Control.abilArray[abilselected,10]
	persondrawx=0
	persondrawy=0
	}else{
	action=6
	wepdrawx=Control.abilArray[abilselected,8]-2
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=180-Control.abilArray[abilselected,11]
	persondrawx=-1
	persondrawy=0
	}
	}else{
	//Bite
	if(argument0==18){
	if(animdel<(Control.abilArray[Control.charselected,7])/2){
	action=7
	wepdrawx=Control.abilArray[abilselected,8]+4
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=Control.abilArray[abilselected,10]
	persondrawx=0
	persondrawy=0
	}else{
	action=7
	wepdrawx=Control.abilArray[abilselected,8]+1
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=Control.abilArray[abilselected,11]
	persondrawx=3
	persondrawy=0
	}
	}else{
	if(argument0==19){
	if(animdel<(Control.abilArray[abilselected,7])/2){
	action=7
	wepdrawx=Control.abilArray[abilselected,8]-3
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=180-Control.abilArray[abilselected,10]
	persondrawx=0
	persondrawy=0
	}else{
	action=7
	wepdrawx=Control.abilArray[abilselected,8]-2
	wepdrawy=Control.abilArray[abilselected,9]
	wepangle=180-Control.abilArray[abilselected,11]
	persondrawx=-3
	persondrawy=0
	}
	}else{
	}}
	}}}}}}
	}}}}}}
	}}}}}}



}
