function charcreates_scr(argument0, argument1) {
	if(argument1==0){
	if(argument0==0){
	if(file_exists("Charslot1.sav")){
	charselected=argument0
	startup=0
	cd=1
	Me.dead=0
	justloaded=1
	charload_scr(charselected)
	abilcreate_scr(charArray[charselected,8])
	Me.charactercheck=1
	Me.charid=charselected
	option=0
	}else{
	startup=2
	subopt=0
	charselected=option
	option=0
	}
	}else{
	if(argument0==1){
	if(file_exists("Charslot2.sav")){
	charselected=argument0
	startup=0
	cd=1
	Me.dead=0
	justloaded=1
	charload_scr(charselected)
	abilcreate_scr(charArray[charselected,8])
	Me.charactercheck=1
	Me.charid=charselected
	option=0
	}else{
	startup=2
	subopt=0
	charselected=option
	option=0
	}
	}else{
	if(argument0==2){
	if(file_exists("Charslot3.sav")){
	charselected=argument0
	startup=0
	cd=1
	Me.dead=0
	justloaded=1
	charload_scr(charselected)
	abilcreate_scr(charArray[charselected,8])
	Me.charactercheck=1
	Me.charid=charselected
	option=0
	}else{
	startup=2
	subopt=0
	charselected=option
	option=0
	}}}}
	}else{
	deleteopt=0
	if(argument0==0){
	if(file_exists("Charslot1.sav")){
	file_delete("Charslot1.sav")
	charload_scr(charselected)
	}}else{
	if(argument0==1){
	if(file_exists("Charslot2.sav")){
	file_delete("Charslot2.sav")
	charload_scr(charselected)
	}}else{
	if(argument0==2){
	if(file_exists("Charslot3.sav")){
	file_delete("Charslot3.sav")
	charload_scr(charselected)
	}}}}
	}



}
