function forestenemy_3_scr() {
	if(option==0){
	option=1

	//All

	if(instance_position(x,y+20,Solid)){
	entypes=1
	}else{
	entypes=4
	}

	//Witch Brew
	if(entypes==1){
	xmid=7
	ymid=7
	sprite_index=witch_brew_spr
	//sprite_index=broom_move_spr
	image_speed=0.2
	mask_index=witch_brew_spr
	atdelay=0
	enemy=0
	attotal=50
	hp=7
	hptotal=hp
	}else{

	//Witch Broom
	if(entypes==2){

	}else{

	if(entypes==3){

	}else{
	if(entypes==4){
	check=1
	sprite_index=witch_broom2_spr
	mask_index=witch_brew_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	movespeed=random_range(0.75,1)
	range=random_range(5.8,6.2)
	firstx=x
	firsty=y
	tick=choose(0,1)
	}}}}}else{
	if(option==2){
	//Shroom boss
	option=3
	visible=true
	hp=30
	entypes=3
	phase=0
	check=0
	trigger=0
	sprite_index=mushroom1_extra1
	xmid=7
	ymid=4
	mask_index=sprite_index
	}}

	//-----*****Witch Brew}*****-----
	if(entypes==1){
	//Initial
	if(option==0){
	option=1
	sprite_index=witch_brew_spr
	xmid=7
	ymid=7
	//sprite_index=broom_move_spr
	image_speed=0.2
	mask_index=image_index
	atdelay=0
	enemy=0
	attotal=45
	hp=30
	hptotal=hp
	dir=0
	}

	if(atdelay<=0){
	//Attack
	atdelay=attotal
	for(i=-3;i<3;i+=1){
	enemy=instance_create(x+11,y+8,Dummy_object)
	with(enemy){
	creator=other.id
	diddamage=0
	duration=60
	durationtotal=duration
	speed=random_range(0.75,1)
	type=1
	pin=11
	damage=1
	num=other.i
	image_speed=0.3
	sprite_index=witch_bats_spr
	direction=point_direction(x,y,Me.x+8,Me.y+12)
	direction+=other.i*4
	}}
	}else{

	//Wind Up
	if(atdelay==attotal-20){
	sprite_index=witch_brew_spr
	}
	if(atdelay<=11){
	atdelay-=1
	if(atdelay==10){
	atdelay-=1
	image_index=0
	if(Me.x>x){
	sprite_index=witch_brewattr_spr
	}else{
	sprite_index=witch_brewattl_spr
	}}
	}else{
	//In Range On CD
	if(point_distance(Me.x+10,Me.y+6,x+14,y+14)<100){
	if(!collision_line(x+10,y+10,Me.x+10,Me.y+10,Solid,true,false)){
	atdelay-=1
	}}else{
	//Out of Range
	if(atdelay==12){
	sprite_index=witch_brew_spr
	}else{
	atdelay-=1
	}}}
	}

	}else{

	//*******{Slime}*******
	if(entypes==2){
	simple_enemy_scr(1)

	}else{

	//**********EVIL SHROOM***********
	if(entypes==3){
	if(trigger==0){
	if(point_distance(x+30,y+30,Me.x,Me.y)<150){
	trigger=1
	}}else{
	if(phase==0){
	if(check==0){
	x+=10
	y+=17
	check=1
	timer=240
	image_index=0
	image_speed=0.075
	sprite_index=mushroom1_extra1
	xmid=7
	ymid=4
	mask_index=sprite_index
	delay=190
	stoption=5
	tick=irandom(1)
	dir=0
	}

	if(animdel>0){

	}else{
	sprite_index=mushroom1_extra1
	}

	if(point_distance(x+30,y+30,Me.x,Me.y)<150||!collision_line(x+10,y+10,Me.x+10,Me.y+10,Solid,true,false)){
	if(delay>0){
	delay-=1
	if(delay==40){
	animdel=delay
	if(tick==0){
	sprite_index=mushroom1_extra1attack1
	}else{
	sprite_index=mushroom1_extra1attack2
	}
	image_index=0
	}else{
	if(delay==15){
	for(i=0;i<3;i+=1){
	if(tick==0){
	created=instance_create(x-13,y-5,Dummy_object)
	}else{
	created=instance_create(x+16,y-5,Dummy_object)
	}
	with(created){
	sprite_index=mushroomproj_spr
	pin=79
	speed=1
	direction=point_direction(x,y,Me.x+10,Me.y+10)
	direction-=25
	direction+=25*other.i
	duration=400
	damage=1
	}}
	}else{
	if(delay<=0){
	tick=irandom(1)
	if(stoption>0){
	delay=120
	stoption-=1
	}else{
	delay=360
	stoption=6
	}
	}
	}}}
	}
	Control.screenroll=5

	if(Control.screenroll<=0){
	//phase=0
	//check=1
	}

	}}}else{

	//WITCH BROOM
	if(entypes==4){
	if(dir==0){
	if(x<firstx+(16*range)){
	x+=movespeed
	}else{
	dir=1
	}}else{
	if(dir==1){
	if(x>firstx-(16*range)){
	x-=movespeed
	}else{
	dir=0
	}}
	}
	if(tick==0){
	if(y<firsty+16){
	y+=movespeed/4
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(y>firsty-16){
	y-=movespeed/4
	}else{
	tick=0
	}}
	}

	}else{

	//********************{SCARECROW BOSS}********************
	if(entypes==5){
	if(startcheck==0){
	if(Me.x>2608&&Me.y+10>224){
	startcheck=1
	created=instance_create(2592,224,Door_obj)
	created.locked=0
	created.image_index=3
	endingx=2719
	endingy=309
	extragold=25

	with(Control){
	rmcheck=1
	musicchange=music_boss_theme4
	}

	with(Enemy){
	if(entypes!=5){
	instance_destroy()
	}}
	}}else{
	//********************{BEGIN PHASE}********************
	if(phase==0){
	if(check==1){
	ending=1
	y-=10
	Control.enemytarget=id
	name="Patch"
	hpbuffer=0

	sprite_index=scarecrow_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	image_speed=0.1
	hp=300
	hptotal=hp
	opt=irandom(1)
	xsped=1
	ysped=0.5
	phase=1
	attdelaytwo=120
	dropone=0
	droptwo=0
	attopt=3
	tick=0
	amindel=0
	standone=instance_create(2688,304,Dummy_two_object)
	with(standone){
	creator=other.id
	pin=80
	tick=0
	sprite_index=scarecrow_stand_spr
	image_speed=0
	depth=8
	}
	standtwo=instance_create(2688+32,304,Dummy_two_object)
	with(standtwo){
	creator=other.id
	pin=80
	tick=0
	sprite_index=scarecrow_stand_spr
	image_speed=0
	depth=8
	}
	standthree=instance_create(2688+64,304,Dummy_two_object)
	with(standthree){
	creator=other.id
	pin=80
	tick=0
	sprite_index=scarecrow_stand_spr
	image_speed=0
	depth=8
	}}

	}else{
	//********************{SIT PHASE}********************
	if(phase==1){
	if(check==1){
	check=0
	attdelay=160
	image_speed=0.05
	if(attopt==0){
	image_index=4
	image_speed=0
	}}
	if(attopt>0){
	if(image_index>=3){
	image_index=0
	}}else{
	if(attdelay==77||attdelay==74&&hp<hptotal*.6||attdelay==71&&hp<hptotal*.3){
	image_index=7
	saveimg=7
	animdel=8
	for(i=0;i<12;i+=1){
	created=instance_create(x+sprite_width/2,(y+sprite_height/2)-12,Dummy_object)
	with(created){
	spread=irandom_range(3,6)
	image_speed=0.2
	image_index=other.i
	sprite_index=scarecrow_abil2_spr
	direction-=spread*4.5
	direction-=(other.i*15)+spread
	if(direction<270){
	image_yscale=-1
	}
	speed=0.75
	//image_angle=direction
	pin=78
	phase=0
	duration=400
	damage=1
	}}}
	}

	if(x+sprite_width/2<Me.x+10){
	dir=1
	}else{
	dir=0
	}

	if(attdelay>0){
	attdelay-=1
	}else{
	if(attopt>0){
	attopt-=1
	}else{
	attopt=3
	}
	phase=2
	check=1
	if(attopt>0){
	if(opt==0){
	tox=2624
	toy=216
	}else{
	if(opt==1){
	tox=2800
	toy=216
	}else{
	if(opt==2){
	tox=2704
	toy=265
	}}}
	}else{
	tox=2720
	toy=216
	}
	if(opt==0){
	opt=choose(1,2)
	}else{
	if(opt==1){
	opt=choose(0,2)
	}else{
	if(opt==2){
	opt=choose(1,0)
	}}}
	}

	}else{
	//********************{MOVE PHASE}********************
	if(phase==2){
	if(check==1){
	check=0
	image_speed=0.1
	if(attopt==0){
	image_index=5
	saveimg=5
	}else{
	image_index=3
	saveimg=3
	}}
	if(x<tox-xsped){
	dir=1
	x+=xsped
	}else{
	if(x>tox+xsped){
	dir=0
	x-=xsped
	}}
	if(y<toy-ysped){
	y+=ysped
	}else{
	if(y>toy+ysped){
	y-=ysped
	}}

	if(image_index>saveimg+1){
	image_index=saveimg
	}

	if(x>=tox-xsped&&x<=tox+xsped&&y>=toy-ysped&&y<=toy+ysped){
	if(attopt>0){
	phase=1
	check=1
	if(opt==2){
	if(x+sprite_width/2<Me.x+10){
	dir=0
	}else{
	dir=1
	}}else{
	if(dir==1){
	dir=0
	}else{
	dir=1
	}}
	if(y<250){
	if(tick=1||hp<hptotal/2){
	tick=0

	chance=choose(1,2,3)
	if(chance==1&&standone.tick==0){
	with(standone){
	visible=false
	tick=instance_create(x,y,Enemy)
	tick.entypes=6
	tick.option=1
	tick.creator=creator
	}
	}else{
	chance=choose(2,3)
	if(chance==2&&standtwo.tick==0){
	with(standtwo){
	visible=false
	tick=instance_create(x,y,Enemy)
	tick.entypes=6
	tick.option=1
	tick.creator=creator
	}
	}else{
	if(standthree.tick==0){
	with(standthree){
	visible=false
	tick=instance_create(x,y,Enemy)
	tick.entypes=6
	tick.option=1
	tick.creator=creator
	}}}}
	}else{
	tick=1
	}}
	}else{
	phase=1
	check=1
	image_index=7
	saveimg=7
	animdel=6
	for(i=0;i<9;i+=1){
	created=instance_create(x+sprite_width/2,(y+sprite_height/2)-12,Dummy_object)
	with(created){
	image_speed=0.2
	image_index=other.i
	sprite_index=scarecrow_abil2_spr
	direction-=other.i*20
	if(direction<270){
	image_yscale=-1
	}
	speed=0.75
	//image_angle=direction
	pin=78
	phase=0
	duration=400
	damage=1
	}}}
	}


	}

	//********************{LOW HEALTH}********************
	if(hp<hptotal*.6){
	xsped=1.5
	ysped=0.75
	if(hp<hptotal*.3){
	xsped=2
	ysped=1
	}}

	}}
	//********************{SCARECROW ALWAYS}********************
	if(animdel>0){
	animdel-=1
	if(animdel>2){
	image_index=saveimg
	}else{
	image_index=saveimg+1
	}}

	//SCARE CROW HEALERS
	with(standone){
	if(tick!=0){
	if(!instance_exists(tick)){
	tick=0
	visible=true
	chance=irandom(2)
	if(chance==1){
	created=instance_create(x+sprite_width/2,y,Item)
	created.itemtype=2
	created.subtype=1
	}}}}
	with(standtwo){
	if(tick!=0){
	if(!instance_exists(tick)){
	tick=0
	visible=true
	chance=irandom(2)
	if(chance==1){
	created=instance_create(x+sprite_width/2,y,Item)
	created.itemtype=2
	created.subtype=1
	}}}}
	with(standthree){
	if(tick!=0){
	if(!instance_exists(tick)){
	tick=0
	visible=true
	chance=irandom(2)
	if(chance==1){
	created=instance_create(x+sprite_width/2,y,Item)
	created.itemtype=2
	created.subtype=1
	}}}}

	//DROPLETS
	if(hp<hptotal/2){
	if(phase!=0){
	if(dropone==0){
	dropone=instance_create(2592+choose(32,48,64),319,Dummy_object)
	with(dropone){
	sprite_index=scarecrow_abil1_spr
	image_index=0
	image_speed=0.02
	pin=77
	delay=6
	damage=1
	}}else{
	with(dropone){
	if(y>room_height){
	other.dropone=0
	instance_destroy()
	}
	if(image_index>=4&&image_index<5){
	image_speed=0
	image_index=4
	y+=1
	if(delay<=0){
	if(instance_place(x,y+1,Solid)){
	image_index=5
	image_speed=0.8
	}}else{
	delay-=1
	}}else{
	if(image_index>=12){
	other.dropone=0
	instance_destroy()
	}}}}}
	if(dropone!=0){
	if(!instance_exists(dropone)){
	dropone=0
	}}
	//droptwo    2784
	if(droptwo==0){
	droptwo=instance_create(2800+choose(0,16,32),319,Dummy_object)
	with(droptwo){
	sprite_index=scarecrow_abil1_spr
	image_index=0
	image_speed=0.02
	pin=77
	delay=6
	damage=1
	}}else{
	with(droptwo){
	if(y>room_height){
	other.droptwo=0
	instance_destroy()
	}
	if(image_index>=4&&image_index<5){
	image_speed=0
	image_index=4
	y+=1
	if(delay<=0){
	if(instance_place(x,y+1,Solid)){
	image_index=5
	image_speed=0.8
	}}else{
	delay-=1
	}}else{
	if(image_index>=12){
	other.droptwo=0
	instance_destroy()
	}}}}}
	if(droptwo!=0){
	if(!instance_exists(droptwo)){
	droptwo=0
	}}
	}}else{

	//Little Scarecrows
	if(entypes==6){
	if(check==1){
	drop=0
	hp=4
	if(creator.hp<creator.hptotal*.6){
	hp=4
	if(creator.hp<creator.hptotal*.3){
	hp=4
	}}
	check=0
	phase=0
	sprite_index=scarecrow_rise_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_speed=0.2
	mask_index=dummy_spr
	attdelay=300
	}
	if(phase==0){
	if(image_index>7){
	phase=1
	mask_index=sprite_index
	sprite_index=scarecrow_small_spr
	image_speed=0.1
	}}else{
	if(attdelay>0){
	attdelay-=1
	if(attdelay==30){
	image_index=0
	sprite_index=scarecrow_smallcast_spr
	}
	}else{
	sprite_index=scarecrow_small_spr
	attdelay=300
	created=instance_create(x+12,y+15,Dummy_object)
	with(created){
	creator=other.creator
	pin=81
	sprite_index=scarecrow_smallabil1_spr
	image_speed=0.2
	depth=other.depth-1
	sped=1
	tick=0
	}
	}}}


	}}}}
	}



}
