function roboclown_scr() {
	distancetrav=x
	if(phase==0){
	if(check==1){
	attackdelaysave=60
	hurtsound=robohurt_snd1
	hurtsoundtwo=robohurt_snd2
	attacktype=2
	__view_set( e__VW.Object, 0, noone )
	mask_index=roboclown_sprs
	image_index=0
	image_speed=0
	part1=instance_create(x,y,Solid_plat)
	with(part1){
	sprite_index=roboclown_spr
	image_index=0
	visible=false
	image_speed=0
	}
	part2=instance_create(x,y,Solid_plat)
	with(part2){
	sprite_index=roboclown_traction_spr
	image_index=0
	visible=false
	image_speed=0
	}
	damage=2
	check=0
	attackan=0
	option=0
	robosprite=0
	armangle=0
	height=20
	tick=0
	ticktwo=0
	y-=20
	starty=y
	//plate=instance_create(x,y-height,Solid_plat)
	//with(plate){
	attackdelay=120
	distance=0
	startx=x
	}

	if(attackdelay>0){
	attackdelay-=1
	}else{
	if(attacktype==0){
	attacktype=choose(2,1)
	}else{
	if(attacktype==1){
	attacktype=choose(0,2)
	}else{
	if(attacktype==2){
	attacktype=choose(0,1)
	}else{
	}}}
	phase=1
	check=1
	attackdelay=15
	//attacktype=2
	}

	if(distance<=0){
	distance=irandom(20)
	distance=20
	}else{
	if(ticktwo==0){
	if(x<startx+distance){
	x+=1
	}else{
	ticktwo=1
	}}else{
	if(ticktwo==1){
	if(x>startx-distance){
	x-=1
	}else{
	ticktwo=0
	}}
	}
	}

	if(tick==0){
	if(height<45){
	height+=1
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(height>23){
	height-=1
	}else{
	tick=0
	}}
	}

	}else{

	//ATTACK PHASE 1
	if(phase==1&&x<__view_get( e__VW.XView, 0 )+255){
	if(check==1){
	check=0
	tick=0
	attackan=0
	if(attacktype==0){
	option=30
	}else{
	if(attacktype==1){
	option=6
	}else{
	option=20
	}}}

	if(height>23){
	height-=1
	}
	//Attack Type rapid fire
	if(attacktype==0){
	if(tick==0){
	if(armangle<45){
	armangle+=4
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(armangle>-20){
	armangle-=4
	}else{
	tick=0
	}}
	}
	if(attackdelay>0){
	attackdelay-=1
	}else{
	attackdelay=4
	option-=1
	if(option<=0){
	phase=10
	attackdelay=attackdelaysave
	}
	attackan=4
	x+=3
	y-=2
	height+=3
	image_angle-=5
	sfx_play(shot_snd1,7,false)
	cannonball=instance_create(x+15,y+52,Dummy_object)
	with(cannonball){
	pin=103
	sprite_index=roboclown_hand_spr
	image_speed=0
	image_index=0
	direction=other.armangle+180
	image_angle=direction
	speed=3
	ypos=52
	xpos=24
	phase=0
	}
	//SMOKE
	spotx=8
	spoty=49
	for(i=0;i<2;i+=1){
	smoke=instance_create(x+spotx,y+spoty,Dummy_object)
	with(smoke){
	pin=110
	visible=true
	chance=choose(0,1)
	if(chance==0){
	sprite_index=smoke_2_spr
	}else{
	sprite_index=smoke_spr
	}
	image_speed=0.2
	image_index=0
	turn=choose(5,-5)
	image_angle=irandom(360)
	if(other.i==1){
	depth=other.depth+1
	}
	}
	spotx+=4
	spoty+=3
	}}

	}else{
	//ATTACK TYPE Spread Shot
	if(attacktype==1){
	//arm
	if(tick==0){
	if(armangle<45){
	armangle+=4
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(armangle>-20){
	armangle-=4
	}else{
	tick=0
	}}
	}

	//attack
	if(attackdelay>0){
	attackdelay-=1
	}else{
	attackdelay=40
	option-=1
	if(option<=0){
	phase=10
	attackdelay=attackdelaysave
	}
	attackan=4
	x+=3
	y-=2
	height+=3
	image_angle-=5
	chance=1
	sfx_play(shot_snd2,7,false)
	for(i=0;i<6;i+=1){
	cannonball=instance_create(x+15,y+52,Dummy_object)
	with(cannonball){
	pin=104
	sprite_index=roboclown_bullet_spr
	image_speed=0.3
	image_index=0
	direction=(other.armangle+120)+other.chance*15
	image_angle=direction
	speed=5
	ypos=52
	xpos=24
	phase=0
	}
	chance+=1
	}
	//SMOKE
	spotx=8
	spoty=49
	for(i=0;i<4;i+=1){
	smoke=instance_create(x+spotx,y+spoty,Dummy_object)
	with(smoke){
	pin=110
	visible=true
	chance=choose(0,1)
	if(chance==0){
	sprite_index=smoke_2_spr
	}else{
	sprite_index=smoke_spr
	}
	image_speed=0.2
	image_index=0
	turn=choose(5,-5)
	image_angle=irandom(360)
	if(other.i==1){
	depth=other.depth+1
	}
	}
	spotx+=2
	spoty+=2
	}}
	}else{

	//ATTACK TYPE Rocket
	if(attacktype==2){
	//arm
	if(tick==0){
	if(armangle>-85){
	armangle-=4
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(armangle<-65){
	armangle+=4
	}else{
	tick=0
	}}
	}

	//attack
	if(attackdelay>0){
	attackdelay-=1
	}else{
	if(armangle>-90&&armangle<-60){
	attackdelay=2
	option-=1
	if(option<=0){
	phase=10
	attackdelay=attackdelaysave
	}
	attackan=4
	x+=3
	y-=2
	height-=0.2
	image_angle-=3
	if(audio_is_playing(rocket_snd1)){
	audio_stop_sound(rocket_snd1)
	sfx_play(rocket_snd1,7,false)
	}else{
	sfx_play(rocket_snd1,7,false)
	}
	cannonball=instance_create(x+15,y+25,Dummy_object)
	with(cannonball){
	phase=0
	timer=10
	pin=105
	sprite_index=roboclown_rocket_spr
	image_speed=0.3
	image_index=0
	direction=(other.armangle+180)
	image_angle=direction
	speed=8
	ypos=52
	xpos=24
	phase=0
	gravity=0.1
	}
	//SMOKE
	spotx=8
	spoty=19
	for(i=0;i<4;i+=1){
	smoke=instance_create(x+spotx,y+spoty,Dummy_object)
	with(smoke){
	pin=110
	visible=true
	chance=choose(0,1)
	if(chance==0){
	sprite_index=smoke_2_spr
	}else{
	sprite_index=smoke_spr
	}
	image_speed=0.2
	image_index=0
	turn=choose(5,-5)
	image_angle=irandom(360)
	if(other.i==1){
	depth=other.depth+1
	}
	}
	spotx+=2
	spoty+=2
	}}}
	}

	}}

	}else{

	//Closed PHASE
	if(phase==2){

	if(tick==0){
	if(height<45){
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(height>23){
	height-=1
	}else{
	tick=0
	}}
	}
	if(x+(sprite_width/2)>Me.x+(Me.sprite_width/2)){
	phase=0
	}

	}else{

	//WAIT PHASE
	if(phase==10){
	if(height>23){
	height-=1
	}
	if(armangle>2){
	armangle-=1.5
	}
	if(armangle<-2){
	armangle+=1.5
	}
	if(attackdelay>0){
	attackdelay-=1
	if(attackdelay==40||attackdelay==30||attackdelay==20){
	attackan=6
	chance=choose(0,1)
	if(chance==0){
	sfx_play(roboroar_snd1,7,false)
	}else{
	sfx_play(roboroar_snd2,7,false)
	}}
	}else{
	attackdelay=120
	phase=0
	}



	}

	}


	}

	}
	//ANY PHASE
	__view_set( e__VW.XView, 0, x-210 )
	__view_set( e__VW.YView, 0, y-44 )
	if(Me.x+(Me.sprite_width/2)<__view_get( e__VW.XView, 0 )){
	Me.x=__view_get( e__VW.XView, 0 )-(Me.sprite_width/2)
	}
	if(Me.x+(Me.sprite_width/2)>__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )){
	Me.x=__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )-(Me.sprite_width/2)
	}

	if(attackan>0||hurt>0){
	attackan-=1
	if(hurt>0){
	robosprite=4
	}else{
	if(phase!=10||attackdelay>40){
	robosprite=3
	}else{
	robosprite=5
	}}
	}else{
	robosprite=0
	}
	if(image_angle<0){
	image_angle+=1
	}
	if(y<starty){
	y+=1
	}
	with(Dummy_object){
	//smoke
	if(pin==110){
	y-=2
	x+=choose(0.25,-0.25)
	chance=choose(0.05,-0.05)
	image_angle+=turn
	image_xscale+=chance
	image_yscale+=chance
	if(y<0){
	instance_destroy()
	}
	}else{
	//cannon ball
	if(pin==103){
	image_angle+=10
	if(y>room_height){
	instance_destroy()
	}
	if(x<__view_get( e__VW.XView, 0 )-5){
	instance_destroy()
	}
	if(phase==2){
	if(check==1){
	check=0
	image_index=1
	direction=270
	speed=2
	}}
	}else{
	//spread shot
	if(pin==104){
	if(y>room_height){
	instance_destroy()
	}
	if(x<__view_get( e__VW.XView, 0 )-5){
	instance_destroy()
	}}else{
	//rocket
	if(pin=105){
	if(y>room_height){
	instance_destroy()
	}
	if(x<__view_get( e__VW.XView, 0 )-5){
	instance_destroy()
	}
	if(phase==1){
	image_angle=direction
	hit=instance_place(x,y+speed,Solid)
	if(hit!=noone){
	gravity=0
	speed=0
	y=hit.y
	sprite_index=roboclown_rocketexp_spr
	phase=2
	timer=8
	with(other){
	Control.screenshake+=3
	if(audio_is_playing(explosion_snd1)){
	audio_stop_sound(explosion_snd1)
	sfx_play(explosion_snd1,7,false)
	}else{
	sfx_play(explosion_snd1,7,false)
	}
	smoke=instance_create(other.x,other.y,Dummy_object)
	//smoke
	with(smoke){
	pin=110
	visible=true
	chance=choose(0,1)
	if(chance==0){
	sprite_index=smoke_2_spr
	}else{
	sprite_index=smoke_spr
	}
	image_speed=0.2
	image_index=0
	turn=choose(5,-5)
	image_angle=irandom(360)
	if(other.i==1){
	depth=other.depth+1
	}}
	}
	}}else{
	if(phase==0){
	image_angle=direction
	if(timer>0){
	timer-=1
	}else{
	phase=1
	}}else{
	if(phase==2){
	image_speed=0.7
	if(timer>0){
	timer-=1
	if(timer==4||timer==0){
	with(other){
	smoke=instance_create(other.x,other.y,Dummy_object)
	//smoke
	with(smoke){
	pin=110
	visible=true
	chance=choose(0,1)
	if(chance==0){
	sprite_index=smoke_2_spr
	}else{
	sprite_index=smoke_spr
	}
	image_speed=0.2
	image_index=0
	turn=choose(5,-5)
	image_angle=irandom(360)
	if(other.i==1){
	depth=other.depth+1
	}}
	}
	}}else{
	instance_destroy()
	}

	}}}
	}else{

	}}}

	}}
	with(Me){
	if(vsp>0){
	hit=collision_rectangle(x+8,y+18+vsp,x+11,y+19+vsp,Dummy_object,true,false)
	if(hit!=noone){
	if(hit.pin==103){
	vsp=-4
	hit.phase=2
	hit.check=1
	}}}
	hit=instance_place(x,y,Dummy_object)
	if(hit!=noone){
	if(hit.pin==103&&hit.phase<2){
	debuff=1
	debufftimer=2
	if(x<hit.x){
	debuffopt=-12
	}else{
	debuffopt=12
	}
	if(hurt<=0){
	hurttick=1
	}
	with(hit){
	instance_destroy()
	}}else{
	if(hit.pin==104||hit.pin==105){
	if(hurt<=0){
	hurttick=1
	}
	with(hit){
	instance_destroy()
	}}
	}}
	}
	if(x+(sprite_width/2)<Me.x+(Me.sprite_width/2)){
	phase=2
	tick=1
	}
	//all
	//visible=false
	with(part1){
	//visible=true
	x=other.x
	y=other.y-other.height
	hit=instance_place(x,y,Me)
	if(hit!=noone){
	Me.x-=1
	}}
	with(part2){
	//visible=true
	x=other.x
	y=other.y
	hit=instance_place(x,y,Me)
	if(hit!=noone){
	Me.x-=1
	}}



}
