function forestenemy_1_scr() {
	//*******{Walking Tree}*******
	if(enemytype==1){
	if(check==1){
	check=0
	hp=6
	needsgrav=1
	sprite_index=tree_w
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	}
	simple_enemy_scr(1)
	}else{
	//*******{Stump}*******
	if(enemytype==2){
	if(check==1){
	check=0
	hp=12
	if(key==0){
	sprite_index=stump_spr
	}else{
	sprite_index=stump2_spr
	}
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	image_speed=0
	attcd=0
	attone=0
	animdel=0
	}

	if(animdel<=0){
	if(image_index>1){
	animdel=random_range(70,84)
	//Awake
	if(image_index==2){
	image_index=3
	}else{
	if(image_index==3){
	image_index=2
	}}
	}else{
	animdel=random_range(170,210)
	//Sleeping
	if(image_index==0){
	image_index=1
	}else{
	if(image_index==1){
	image_index=0
	}}}
	}else{
	animdel-=1
	}

	if(attcd>0){
	attcd-=1
	}else{
	//Attack
	if(abs(y-Me.y)<20&&abs(x-Me.x)<70){
	attone=20
	attcd=360
	image_index=2
	sfx_play_at(choose(sandstorm_snd1,sandstorm_snd2),x,y,0,5,300,1,false,8)
	}else{
	if(image_index>1){
	image_index=0
	}}}

	if(attone>0){
	attone-=1
	if(attone==9){
	image_index=4
	}else{
	if(attone==0){
	image_index=2
	}}
	for(i=0;i<3;i+=1){
	if(dir==0){
	created=instance_create(x+13,y+random_range(9.5,10.5)+(i*random_range(1.5,2.5)),Dummy_object)
	}else{
	created=instance_create(x+3,y+random_range(9.5,10.5)+(i*random_range(1.5,2.5)),Dummy_object)
	}
	with(created){
	dir=other.dir
	tick=choose(0,1)
	starty=y
	sped=random_range(0.75,1.15)
	num=other.i
	pin=10
	hp=1
	creator=other.id
	duration=190
	sprite_index=leaf_spr
	image_index=irandom(2)
	image_speed=0
	}
	}}

	}else{
	//*******{Bee}*******
	if(enemytype==3){
	if(check==1){
	check=0
	dir=1
	hp=8
	sprite_index=bee_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	attcd=0
	movespeed=0.75
	animdel=0
	tick=0
	starty=y
	startx=x
	range=16*3
	image_speed=0.15
	}
	if(Me.x+10<x+(sprite_width/2)){
	dir=1
	}else{
	dir=0
	}

	if(image_index<0.3){
	chance=irandom(12)
	if(chance==0&&sprite_index!=bee2_spr){
	sprite_index=bee2_spr
	}else{
	sprite_index=bee_spr
	}}

	if(tick==0){
	if(y<firsty+range){
	y+=movespeed
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(y>firsty-range){
	y-=movespeed
	}else{
	tick=0
	}}
	}

	}else{

	//*******{Queen Bee}*******
	if(enemytype==4){
	if(check==1){
	ending=1
	check=0
	dir=1

	Control.enemytarget=id
	name="Bee Queen"
	hpbuffer=0

	endingx=5811
	endingy=209
	extragold=20
	extraxp=9

	sprite_index=beequeen_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	attcd=0
	movespeed=0.5
	animdel=0
	tick=0
	starty=y+64
	startx=x
	range=16*4
	rangetwo=16*4
	image_speed=0.15
	ticktwo=0
	lrlr=0
	hp=130
	hptotal=hp
	udud=0
	phase=1
	phaseopt=0
	counter=0
	chancespot=choose(1,2,3,4,5,6)
	enrage=70
	atttwodelay=200
	}
	//Phase 0
	if(phase==0){
	if(Me.x+10<x+(sprite_width/2)){
	dir=1
	}else{
	dir=0
	}
	if(hp<=0){
	instance_create(5808,224,Goal)
	}
	if(hp>enrage){
	if(image_index<0.3){
	chance=irandom(12)
	if(chance==0&&sprite_index!=beequeen2_spr){
	sprite_index=beequeen2_spr
	}else{
	sprite_index=beequeen_spr
	}}
	}else{
	movespeed=0.9
	image_speed=0.25
	sprite_index=beequeenrage_spr
	}
	//Y
	if(tick<=0){
	tick=random_range(60,120)
	if(y<starty+range&&y>starty-range){
	udud=choose(1,-1)
	}else{
	if(y<starty+range){
	udud=1
	}else{
	if(y>starty-range){
	udud=-1
	}}}
	}else{
	tick-=1
	y+=movespeed*udud
	if(y>starty+range||y<starty-range){
	tick=0
	}}
	//X
	if(ticktwo<=0){
	ticktwo=random_range(60,180)
	if(x<startx+rangetwo&&x>firstx-rangetwo){
	lrlr=choose(1,-1)
	}else{
	if(x<startx+rangetwo){
	lrlr=1
	}else{
	if(x>startx-rangetwo){
	lrlr=-1
	}}}
	}else{
	ticktwo-=1
	x+=movespeed*lrlr
	if(x>startx+rangetwo||x<startx-rangetwo){
	ticktwo=0
	}}

	if(counter==0){
	if(hp>=hptotal){
	phase=1
	counter+=1
	}}else{
	if(counter==1){
	if(hp<=hptotal-30){
	phase=1
	counter+=1
	}}else{
	if(counter==2){
	if(hp<=hptotal-60){
	phase=1
	counter+=1
	}}else{
	if(counter==3){
	if(hp<=40){
	phase=1
	counter+=1
	}}}}}

	if(hp<=enrage){
	if(atttwodelay>0){
	swarmcheck=0
	with(Dummy_object){
	if(pin==2){
	other.swarmcheck=1
	}}
	if(swarmcheck==0){
	atttwodelay-=1
	}}else{
	atttwodelay=200
	for(i=0;i<11;i+=1){
	if(i==0){
	xoffset=-1+random(2)
	yoffset=-6+random(2)
	ticksavex=-1
	ticksavey=0
	}else{
	if(i==1){
	xoffset=-1+random(2)
	yoffset=-1+random(2)
	ticksavex=-1
	ticksavey=-1
	}else{
	if(i==2){
	xoffset=-1+random(2)
	yoffset=4+random(2)
	ticksavex=-1
	ticksavey=1
	}else{
	if(i==3){
	xoffset=-6+random(2)
	yoffset=-3.5+random(2)
	ticksavex=0
	ticksavey=0
	}else{
	if(i==4){
	xoffset=-6+random(2)
	yoffset=1.5+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==5){
	xoffset=4+random(2)
	yoffset=-3.5+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==6){
	xoffset=4+random(2)
	yoffset=1.5+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==7){
	xoffset=-4.25+random(2)
	yoffset=-2.25+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==8){
	xoffset=2.25+random(2)
	yoffset=0.25+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==9){
	xoffset=1.25+random(2)
	yoffset=-3.25+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==10){
	xoffset=-3.25+random(2)
	yoffset=1.25+random(2)
	ticksavex=0
	ticksavey=0
	}}}}}}}}}}}
	created=instance_create(x+xoffset+42,y+yoffset+31,Dummy_object)
	with(created){
	sprite_index=beesmalltwo_spr
	pin=2
	hp=1
	duration=180+(other.i*22)
	creator=other.id
	movespeed=0.25
	yoffset=other.yoffset
	xoffset=other.xoffset
	tickx=other.ticksavex
	ticky=other.ticksavey
	actualx=x
	actualy=y
	}}}
	}

	}else{

	//Phase 1
	if(phase==1){
	move_towards_point(startx+32,starty-165,3)
	if(point_distance(x,y,startx+32,starty-165)<10){
	phase=2
	phaseopt=0
	if(hp==hptotal){
	phaseopttwo=0
	}else{
	phaseopttwo=2
	}
	speed=0
	}}else{

	//Phase 2
	if(phase==2){
	//Initial
	if(phaseopt==0){
	phaseopt=1
	if(chancespot<=2){
	chancespot=choose(3,4)
	}else{
	chancespot=choose(1,2)
	}
	if(chancespot==1){
	xspot=5712
	xspottwo=5888
	}else{
	if(chancespot==2){
	xspot=5744
	xspottwo=5920
	}else{
	if(chancespot==3){
	xspot=5888
	xspottwo=5712
	}else{
	if(chancespot==4){
	xspot=5920
	xspottwo=5744
	}}}}
	if(hp>enrage){
	enragetimes=1
	}else{
	enragetimes=2
	}
	for(i=0;i<enragetimes;i+=1){
	if(i==0){
	xtimes=xspot
	}else{
	xtimes=xspottwo
	}
	created=instance_create(xtimes,132,Enemy)
	with(created){
	times=0
	enemytype=5
	creator=other.id
	if(other.hp>other.enrage){
	subtype=0
	sprite_index=beelarva_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	hp=15
	timertotal=160
	}else{
	subtype=1
	sprite_index=beelarvatwo_spr
	hp=15
	timertotal=240
	}
	timer=0
	mask_index=sprite_index
	phase=0
	}}}

	//Active
	larvacheck=0
	with(Enemy){
	if(enemytype==6||enemytype=5){
	other.larvacheck=1
	}}

	if(larvacheck==0){
	phaseopt=0
	if(phaseopttwo>0){
	phaseopttwo-=1
	}else{
	phase=0
	}}}

	}}}else{

	//*********{Larva}*********
	if(enemytype==5){
	//Fall Phase
	if(phase==0){
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_index=0
	if(!instance_place(x,y-2,Solid)){
	y+=2
	}else{
	phase=1
	}
	hp=8
	}else{
	//Hatch Phase
	if(phase==1){
	if(timer<timertotal+(times*85)){
	timer+=1
	image_index=timer/(timertotal+(times*85))*5
	}else{
	if(subtype==0){
	phase=2
	for(i=0;i<11;i+=1){
	if(i==0){
	xoffset=-1+random(2)
	yoffset=-6+random(2)
	ticksavex=-1
	ticksavey=0
	}else{
	if(i==1){
	xoffset=-1+random(2)
	yoffset=-1+random(2)
	ticksavex=-1
	ticksavey=-1
	}else{
	if(i==2){
	xoffset=-1+random(2)
	yoffset=4+random(2)
	ticksavex=-1
	ticksavey=1
	}else{
	if(i==3){
	xoffset=-6+random(2)
	yoffset=-3.5+random(2)
	ticksavex=0
	ticksavey=0
	}else{
	if(i==4){
	xoffset=-6+random(2)
	yoffset=1.5+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==5){
	xoffset=4+random(2)
	yoffset=-3.5+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==6){
	xoffset=4+random(2)
	yoffset=1.5+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==7){
	xoffset=-4.25+random(2)
	yoffset=-2.25+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==8){
	xoffset=2.25+random(2)
	yoffset=0.25+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==9){
	xoffset=1.25+random(2)
	yoffset=-3.25+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==10){
	xoffset=-3.25+random(2)
	yoffset=1.25+random(2)
	ticksavex=0
	ticksavey=0
	}}}}}}}}}}}
	created=instance_create(x+xoffset+8,y+yoffset,Dummy_object)
	with(created){
	sprite_index=beesmall_spr
	pin=2
	hp=1
	duration=340+(other.i*22)
	creator=other.id
	movespeed=0.175
	yoffset=other.yoffset
	xoffset=other.xoffset
	tickx=other.ticksavex
	ticky=other.ticksavey
	actualx=x
	actualy=y
	}}
	}else{
	//ENRAGED
	created=instance_create(x-16,y-16,Enemy)
	with(created){
	enemytype=6
	}
	instance_destroy()
	}}}else{
	//Bee Phase
	image_index=0
	if(phase==2){
	checks=2
	if(instance_exists(Dummy_object)){
	with(Dummy_object){
	if(pin==2){
	other.checks=1
	}}}
	if(checks==2){
	times+=1
	phase=1
	timer=0
	}}}}
	}else{

	//Boss Bees
	if(enemytype==6){
	if(check==1){
	check=0
	hp=12
	dir=1
	sprite_index=bee_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	attcd=0
	movespeed=0.6
	animdel=0
	tick=0
	starty=y
	startx=x
	range=16*3
	image_speed=0.15
	hp=8
	}
	if(Me.x+10<x+(sprite_width/2)){
	dir=1
	}else{
	dir=0
	}

	if(image_index<0.3){
	chance=irandom(12)
	if(chance==0&&sprite_index!=bee2_spr){
	sprite_index=bee2_spr
	}else{
	sprite_index=bee_spr
	}}

	if(tick==0){
	if(y<firsty+range){
	y+=movespeed
	}else{
	tick=1
	}}else{
	if(tick==1){
	if(y>firsty-range){
	y-=movespeed
	}else{
	tick=0
	}}}
	if(x+16<Me.x+10-5){
	x+=movespeed/5
	}else{
	if(x+16>Me.x+10+5){
	x-=movespeed/5
	}}

	if(firsty+16<Me.y+10-5){
	firsty+=movespeed/5
	}else{
	if(firsty+16>Me.y+10+5){
	firsty-=movespeed/5
	}}

	}else{
	//DUMMY
	if(enemytype==8){
	if(check==1){
	y-=12
	check=0
	hp=1000
	sprite_index=present_roombonus_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	mask_index=sprite_index
	image_speed=0
	image_index=0
	}
	hp=1000
	}
	}}}}

	}}





}
