function worldone_rm5_enemy_scr() {

	//--------------------------------------------------------------------<<<<<<{PRESENT}>>>>>>--------------------------------------------------------------------
	if(enemytype==2){
	if(check==1){
	hp=10
	check=0
	xmid=8
	ymid=8
	sprite_index=present_spr
	mask_index=sprite_index
	imgsave=irandom(3)
	imgsave=imgsave*4
	damaging=0
	}else{
	if(image_index<imgsave||image_index>imgsave+4){
	image_index=imgsave
	}
	simplemove_scr(0)

	}}else{

	//--------------------------------------------------------------------<<<<<<{PRESENT FLOATING}>>>>>>--------------------------------------------------------------------
	if(enemytype==1){
	if(check==1){
	tick=choose(0,1)
	hp=10
	check=0
	damaging=0
	xmid=8
	ymid=8
	image_speed=0.005
	sprite_index=present_two_spr
	mask_index=sprite_index
	imgsave=irandom(3)
	imgsave=imgsave*10
	range=32
	movespeed=0.25
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	pin=70
	image_speed=0
	image_index=irandom(1)
	depth=other.depth+1
	sprite_index=present_balloon_spr
	}}
	if(image_index<imgsave||image_index>=imgsave+10){
	image_index=imgsave
	image_speed=0.005
	}
	if(image_index>=imgsave+1){
	image_speed=0.05
	damaging=1
	}
	simplemove_scr(1)
	with(selfcreated){
	x=other.x+8
	y=other.y-14
	}

	}else{

	//--------------------------------------------------------------------<<<<<<{KID FLOATING}>>>>>>--------------------------------------------------------------------
	if(enemytype==3){
	if(check==1){
	wepx=27
	wepy=29
	attdelay=120
	attdelaytotal=240
	tick=choose(0,1)
	hp=8
	xmid=22
	ymid=26
	check=0
	damaging=0
	image_speed=0.1
	sprite_index=present_kid_spr
	mask_index=sprite_index
	imgsave=irandom(1)
	imgpreset=0
	range=8
	movespeed=0.125
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	pin=70
	image_speed=0
	depth=other.depth-1
	sprite_index=present_wep_spr
	image_angle=210
	}}
	if(attdelay>0){
	attdelay-=1
	if(attdelay>attdelaytotal-12){
	y-=1
	}else{
	if(attdelay==attdelaytotal-20){
	}}
	with(selfcreated){
	direction=point_direction(x,y,Me.x+10,Me.y+12)
	image_angle=direction
	}
	}else{
	attdelay=attdelaytotal
	with(selfcreated){
	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=30;i>0;i-=1){
	//CONFETTI SHOT
	created=instance_create(x,y,Dummy_object)
	with(created){
	sprite_index=present_fetti_spr
	mask_index=sprite_index
	image_speed=0
	image_index=other.chance+other.i
	direction=other.direction
	direction+=irandom(7)*choose(-1,1)
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.4,0.8)
	duration=180+random(80)
	damage=1
	pin=73
	}}}
	}
	spot1=x+sprite_width/2
	spot2=Me.x+10
	if(imgsave==0){
	if(spot1<spot2+10&&spot1>spot2-10){
	imgpreset=2
	}else{
	if(spot1>spot2+10){
	imgpreset=0
	}else{
	imgpreset=4
	}}
	}else{
	if(spot1<spot2+10&&spot1>spot2-10){
	imgpreset=8
	}else{
	if(spot1>spot2+10){
	imgpreset=6
	}else{
	imgpreset=10
	}}
	}
	if(image_index<imgpreset||image_index>=imgpreset+2){
	image_index=imgpreset
	image_speed=0.075
	}

	simplemove_scr(1)
	with(selfcreated){
	x=other.wepx+other.x
	y=other.wepy+other.y
	}

	}else{

	//--------------------------------------------------------------------<<<<<<{CONTAINER FLOATING}>>>>>>--------------------------------------------------------------------
	if(enemytype==4){
	if(phase==0){
	if(check==1){
	tick=choose(0,1)
	movingcheck=0
	mecheck=0
	hp=10
	check=0
	damaging=0
	duration=240
	image_speed=0
	sprite_index=present_container_spr
	mask_index=dummy_spr
	imgsave=irandom(3)
	imgsave=imgsave*10
	range=0.5
	movespeed=0.005
	moving=0
	selfcreated=instance_create(x-5,y+20,Container)
	with(selfcreated){
	drop=0
	creator=other.id
	nograv=1
	startx=x
	starty=y
	subtype=other.subtype
	visible=false
	}
	depth=selfcreated.depth+1
	}
	if(instance_exists(selfcreated)){
	if(selfcreated.hp>1){
	image_index=0
	if(mecheck==0){
	if(selfcreated.y==selfcreated.starty){
	simplemove_scr(1)
	}else{
	with(selfcreated){
	if(y>starty){
	y-=0.05
	other.y=y-20
	}else{
	y=starty
	other.y=y-20
	}}}
	}else{
	mecheck=0
	}}else{
	image_index=1
	if(mecheck==0){
	selfcreated.y-=0.055
	y=selfcreated.y-20
	if(selfcreated.y<-8){
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}}else{
	mecheck=0
	}}}else{
	phase=1
	image_index=2
	duration=120
	}}else{
	if(duration>0){
	duration-=1
	y-=1
	}else{
	instance_destroy()
	}}
	if(y>room_height){
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}}else{

	//--------------------------------------------------------------------<<<<<<{RANDOM BLOCK}>>>>>>--------------------------------------------------------------------
	if(enemytype==5){
	if(phase==0){
	if(check==1){
	tick=choose(0,1)
	movingcheck=0
	mecheck=0
	hp=10
	check=0
	damaging=0
	duration=240
	image_speed=0
	sprite_index=present_randomballoon_spr
	mask_index=dummy_spr
	range=0.5
	movespeed=0.005
	moving=0

	selfcreated=instance_create(x-9,y+16,Container)
	with(selfcreated){
	if(other.subtype==0){
	imagemax=3
	}else{
	imagemax=4
	}
	imagesave=irandom(imagemax)
	image_index=imagesave
	clock=0
	clockcheck=imagesave
	for(i=0;i<imagemax;i+=1){
	loot_array[i]=i
	}
	depth=other.depth
	imagelevel=0
	delay=0
	delaytotal=80
	subtype=70
	creator=other.id
	nograv=1
	startx=x
	starty=y
	bomb=0
	sprite_index=present_randomblock_spr
	selfcreated=instance_create(x+8,y+8,Dummy_two_object)
	with(selfcreated){
	depth=other.depth
	pin=70
	starty=2
	image_speed=0
	sprite_index=present_randomitem_spr
	}
	mask_index=sprite_index
	}
	depth=selfcreated.depth+2
	}
	if(mecheck==0){
	simplemove_scr(1)
	selfcreated.y=y+16
	}else{
	mecheck=0
	}
	if(selfcreated.hp>1){
	with(selfcreated){
	//ROLL
	if(delay<=0){
	if(hurttick==0){
	if(imagesave<imagemax-0.07+imagelevel){
	imagesave+=0.035
	//imagesave+=0.05+imagelevel
	}else{
	imagesave=0
	}
	imagecheck=floor(imagesave)
	if(imagecheck!=clockcheck){
	clock=0
	clockcheck=imagecheck
	}else{
	clock+=0.15
	}
	selfcreated.image_index=loot_array[imagecheck]
	selfcreated.y=y+9+clock
	}else{
	if(!audio_is_playing(box1_snd)){
	audio_play_sound(box1_snd,1,false)
	}else{
	audio_stop_sound(box1_snd)
	audio_play_sound(box1_snd,1,false)
	}
	hurttick=0
	delay=delaytotal
	}}else{
	//Loot
	delay-=1
	if(selfcreated.y>y+12-0.15&&selfcreated.y<y+12+0.15){
	selfcreated.y=y+12
	}else{
	if(selfcreated.y<y+12-0.15){
	selfcreated.y+=0.15
	}else{
	if(selfcreated.y>y+12+0.15){
	selfcreated.y-=0.055
	}}}
	imagecheck=floor(imagesave)
	if(delay==delaytotal/2){
	//Bomb
	if(loot_array[imagecheck]==0){
	bomb=5
	}else{
	//Coin
	if(loot_array[imagecheck]==1){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	}else{
	//Tri Coin
	if(loot_array[imagecheck]==2){
	for(i=0;i<3;i+=1){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	}
	}else{
	//Heart
	if(loot_array[floor(imagecheck)]==3){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	created.subtype=1
	}}}
	}
	loot_array[imagecheck]=0
	selfcreated.image_index=0
	hurttick=0
	selfcreated.image_index=loot_array[imagecheck]
	}else{
	if(delay==0){
	}}}
	if(bomb!=0){
	//BLOWS UP
	if(bomb>1){
	Control.screenshake+=8
	bomb-=1
	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)

	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=20;i>0;i-=1){
	//CONFETTI BLAST
	created=instance_create(x+5,y+5,Dummy_object)
	with(created){
	sprite_index=present_fetti_spr
	mask_index=sprite_index
	image_speed=0
	image_index=other.chance+other.i
	direction=other.i*20
	direction+=(other.delay-1)*10
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.55,0.8)
	duration=120+random(80)
	damage=1
	pin=73
	}}}else{
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}}
	}
	if(!instance_exists(selfcreated)){
	phase=1
	duration=120
	image_index=1
	selfcreated=0
	}

	}}else{
	if(duration>0){
	duration-=1
	y-=1
	}else{
	instance_destroy()
	}
	}}else{


	//--------------------------------------------------------------------<<<<<<{YELLOW PRESENT ROOM}>>>>>>--------------------------------------------------------------------
	if(enemytype==6){
	if(phase==0){
	if(check==1){
	x+=8
	dir=0
	medamage=0
	check=0
	depth=Me.depth-1
	sprite_index=present_roombonus_spr
	mask_index=sprite_index
	image_index=0
	image_speed=0
	imagesave=0
	selfcreated=instance_create(x,y,Solid_plat)
	with(selfcreated){
	sprite_index=present_roombonusmask_spr
	image_index=1
	image_speed=0
	}
	created=instance_create(x,y,Dummy_two_object)
	with(created){
	sprite_index=present_roombonus_spr
	image_index=4
	imagesave=4
	image_speed=0
	depth=other.depth+8
	pin=70
	}
	hp=80
	}
	created.image_blend=image_blend
	if(hp<80&&hp>65){
	image_index=imagesave+1
	created.image_index=created.imagesave+1
	}else{
	if(hp<=65&&hp>50){
	image_index=imagesave+2
	created.image_index=created.imagesave+2
	}else{
	if(hp<=50){
	phase=1
	created.image_blend=c_white
	selfcreated.image_index=0
	image_index=imagesave+3
	created.image_index=created.imagesave+3
	mask_index=dummy_spr
	delay=0
	}else{
	}}}}

	}else{

	//______________________________****************************************{CAKE BOSS}****************************************______________________________
	if(enemytype==7){
	if(check==1&&phase==0&&extracheck==1){
	extracheck=0
	check=0
	mask_index=dummy_spr
	x=9897
	y=161

	endingx=9839
	endingy=160
	extragold=25
	extraxp=11

	delay=0
	blocktimes=0
	cakehurt=0
	attopt=choose(0,1,2)
	attdelay=0
	undie=1

	with(Control){
	rmcheck=1
	musicchange=music_boss_theme1
	}

	//----------------------------------CAKE LAYERS----------------------------------

	for(i=0;i<3;i+=1){

	//**********(BOTTOM)**********
	if(other.i==0){
	layerbottom=instance_create(x,y,Enemy)
	created=layerbottom
	with(created){
	sprite_index=cake_bottom_spr
	depth=20
	delay=120

	xpos1=-12
	xpos2=-1
	//Eyes
	xpos3=15
	xpos4=61
	ypos1=11

	//Mouth
	mouthy=23
	mouthx=47

	cakesprite=cake_eyethree_spr

	name="Cake Top"
	hpbuffer=0
	}}else{
	//**********(MID)**********
	if(other.i==1){
	layermid=instance_create(x+9,y-28,Enemy)
	created=layermid
	with(created){
	sprite_index=cake_mid_spr
	depth=15
	delay=240

	xpos1=-18
	xpos2=-7
	//Eyes
	xpos3=16
	xpos4=47
	ypos1=8

	//Mouth
	mouthy=20
	mouthx=38

	cakesprite=cake_eyetwo_spr

	name="Cake Mid"
	hpbuffer=0
	}}else{
	//**********(TOP)**********
	if(other.i==2){
	layertop=instance_create(x+22,y-57,Enemy)
	created=layertop
	with(created){
	sprite_index=cake_top_spr
	depth=10
	delay=360

	name="Cake Top"
	hpbuffer=0

	xpos1=-27
	xpos2=-15
	//Eyes
	xpos3=9
	xpos4=33
	ypos1=6

	//Mouth
	mouthy=18
	mouthx=25

	cakesprite=cake_eye_spr

	//Candles
	for(i=0;i<5;i+=1){
	created=instance_create(x,-10,Dummy_two_object)
	with(created){
	visible=false
	num=other.i
	sprite_index=candle_spr
	image_index=num
	image_speed=0
	depth+=other.depth-1
	pin=74
	xpos=8+(other.i*9)
	ypos=2
	if(num==0||num==4){
	ypos+=1
	}else{
	if(num==2){
	ypos+=3
	}}
	x=other.x+xpos
	created=instance_create(x,-10,Dummy_object)
	with(created){
	pin=79
	visible=false
	num=other.num
	sprite_index=fire_small_spr
	image_index=irandom(image_number)
	image_speed=0.15
	depth+=other.depth-1
	damage=0
	xpos=8+(other.num*9)
	ypos=2-sprite_height-8
	if(num==0||num==4){
	ypos+=1
	}else{
	if(num==2){
	ypos+=3
	}}
	x=other.x+xpos
	}}
	}

	}}}
	}

	with(created){
	num=other.i
	hp=1000

	mask_index=sprite_index
	attdelay=0
	phase=0
	image_speed=0
	enemytype=8
	dir=0
	creator=other.id
	immune=1
	phaseopt=0
	undie=1
	deathcheck=1
	firsty=y

	//CUPCAKE HELPERS
	for(i=0;i<2;i+=1){
	created=instance_create(x+xpos1+24,-16,Enemy)
	with(created){
	visible=false
	mask_index=dummy_spr
	sprite_index=cake_cupcake_spr
	image_speed=0
	enemytype=9
	creator=other.id
	dir=0

	imagesave=other.num*8
	image_index=imagesave
	if(other.i==1){
	x+=40+other.xpos2
	dir=1
	}}}

	ypos1-=1
	eyedelay=200+irandom(300)
	//EYES
	for(i=0;i<2;i+=1){
	eyes=instance_create(0,0,Dummy_two_object)
	with(eyes){
	visible=false
	imagesave=0
	delay=0
	sprite_index=other.cakesprite
	image_index=10
	image_speed=0
	depth=other.depth-1
	creator=other.id
	pin=72
	num=other.i
	if(other.i==1){
	num=2
	image_xscale=-1
	}}
	}


	mouthy+=5
	//MOUTH
	mouth=instance_create(0,0,Dummy_two_object)
	with(mouth){
	visible=false
	sprite_index=cake_mouth_spr
	image_speed=0
	depth=other.depth-1
	creator=other.id
	pin=73

	imagesave=other.num*5
	image_index=imagesave

	delay=400+irandom(400)
	chance=irandom(2)
	}

	//FALLING CAKE SLICES
	selfcreated=instance_create(x,-10,Dummy_two_object)
	with(selfcreated){
	visible=false
	sprite_index=other.sprite_index
	image_index=2
	image_speed=0
	depth+=1
	pin=70
	}
	}}

	with(layerbottom){
	layer1=other.layermid
	layer2=other.layertop
	Control.enemytargetthree=id
	}

	with(layermid){
	layer1=other.layerbottom
	layer2=other.layertop
	Control.enemytargettwo=id
	}

	with(layertop){
	layer1=other.layerbottom
	layer2=other.layermid
	Control.enemytarget=id
	}

	}

	//--------------------------------------------------------------------<<<<<<{ALWAYS}>>>>>>--------------------------------------------------------------------

	if(!instance_exists(layertop)&&!instance_exists(layermid)&&!instance_exists(layerbottom)){
	Control.ending=1
	}else{

	//EYES
	with(Dummy_two_object){
	if(pin==72){
	if(instance_exists(creator)){
	hurt=creator.hurt
	delay=creator.eyedelay
	if(hurt<=0){
	//Look
	xpos=creator.x+creator.sprite_width/2
	xrange=creator.xpos4/2
	if(xpos+xrange>Me.x+10&&xpos-xrange<Me.x+10){
	imagesave=3
	}else{
	if(xpos+xrange<Me.x+10){
	if(num==0){
	imagesave=6
	}else{
	imagesave=0
	}}else{
	if(xpos-xrange>Me.x+10){
	if(num==0){
	imagesave=0
	}else{
	imagesave=6
	}}}
	}

	//Blink
	if(delay>0){
	delay-=1

	if(delay<=60&&delay>40){
	image_index=imagesave+1
	}else{
	if(delay<=40&&delay>20){
	image_index=imagesave+2
	}else{
	if(delay<=20){
	image_index=imagesave+1
	}else{
	image_index=imagesave
	}}}}}else{

	//Hurt
	if(hurt>4){
	image_index=10
	}else{
	if(hurt<=4){
	image_index=9
	}}
	}

	//Positioning
	if(num==0){
	x=creator.x+creator.xpos3
	y=creator.y+creator.ypos1
	}else{
	x=creator.x+creator.xpos3+creator.xpos4
	y=creator.y+creator.ypos1
	}}else{
	instance_destroy()
	}}}


	//------------------------------{***CREATE BLOCK***}------------------------------
	if(phase==1){
	if(option==0){
	if(blocktimes==0){
	blocktimes=1
	}
	block=instance_create(9823,0,Enemy)
	with(block){
	enemytype=10
	creator=other.id
	}
	phase=0
	}else{

	if(option==1){
	phase=-1
	}else{
	if(option>1&&option<=4){
	if(check==1){
	check=0
	blocktimes+=1
	for(i=0;i<option-1;i+=1){
	meattack=instance_create(9806,10,Enemy)
	with(meattack){
	creator=other.id
	enemytype=11
	delay=other.i*80

	visible=false
	mask_index=dummy_spr
	sprite_index=cake_cupcake_spr
	image_speed=0
	dir=0

	imagesave=24
	image_index=24
	}
	if(instance_exists(layermid)){
	meattack.tox=layermid.x+(layermid.sprite_width/2)-(meattack.sprite_width/2)
	meattack.toy=layermid.y+(layermid.sprite_height/2)-(meattack.sprite_height/2)
	}else{
	if(instance_exists(layertop)){
	meattack.tox=layermid.x+(layertop.sprite_width/2)-(meattack.sprite_width/2)
	meattack.toy=layermid.y+(layertop.sprite_height/2)-(meattack.sprite_height/2)
	}else{
	if(instance_exists(layerbottom)){
	meattack.tox=layermid.x+(layerbottom.sprite_width/2)-(meattack.sprite_width/2)
	meattack.toy=layermid.y+(layerbottom.sprite_height/2)-(meattack.sprite_height/2)
	}else{
	with(meattack){
	instance_destroy()
	}}}}}
	}

	}else{

	}}}
	}else{


	if(phase==-1){
	with(Dummy_object){
	if(pin==79){
	damage=0
	visible=false
	}}
	if(instance_exists(layertop)){
	layertop.phase=7
	layertop.check=1
	}
	if(instance_exists(layermid)){
	layermid.phase=7
	layermid.check=1
	}
	if(instance_exists(layerbottom)){
	layerbottom.phase=7
	layerbottom.check=1
	}
	phase=-2
	}else{

	//------------------------------{***ATT PHASES***}------------------------------
	if(phase==2){
	if(delay>0){
	delay-=1
	if(instance_exists(layertop)){
	layertop.phase=6
	}
	if(instance_exists(layermid)){
	layermid.phase=6
	}
	if(instance_exists(layerbottom)){
	layerbottom.phase=6
	}
	}else{
	phase=3
	}

	}else{

	if(phase==3){
	phase=0
	if(instance_exists(layertop)||instance_exists(layermid)||instance_exists(layerbottom)){
	if(attopt==0){
	if(instance_exists(layerbottom)&&instance_exists(layermid)){
	attopt=choose(1,2)
	}else{
	if(instance_exists(layermid)){
	attopt=1
	}else{
	if(instance_exists(layerbottom)){
	attopt=2
	}}}
	}else{
	if(attopt==1){
	if(instance_exists(layerbottom)&&instance_exists(layertop)){
	attopt=choose(0,2)
	}else{
	if(instance_exists(layertop)){
	attopt=0
	}else{
	if(instance_exists(layerbottom)){
	attopt=2
	}}}
	}else{
	if(attopt==2){
	if(instance_exists(layertop)&&instance_exists(layermid)){
	attopt=choose(0,1)
	}else{
	if(instance_exists(layermid)){
	attopt=1
	}else{
	if(instance_exists(layertop)){
	attopt=0
	}}}}}}
	}else{
	attopt=-1
	}

	if(attopt==0){
	layertop.phase=8
	layertop.check=1
	layertop.phaseopt=0

	if(instance_exists(layermid)){
	layermid.phase=12
	}
	if(instance_exists(layerbottom)){
	layerbottom.phase=12
	}
	}else{
	if(attopt==1){
	layermid.phase=8
	layermid.check=1
	layermid.phaseopt=0

	if(instance_exists(layertop)){
	layertop.phase=12
	}
	if(instance_exists(layerbottom)){
	layerbottom.phase=12
	}
	}else{
	if(attopt==2){
	layerbottom.phase=8
	layerbottom.check=1
	layerbottom.phaseopt=0

	if(instance_exists(layertop)){
	layertop.phase=12
	}
	if(instance_exists(layermid)){
	layermid.phase=12
	}
	}}}}}}
	}

	if(cakehurt==1){
	cakehurt=2
	with(Enemy){
	if(enemytype==8){
	immune=0
	dr+=50
	drdraw+=50
	if(hurt<=0){
	hurttick=1
	}}}}else{
	if(cakehurt==2){
	with(Enemy){
	if(enemytype==8){
	if(hurt<=0){
	immune=1
	other.cakehurt=0
	}}}}
	}

	}
	}else{

	//--------------------------------------------------------------------<<<<<<{CAKE LAYERS}>>>>>>--------------------------------------------------------------------
	if(enemytype==8){
	//delay=200

	if(hp<=0&&phase!=8&&phase!=7){
	undie=0
	if(selfcreated!=0){
	if(instance_exists(selfcreated)){
	with(selfcreated){
	instance_destroy()
	}}}
	with(mouth){
	instance_destroy()
	}
	if(num==2){
	with(Dummy_two_object){
	if(pin==74){
	instance_destroy()
	}}}
	instance_destroy()
	}else{

	//--------------------------<<<<ALWAYS>>>>--------------------------

	if(phase==6){
	//TOP
	if(num==2){
	if(!instance_exists(layer1)&&!instance_exists(layer2)){
	starty=firsty+(sprite_height*2)-12
	}else{
	if(!instance_exists(layer1)||!instance_exists(layer2)){
	starty=firsty+sprite_height-3
	}}
	if(y<starty-1.5){
	y+=1.5
	}else{
	y=starty
	}}else{
	//MID
	if(num==1){
	if(!instance_exists(layer1)){
	starty=firsty+sprite_height-5
	}
	if(y<starty-1.5){
	y+=1.5
	}else{
	y=starty
	}
	}}}

	if(eyedelay>0&&hurt==0){
	eyedelay-=1
	}else{
	eyedelay=600+irandom(100)
	}
	//Mouth
	mouth.x=x+mouthx
	mouth.y=y+mouthy

	if(phase>3){
	with(mouth){
	hurt=other.hurt
	if(hurt<=0&&other.phase!=8){
	if(delay>0){
	delay-=1
	//1

	if(chance==0){
	if(delay==20){
	image_index=imagesave+1
	}else{
	if(delay==0){
	image_index=imagesave
	}}}else{
	//2
	if(chance==1){
	if(delay==60){
	image_index=imagesave+1
	}else{
	if(delay==40){
	image_index=imagesave
	}else{
	if(delay==20){
	image_index=imagesave+1
	}else{
	if(delay==0){
	image_index=imagesave
	}}}}}else{
	//3
	if(chance==2){
	if(delay==140){
	image_index=imagesave+1
	}else{
	if(delay==120){
	image_index=imagesave
	}else{
	if(delay==100){
	image_index=imagesave+1
	}else{
	if(delay==80){
	image_index=imagesave+2
	}else{
	if(delay==60){
	image_index=imagesave+1
	}else{
	if(delay==40){
	image_index=imagesave
	}else{
	if(delay==20){
	image_index=imagesave+1
	}else{
	if(delay==0){
	image_index=imagesave
	}}}}}}}}}}
	}
	}else{
	delay=400+irandom(400)
	chance=irandom(2)
	}}else{
	if(hurt>7){
	image_blend=other.image_blend
	image_index=15
	}else{
	if(hurt>1){
	image_index=16
	}else{
	if(hurt==1){
	image_index=imagesave
	delay=400+irandom(400)
	chance=irandom(2)
	image_blend=c_white
	}}}}}
	}
	if(phase>1){
	//Candles
	if(num==2){
	with(Dummy_two_object){
	if(pin==74){
	y=other.y+ypos
	x=other.x+xpos
	}}
	with(Dummy_object){
	if(pin==79){
	y=other.y+ypos
	x=other.x+xpos
	}}}
	}


	if(phase==0){
	if(delay>0){
	delay-=1
	}else{
	phase=1
	delay=40
	selfcreated.visible=true
	//CANDLES
	if(num==2){
	with(Dummy_object){
	if(pin==79){
	visible=true
	}}
	with(Dummy_two_object){
	if(pin==74){
	visible=true
	}}}
	with(Enemy){
	if(enemytype==9){
	if(creator.id==other.id){
	visible=true
	mask_index=sprite_index
	}}}}}else{
	if(phase==1){
	if(selfcreated.y<y-4){
	selfcreated.y+=2
	//CANDLES
	if(num==2){
	with(Dummy_two_object){
	if(pin==74){
	if(y<other.y+ypos){
	y+=2
	}else{
	y=other.y+ypos
	}}}
	with(Dummy_object){
	if(pin==79){
	if(y<other.y+ypos){
	y+=2
	}else{
	y=other.y+ypos
	}}}
	}
	}else{
	with(selfcreated){
	instance_destroy()
	}

	image_index=1
	phase=2
	}}else{

	//Roar
	if(phase==3){
	if(check==1){
	ticktwo=0
	rangetwo=30
	movespeedtwo=1.75
	startx=x
	starty=y
	check=0
	option=0
	//EYES
	with(Dummy_two_object){
	if(pin==72){
	if(creator.id==other.id){
	visible=true
	}}}
	mouth.visible=true
	if(num==1){
	tick=0
	}else{
	tick=1
	}
	range=3
	movespeed=0.5
	delay=80
	}else{
	if(delay>0){
	delay-=1

	if(delay==70){
	mouth.image_index+=1
	}else{
	if(delay==60){
	mouth.image_index+=1
	}else{
	if(delay==50){
	mouth.image_index+=1
	}else{
	if(delay==30){
	mouth.image_index-=1
	}else{
	if(delay==20){
	mouth.image_index-=1
	}else{
	if(delay==10){
	mouth.image_index-=1
	}}}}}
	}

	if(option<1){
	//Jump
	if(ticktwo==0){
	if(y>starty-rangetwo+movespeedtwo){
	y-=movespeedtwo
	if(y>layer1.y){
	layer1.y-=movespeedtwo
	}
	if(y>layer2.y){
	layer2.y-=movespeedtwo
	}
	}else{
	ticktwo=1
	}}else{
	if(y<starty-movespeedtwo){
	y+=movespeedtwo
	if(y>layer1.y){
	layer1.y+=movespeedtwo
	}
	if(y>layer2.y){
	layer2.y+=movespeedtwo
	}
	}else{
	ticktwo=0
	option+=1
	}}}else{
	if(option==1){
	option+=1
	y=starty
	layer1.y=layer1.starty
	layer2.y=layer2.starty
	}else{

	//Shake
	if(tick==0){
	if(x<startx+range){
	x+=movespeed
	}else{
	tick=1
	}}else{
	if(x>startx-range){
	x-=movespeed
	}else{
	tick=0
	}}}
	}

	}else{
	phase=4
	delay=180
	}}
	}else{

	//PHASE 4
	if(phase==4){
	if(delay>0){
	delay-=1
	if(x<startx-0.125){
	x+=0.125
	}else{
	if(x>startx+0.125){
	x-=0.125
	}}}else{
	phase=5
	check=1
	}}else{

	//PHASE 5
	if(phase==5&&num==0){
	if(check==1){
	delay=32
	movespeed=1.25
	check=0
	layer1dif=layer1.x-x
	layer2dif=layer2.x-x
	tox=x+50
	moving=1
	}

	if(layer1.phase==5){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	x+=movespeed
	if(delay<=20){
	layer1.x+=movespeed
	}}else{
	//Reset
	if(layer1.x<x+layer1dif||layer2.x<x+layer2dif){
	if(layer1.x<x+layer1dif){
	layer1.x+=movespeed
	delay-=1
	}
	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	}}else{
	delay=40
	}}
	}else{

	if(layer1.x<x+layer1dif||layer2.x<x+layer2dif){
	if(layer1.x<x+layer1dif){
	layer1.x+=movespeed
	delay-=1
	if(delay<-10){
	layer2.x+=movespeed
	}}else{
	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	}}}else{

	//Block Spawn
	phase=6
	if(creator.phase==0){
	creator.phase=1
	homex=x
	layer1.homex=layer1.x
	layer2.homex=layer2.x
	}}}
	}

	}else{

	//------------------------***{SEVEN}***------------------------
	if(phase==7){
	//------------BOTTOM------------
	if(num==0){
	if(instance_exists(layer1)||instance_exists(layer2)){
	if(check==1){
	delay=32
	movespeed=1.25
	check=0
	if(instance_exists(layer1)&&instance_exists(layer2)){
	layer1dif=layer1.x-x
	layer2dif=layer2.x-x
	layer1.immune=0
	layer2.immune=0
	choice=0
	}else{
	choice=1
	if(instance_exists(layer1)){
	layer1.immune=0
	layeronly=layer1
	layeronlydif=layeronly.x-x
	}else{
	layer2.immune=0
	layeronly=layer2
	layeronlydif=layeronly.x-x
	}}

	tox=homex-300
	moving=0
	immune=0
	}

	//BOTH
	if(choice==0){
	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	x+=movespeed
	if(delay<=20){
	layer1.x+=movespeed
	}}else{
	//Reset
	if(layer1.x<x+layer1dif||layer2.x<x+layer2dif){
	if(layer1.x<x+layer1dif){
	layer1.x+=movespeed
	delay-=1
	}
	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	}}else{
	delay=40
	}}
	}else{

	if(layer1.x<x+layer1dif||layer2.x<x+layer2dif){
	if(layer1.x<x+layer1dif){
	layer1.x+=movespeed
	delay-=1
	if(delay<-10){
	layer2.x+=movespeed
	}}else{
	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	}}}else{

	//End
	phase=6
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	creator.phase=2
	creator.delay=40
	creator.option=0
	layer1.x=layer1.homex
	layer1.phase=6
	layer1.immune=1
	layer2.x=layer2.homex
	layer2.phase=6
	layer2.immune=1
	phase=6
	immune=1
	x=homex
	}}
	}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	x-=movespeed
	if(delay<=20){
	layer1.x-=movespeed
	}}else{
	//Reset
	if(layer1.x>x+layer1dif||layer2.x>x+layer2dif){
	if(layer1.x>x+layer1dif){
	layer1.x-=movespeed
	delay-=1
	}
	if(layer2.x>x+layer2dif){
	layer2.x-=movespeed
	}}else{
	delay=40
	}}
	}else{

	if(layer1.x>x+layer1dif||layer2.x>x+layer2dif){
	if(layer1.x>x+layer1dif){
	layer1.x-=movespeed
	delay-=1
	if(delay<-10){
	layer2.x-=movespeed
	}}else{
	if(layer2.x>x+layer2dif){
	layer2.x-=movespeed
	}}}else{
	moving=1
	tox=homex
	delay=0
	}}}
	}}else{

	//ONLY ONE

	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	x+=movespeed
	if(delay<=20){
	layeronly.x+=movespeed
	}}else{
	//Reset
	if(layeronly.x<x+layeronlydif){
	layeronly.x+=movespeed
	delay-=1
	}else{
	delay=40
	}}
	}else{

	if(layeronly.x<x+layeronlydif){
	layeronly.x+=movespeed
	delay-=1
	}else{

	//End
	phase=6
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	creator.phase=2
	creator.delay=40
	creator.option=0
	layeronly.x=layeronly.homex
	layeronly.phase=6
	layeronly.immune=1
	immune=1
	x=homex
	}}
	}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	x-=movespeed
	if(delay<=20){
	layeronly.x-=movespeed
	}}else{
	//Reset
	if(layeronly.x>x+layeronlydif){
	layeronly.x-=movespeed
	delay-=1
	}else{
	delay=40
	}}
	}else{

	if(layeronly.x>x+layeronlydif){
	layeronly.x-=movespeed
	delay-=1
	}else{
	moving=1
	tox=homex
	delay=0
	}}}}}}else{

	//SOLO
	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x+=movespeed
	}}else{
	delay=50
	}}else{

	//End
	phase=6
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	creator.phase=2
	creator.delay=40
	creator.option=0
	immune=1
	x=homex
	}}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x-=movespeed
	}}else{
	delay=50
	}}else{
	moving=1
	tox=homex
	delay=0
	}}
	}

	}}else{

	//------------MID------------
	if(num==1){
	if(!instance_exists(layer1)){
	if(instance_exists(layer2)){
	if(check==1){
	delay=32
	movespeed=1.25
	check=0
	layer2dif=layer2.x-x
	tox=homex-300
	moving=0
	immune=0
	layer2.immune=0
	}

	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	x+=movespeed
	if(delay<=20){
	layer2.x+=movespeed
	}}else{
	//Reset
	if(layer2.x<x+layer2dif){
	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	delay-=1
	}}else{
	delay=40
	}}
	}else{

	if(layer2.x<x+layer2dif){
	layer2.x+=movespeed
	delay-=1
	}else{

	//End
	phase=6
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	creator.phase=2
	creator.delay=40
	creator.option=0
	layer2.x=layer2.homex
	layer2.phase=6
	immune=1
	layer2.immune=1
	x=homex
	}}
	}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	x-=movespeed
	if(delay<=20){
	layer2.x-=movespeed
	}}else{
	//Reset
	if(layer2.x>x+layer2dif){
	layer2.x-=movespeed
	delay-=1
	}else{
	delay=40
	}}
	}else{

	if(layer2.x>x+layer2dif){
	layer2.x-=movespeed
	delay-=1
	}else{
	moving=1
	tox=homex
	delay=0
	}}}
	}}else{

	//SOLO

	if(check==1){
	delay=32
	movespeed=1.25
	check=0
	tox=homex-300
	moving=0
	immune=0
	}
	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x+=movespeed
	}}else{
	delay=50
	}}else{

	//End
	phase=6
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	creator.phase=2
	creator.delay=40
	creator.option=0
	immune=1
	x=homex
	}}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x-=movespeed
	}}else{
	delay=50
	}}else{
	moving=1
	tox=homex
	delay=0
	}}
	}

	}
	}else{
	check=0
	}}else{

	//------------TOP------------
	if(num==2){
	if(!instance_exists(layer1)&&!instance_exists(layer2)){
	if(check==1){
	delay=32
	movespeed=1.25
	check=0
	tox=homex-300
	moving=0
	immune=0
	}

	if(moving==1){
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x+=movespeed
	}}else{
	//Reset
	delay=50
	}}else{
	//End
	with(Dummy_object){
	if(pin==79){
	damage=1
	visible=true
	}}
	phase=6
	creator.phase=2
	creator.delay=40
	creator.option=0
	immune=1
	x=homex
	}
	}else{

	//Moving Left
	if(moving==0){
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	if(delay<30){
	x-=movespeed
	}}else{
	//Reset
	delay=50
	}}else{
	moving=1
	tox=homex
	delay=0
	}}
	}
	}else{
	check=0
	}
	}}}
	}else{

	//------------------------***{Eight}***------------------------
	if(phase==8){

	//------------------------***{Bottom Attack}***------------------------
	if(num==0){
	if(phaseopt==0){
	if(check==1){
	immune=0
	check=0
	if(instance_exists(layer1)&&instance_exists(layer2)){
	choice=0
	layer1.toy=(layer1.y+layer1.sprite_height)-8
	layer2.toy=(layer2.y+layer2.sprite_height)-3
	}else{
	if(!instance_exists(layer2)){
	choice=1
	layeronly=layer1
	layeronly.toy=(layeronly.y+layeronly.sprite_height)-8
	}else{
	if(!instance_exists(layer1)){
	choice=1
	layeronly=layer2
	layeronly.toy=(layeronly.y+layeronly.sprite_height)-3
	}}}

	tox=choose(9776,9808,9839)
	toy=-20
	delay=30
	}
	Me.y-=0.0525

	//Settle Cakes
	if(choice==0){
	//BOTH
	if(layer1.y<layer1.toy-5){
	layer1.y+=2.5
	}else{
	layer1.y=layer1.toy
	}
	if(layer2.y<layer2.toy-5){
	layer2.y+=2.5
	}else{
	layer2.y=layer2.toy
	}}else{
	//ONLY ONE
	if(layeronly.y<layeronly.toy-5){
	layeronly.y+=2.5
	}else{
	layeronly.y=layeronly.toy
	}}

	//BOTH
	if(choice==0){
	if(y<=toy&&layer1.y>=layer1.toy&&layer2.y>=layer2.toy){
	if(delay<=0){
	phaseopt=1
	check=1
	x=tox
	y=toy
	}else{
	delay-=1
	}}else{
	if(layer1.y>=layer1.toy&&layer2.y>=layer2.toy){
	if(y>toy){
	y-=1
	}}}}else{
	//ONLY ONE
	if(y<=toy&&layeronly.y>=layeronly.toy){
	if(delay<=0){
	phaseopt=1
	check=1
	x=tox
	y=toy
	}else{
	delay-=1
	}}else{
	if(layeronly.y>=layeronly.toy){
	if(y>toy){
	y-=1
	}}}
	}
	mouth.image_index=mouth.imagesave

	}else{

	//PHASE 1: Fall phase
	if(phaseopt==1){
	if(check==1){
	check=0
	delay=360
	imagesave=4
	}
	if(delay>0){
	delay-=1
	y+=0.25
	}else{
	if(y<starty-1.5){
	y+=2.75
	if(delay>0){
	delay-=1
	}else{
	if(imagesave==4){
	imagesave=3
	}else{
	imagesave=4
	}}
	mouth.image_index=mouth.imagesave+imagesave
	}else{
	y=starty
	phaseopt=2
	check=1
	mouth.image_index=mouth.imagesave
	}}}else{

	//PHASE 2: Move Back
	if(phaseopt==2){
	if(check==1){
	delay=40
	movespeed=1.25
	check=0
	tox=homex
	}
	//Move
	if(x<tox){
	if(delay>0){
	delay-=1
	if(delay>10){
	x+=movespeed
	}}else{
	delay=40
	}}else{
	phaseopt=3
	check=1
	}}else{

	//PHASE 3: Settle Cakes
	if(phaseopt==3){
	if(check==1){
	check=0
	}
	//BOTH
	if(choice==0){
	if(layer1.y<=layer1.starty&&layer2.y<=layer2.starty){
	layer1.y=layer1.starty
	layer2.y=layer2.starty
	creator.phase=1
	creator.option=0
	immune=1
	phase=6
	}else{
	if(layer1.y>layer1.starty+1.5){
	layer1.y-=1.5
	}else{
	layer1.y=layer1.starty
	}
	if(layer2.y>layer2.starty+1.5){
	layer2.y-=1.5
	}else{
	layer2.y=layer2.starty
	}}
	}else{
	//ONLY ONE
	if(layeronly.y<=layeronly.starty){
	layeronly.y=layeronly.starty
	creator.phase=1
	creator.option=0
	immune=1
	phase=6
	}else{
	if(layeronly.y>layeronly.starty+1.5){
	layeronly.y-=1.5
	}else{
	layeronly.y=layeronly.starty
	}}}

	}}}}}else{
	//------------------------***{MID Attack}***------------------------
	if(num==1){
	if(check==1){
	check=0
	delay=160
	option=7
	optiontotal=7*21
	tickopt=7
	tick=0
	movespeed=1
	chance=choose(0,1)
	}
	if(tickopt>0){
	//Shake
	if(tick==0){
	if(x<homex+range){
	x+=movespeed
	}else{
	tick=1
	}}else{
	if(x>homex-range){
	x-=movespeed
	}else{
	tick=0
	}}
	if(delay>0){
	delay-=1
	}else{
	if(option>0){
	if(chance==1){
	created=instance_create(9776+(optiontotal-(option*21)),0,Enemy)
	}else{
	created=instance_create(9776+(option*21)-21,0,Enemy)
	}
	with(created){
	enemytype=12
	creator=other.id
	sprite_index=cake_cupcake_spr
	mask_index=sprite_index
	image_speed=0
	dir=0

	imagesave=irandom(2)*8
	image_index=imagesave
	}

	option-=1
	delay=100
	}else{

	}}
	}else{
	if(x<=homex+1&&x>=homex-1){
	creator.phase=1
	creator.option=0
	immune=1
	phase=6
	x=homex
	}else{
	if(x<=homex-1){
	x+=1
	}else{
	x-=1
	}}}

	}else{
	//------------------------***{TOP Attack}***------------------------
	if(num==2){
	if(phaseopt==0){
	if(check==1){
	immune=0
	check=0
	if(instance_exists(layer1)&&instance_exists(layer2)){
	toy=y+(sprite_height*2)-10
	}else{
	if(instance_exists(layer1)||instance_exists(layer2)){
	toy=y+sprite_height-7
	}else{
	toy=y
	}}
	tox=9904
	delay=40
	movespeed=1
	}
	if(x<=tox){
	y=toy
	x=tox
	phaseopt=1
	check=1
	}else{
	if(y<toy-2.5){
	y+=2.5
	}else{
	y=toy
	//Move
	if(x>tox){
	if(delay>0){
	delay-=1
	if(delay>10){
	x-=movespeed
	}}else{
	delay=40
	}}}}

	}else{

	//PHASE OPT: 1 ATTACK
	if(phaseopt==1){
	if(check==1){
	check=0
	delay=80
	tickopt=10
	jumpdelay=200
	tick=0
	toy=y
	}

	if(jumpdelay>0){
	if(jumpdelay>100){
	jumpdelay-=1
	}else{
	if(tick==0){
	if(y>toy-16*4){
	y-=1.5
	}else{
	tick=1
	}}else{
	if(y<toy-3){
	y+=1.5
	}else{
	jumpdelay=0
	y=toy
	tick=0
	}}}}else{
	jumpdelay=200
	if(tickopt<=0){
	y=starty
	phaseopt=2
	check=1
	}}

	if(tickopt>0){
	if(delay>0){
	delay-=1
	if(delay==42){
	mouth.image_index=mouth.imagesave+2
	}else{
	if(delay==36){
	mouth.image_index=mouth.imagesave+3
	}else{
	if(delay==30){
	mouth.image_index=mouth.imagesave+4
	created=instance_create(x+27,y+23,Dummy_object)
	with(created){
	pin=77
	sprite_index=cake_cakeproj_spr
	image_speed=0
	sped=0.25
	damage=1
	delay=240
	rangeone=random(5)
	rangetwo=random(5)
	}}else{
	if(delay==20){
	mouth.image_index=mouth.imagesave+3
	}else{
	if(delay==16){
	mouth.image_index=mouth.imagesave+2
	}else{
	if(delay==10){
	tickopt-=1
	mouth.image_index=mouth.imagesave
	delay=180
	}}}}}}
	}}else{
	phaseopt=2
	check=1
	}
	}else{

	//PHASE OPT 2: Move Back
	if(phaseopt==2){
	if(check==1){
	delay=40
	movespeed=1.25
	check=0
	}
	//Move
	if(x<homex){
	if(delay>0){
	delay-=1
	if(delay>10){
	x+=movespeed
	}}else{
	delay=40
	}}else{
	phaseopt=3
	check=1
	x=homex
	}}else{

	//PHASE OPT 3: Back Top
	if(phaseopt==3){
	if(check==1){
	check=0
	}
	if(y>starty+1.5){
	y-=1.5
	}else{
	y=starty
	creator.phase=1
	creator.option=0
	immune=1
	phase=6
	}

	}

	}}}}}}
	}



	}}}


	}}}}

	}else{

	//--------------------------------------------------------------------<<<<<<{CUPCAKE}>>>>>>--------------------------------------------------------------------
	if(enemytype==9){
	if(phase==0){
	if(check==1){
	check=0
	image_speed=0
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	pin=70
	image_speed=0
	image_index=irandom(1)
	depth=other.depth+1
	sprite_index=present_balloon_spr
	visible=false
	}}
	if(creator.phase==1){
	y+=2
	with(selfcreated){
	x=other.x+16
	y=other.y-8
	visible=true
	}
	if(imagesave==0){
	delay=4
	}else{
	if(imagesave==8){
	delay=2
	}else{
	if(imagesave==16){
	delay=1
	}}}}else{
	if(creator.phase==2){
	phase=1
	}}}else{

	if(selfcreated!=0){
	with(selfcreated){
	if(y>-2){
	y-=1
	}else{
	other.selfcreated=0
	instance_destroy()
	}}}

	if(phase==1){
	if(delay>0){
	y+=2
	delay-=1
	}else{
	yplus=y-creator.y
	phase=2
	check=1
	}}else{

	if(phase==2){
	if(check==1){
	check=0
	image_index=imagesave+2
	image_speed=0.05
	delay=160
	}

	y=creator.y+yplus
	delay-=1
	if(delay>60){
	if(image_index<imagesave+2||image_index>=imagesave+4){
	image_index=imagesave+2
	}}else{
	if(delay==60){
	image_index=imagesave+1
	image_speed=0
	}else{

	//BLOWS UP
	if(delay<=4&&delay>0){
	Control.screenshake+=8

	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)

	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=20;i>0;i-=1){
	//CONFETTI BLAST
	created=instance_create(x+15,y+15,Dummy_object)
	with(created){
	sprite_index=present_fetti_spr
	mask_index=sprite_index
	image_speed=0
	image_index=other.chance+other.i
	direction=other.i*20
	direction+=(other.delay-1)*10
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.4,0.6)
	duration=120+random(80)
	damage=1
	pin=73
	}}}else{
	if(delay==0){
	hp=0
	drop=0
	creator.phase=3
	creator.check=1
	}}}
	}

	}}}
	}else{

	//--------------------------------------------------------------------<<<<<<{BLOCK RANDOM}>>>>>>--------------------------------------------------------------------
	if(enemytype==10){
	if(phase==0){
	if(check==1){
	if(Me.hp<=Me.hptotal-1){
	Me.hp+=1
	}
	ycheck=1
	tick=choose(0,1)
	movingcheck=0
	mecheck=0
	hp=10
	check=0
	damaging=0
	duration=240
	image_speed=0
	sprite_index=present_randomballoon_two_spr
	mask_index=dummy_spr
	range=0.5
	movespeed=0.005
	moving=0

	rollspeed=0.025+(creator.blocktimes*0.0025)

	selfcreated=instance_create(x+16,y+50,Container)
	with(selfcreated){
	imagemax=6

	rollspeed=other.rollspeed
	imagesave=0
	image_index=0
	clock=0
	clockcheck=0

	loot_array[0]=0
	loot_array[1]=1
	loot_array[2]=0
	loot_array[3]=2
	loot_array[4]=0
	loot_array[5]=3

	creatortwo=other.creator

	depth=other.depth
	imagelevel=0
	delay=0
	delaytotal=80
	subtype=70
	creator=other.id
	nograv=1
	startx=x
	starty=y
	bomb=0
	sprite_index=present_randomblock_two_spr
	mask_index=sprite_index
	}
	depth=selfcreated.depth+2
	}

	if(ycheck==1){
	if(y<90){
	y+=0.5
	selfcreated.y=y+30
	with(selfcreated){
	hurttick=0
	while(place_meeting(x,y+1+(Me.vsp*-1),Me)){
	Me.y+=1
	Me.vsp=0.5
	}}
	}else{
	ycheck=0
	phase=1
	startx=x
	starty=y
	check=1
	}}
	}else{
	if(phase==1){
	if(check==1){
	check=0
	with(selfcreated){
	selfcreated=instance_create(x+8,y+20,Dummy_two_object)
	with(selfcreated){
	depth=other.depth
	pin=70
	starty=2
	image_speed=0
	sprite_index=present_randomitem_two_spr
	}}}

	if(mecheck==0){
	simplemove_scr(1)
	selfcreated.y=y+30
	}else{
	mecheck=0
	}
	if(selfcreated.hp>1){
	with(selfcreated){
	//__________________________-------------**********{ROLL}**********-------------__________________________
	if(delay<=0){
	if(hurttick==0){
	if(imagesave<imagemax-rollspeed+imagelevel){
	imagesave+=rollspeed
	//imagesave+=0.05+imagelevel
	}else{
	imagesave=0
	}
	imagecheck=floor(imagesave)
	if(imagecheck!=clockcheck){
	clock=0
	clockcheck=imagecheck
	}else{
	clock+=0.25+(rollspeed*10)
	}
	selfcreated.image_index=loot_array[imagecheck]
	selfcreated.y=y+4+clock
	}else{
	if(!audio_is_playing(box1_snd)){
	audio_play_sound(box1_snd,1,false)
	}else{
	audio_stop_sound(box1_snd)
	audio_play_sound(box1_snd,1,false)
	}
	hurttick=0
	delay=delaytotal
	}}else{
	//__________________________-------------**********{Loot}**********-------------__________________________
	if(selfcreated.y>y+15-0.15&&selfcreated.y<y+15+0.15){
	selfcreated.y=y+15
	delay-=1
	}else{
	if(selfcreated.y<y+15-0.15){
	selfcreated.y+=0.15
	}else{
	if(selfcreated.y>y+15+0.15){
	selfcreated.y-=0.055
	}else{
	}}}
	imagecheck=floor(imagesave)
	if(delay==delaytotal/2){
	//SKULL
	if(loot_array[imagecheck]==0){
	creatortwo.phase=1
	creatortwo.option=1
	creatortwo.check=1
	}else{
	//ONE
	if(loot_array[imagecheck]==1){
	creatortwo.phase=1
	creatortwo.option=2
	creatortwo.check=1
	}else{
	//TWO
	if(loot_array[imagecheck]==2){
	for(i=0;i<2;i+=1){
	creatortwo.phase=1
	creatortwo.option=3
	creatortwo.check=1
	}
	}else{
	//THREE
	if(loot_array[floor(imagecheck)]==3){
	for(i=0;i<3;i+=1){
	creatortwo.phase=1
	creatortwo.option=4
	creatortwo.check=1
	}
	}}}
	}
	//loot_array[imagecheck]=0
	//selfcreated.image_index=0
	other.phase=2
	hurttick=0
	//selfcreated.image_index=loot_array[imagecheck]
	}else{
	if(delay==0){
	}}}

	}
	if(!instance_exists(selfcreated)){
	other.phase=2
	selfcreated.mask_index=dummy_spr
	duration=120
	image_index=1
	selfcreated=0
	}}

	}else{
	if(phase==2){
	if(y>-5){
	y-=1
	with(selfcreated){
	y-=1
	selfcreated.y-=1
	}
	}else{

	with(selfcreated){
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}
	instance_destroy()
	}}

	}}
	}else{

	//--------------------------------------------------------------------<<<<<<{ME: CUPCAKE ATTACK}>>>>>>--------------------------------------------------------------------
	if(enemytype==11){
	if(phase==0){
	if(check==1){
	check=0
	immune=1
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	pin=70
	image_speed=0
	image_index=irandom(1)
	depth=other.depth+1
	sprite_index=present_balloon_spr
	mask_index=dummy_spr
	image_index=4
	visible=false
	}

	if(delay==0){
	visible=true
	}else{
	visible=false
	}
	image_speed=0.05
	}
	if(delay<=0){
	if(x<tox-20||y<toy-20){
	if(image_index<imagesave||image_index>=imagesave+2){
	image_index=imagesave
	}}
	if(x>=tox-20&&y>=toy-20){
	image_index=imagesave+2
	image_speed=0
	}
	if(x<tox||y<toy){
	if(y<toy){
	y+=0.4
	}
	if(x<tox){
	x+=0.5
	}
	with(selfcreated){
	x=other.x+16
	y=other.y-8
	visible=true
	}
	}else{

	phase=1
	check=1
	}}else{
	delay-=1
	if(delay==0){
	visible=true
	selfcreated.visible=true
	}
	}}else{

	if(phase==1){
	if(check==1){
	check=0
	delay=10
	}

	delay-=1

	//BLOWS UP
	if(delay<=6&&delay>0){
	Control.screenshake+=8

	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)

	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=20;i>0;i-=1){
	//CONFETTI BLAST
	created=instance_create(x+15,y+15,Dummy_object)
	with(created){
	sprite_index=present_fetti_two_spr
	mask_index=dummy_spr
	image_speed=0
	image_index=other.chance+other.i
	direction=other.i*20
	direction+=(other.delay-1)*10
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.4,0.6)
	duration=120+random(80)
	damage=1
	pin=73
	}}}else{
	if(delay==0){
	phase=2
	drop=0
	creator.cakehurt=1
	creator.phase=2
	creator.delay=240
	visible=false
	}}


	}else{

	if(phase==2){
	if(selfcreated!=0){
	with(selfcreated){
	if(y>-2){
	y-=1
	}else{
	other.selfcreated=0
	instance_destroy()
	}}}else{
	instance_destroy()
	}

	}}}


	}else{

	//--------------------------------------------------------------------<<<<<<{CAKE CUPCAKE ATTACK}>>>>>>--------------------------------------------------------------------
	if(enemytype==12){
	if(phase==0){
	if(check==1){
	damage=1
	check=0
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	pin=70
	image_speed=0
	image_index=0
	depth=other.depth+1
	sprite_index=present_balloon_spr
	mask_index=dummy_spr
	}
	image_speed=0.05
	visible=true
	image_speed=0.05
	hp=10000
	}
	if(y<160&&point_distance(x+sprite_width/2,y+sprite_height/2,Me.x+10,Me.y+10)>30){
	y+=1
	if(image_index<imagesave+2||image_index>=imagesave+4){
	image_index=imagesave+2
	}
	}else{
	phase=1
	check=1
	image_index=imagesave+1
	}
	with(selfcreated){
	x=other.x+16
	y=other.y-8
	}

	}else{

	if(phase==1){
	if(check==1){
	check=0
	delay=16
	}

	delay-=1

	//BLOWS UP
	if(delay<=6&&delay>0){
	Control.screenshake+=8

	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)

	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=20;i>0;i-=1){
	//CONFETTI BLAST
	created=instance_create(x+5,y+5,Dummy_object)
	with(created){
	sprite_index=present_fetti_spr
	mask_index=sprite_index
	image_speed=0
	image_index=other.chance+other.i
	direction=other.i*20
	direction+=(other.delay-1)*10
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.55,0.8)
	duration=20+random(40)
	damage=1
	pin=73
	}}}else{
	if(delay==0){
	phase=2
	drop=0
	creator.tickopt-=1
	visible=false
	mask_index=dummy_spr
	}}
	}else{
	if(phase==2){
	if(selfcreated!=0){
	with(selfcreated){
	if(y>-2){
	y-=1
	}else{
	other.selfcreated=0
	instance_destroy()
	}}}else{
	instance_destroy()
	}

	}}}}}}}}}}}}}}

	}



}
