function forestenemy_snow_scr() {
	if(enemytype==1){
	if(instance_position(x,y+16,Solid)){
	enemytype=3
	}else{
	enemytype=4
	}}

	//*******{Frost Golem}*******
	if(enemytype==4){
	if(check==1){
	check=0
	sprite_index=frostgolem_spr
	mask_index=sprite_index
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_speed=0.065
	attdelay=0
	created=0
	hp=16
	}
	if(Me.x+10>x+16){
	dir=0
	}else{
	dir=1
	}
	if(attdelay>0){
	attdelay-=1
	}else{
	image_index=20
	attdelay=280
	if(dir==1){
	created=instance_create(x+14,y+29,Dummy_object)
	}else{
	created=instance_create(x+18,y+29,Dummy_object)
	}
	with(created){
	pin=10
	creator=other.id
	sprite_index=iceshard_spr
	visible=true
	image_index=irandom(2)
	image_speed=0
	damage=1
	vsp=0

	grav=0.025
	tick=0
	duration=230
	bounce=random_range(2.8,3.5)
	}}
	}else{

	//*******{Stump}*******
	if(enemytype==2){
	if(check==1){
	check=0
	sprite_index=stump3_spr
	mask_index=sprite_index
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_speed=0
	attcd=0
	attone=0
	animdel=0
	}

	if(animdel<=0){
	if(image_index>1){
	animdel=random_range(70,84)
	//Awake
	if(image_index==2){
	image_index=3
	}else{
	if(image_index==3){
	image_index=2
	}}
	}else{
	animdel=random_range(170,210)
	//Sleeping
	if(image_index==0){
	image_index=1
	}else{
	if(image_index==1){
	image_index=0
	}}}
	}else{
	animdel-=1
	}

	if(attcd>0){
	attcd-=1
	}else{
	//Attack
	if(abs(y-Me.y)<20&&abs(x-Me.x)<70){
	attone=20
	attcd=360
	image_index=2
	audio_play_sound_at(choose(sandstorm_snd1,sandstorm_snd2),x,y,0,5,300,1,false,8)
	}else{
	if(image_index>1){
	image_index=0
	}}}

	if(attone>0){
	attone-=1
	if(attone==9){
	image_index=4
	}else{
	if(attone==0){
	image_index=2
	}}
	for(i=0;i<3;i+=1){
	if(dir==0){
	created=instance_create(x+13,y+random_range(9.5,10.5)+(i*random_range(1.5,2.5)),Dummy_object)
	}else{
	created=instance_create(x+3,y+random_range(9.5,10.5)+(i*random_range(1.5,2.5)),Dummy_object)
	}
	with(created){
	damage=0.5
	dir=other.dir
	tick=choose(0,1)
	starty=y
	sped=random_range(0.75,1.15)
	num=other.i
	pin=11
	hp=1
	creator=other.id
	duration=190
	sprite_index=frostleaf_spr
	image_index=irandom(2)
	image_speed=0
	}
	}}

	}else{

	//*******{Frost Turtle}*******
	if(enemytype==3){
	if(check==1){
	y+=2
	hp=6
	check=0
	tick=0
	startx=x 
	image_speed=0.15
	movespeed=0.3
	range=16
	sprite_index=frostturtle_spr
	mask_index=sprite_index
	xmid=sprite_width/2
	ymid=sprite_height/2
	}

	simplemove_scr(0)

	}else{

	//*******{Yeti Head}*******
	if(enemytype==5){
	if(check==1){
	hurtsound=snd_bosshurt_tree_2
	hurtsoundtwo=snd_bosshurt_tree_3
	blink=random_range(50,90)
	depth=1000002

	endingx=1730
	endingy=470
	extragold=25
	extraxp=11

	Control.enemytarget=id
	name="Frost Beast"
	hpbuffer=0


	phase=0
	delay=0
	tick=0
	ticktwo=0
	range=16
	rangetwo=12
	sped=0.15
	startx=x
	starty=y-16
	attdelay=120
	attdelaytwo=0
	atttick=0
	dir=0
	image_alpha=0
	alphaset=0
	check=0
	image_speed=0
	sprite_index=yetihead_spr
	mask_index=dummy_spr
	xmid=sprite_width/2
	ymid=sprite_height/2
	alphamulti=0.001
	eyes=0
	lastmove=0
	option=0
	hp=150
	}

	if(delay>0){
	delay-=1
	}

	//***{PHASE:0}***
	if(phase==0){
	if(Me.x>1728&&Me.y>480){
	phase=1
	with(Control){
	rmcheck=1
	musicchange=music_boss_theme2
	}

	//CREATED eyes
	eyes=instance_create(x-80,y+25,Dummy_object)
	with(eyes){
	pin=39
	image_speed=0
	sprite_index=yetieyes_spr
	depth=other.depth+1
	image_index=0
	}
	//CREATED HANDS
	handone=instance_create(x-80,y+25,Enemy)
	with(handone){
	creator=other.id
	enemytype=6
	tick=0
	ticktwo=0
	sped=0.125
	sprite_index=yetihand_spr

	mask_index=sprite_index
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_speed=0
	image_index=0
	dir=0
	image_alpha=0
	type=1

	Control.enemytargettwo=id
	name="Hand"
	hpbuffer=0
	}
	handtwo=instance_create(x+125,y+25,Enemy)
	with(handtwo){
	creator=other.id
	tick=1
	ticktwo=1
	sped=0.175
	enemytype=6
	sprite_index=yetihand_spr

	mask_index=sprite_index
	xmid=sprite_width/2
	ymid=sprite_height/2
	image_speed=0
	image_index=0
	dir=1
	image_alpha=0
	type=2
	Control.enemytargetthree=id
	name="Hand"
	hpbuffer=0
	}}}else{

	//***{PHASE:1}***
	if(phase==1){

	if(!instance_exists(handone)&&!instance_exists(handtwo)){
	mask_index=sprite_index
	}

	//Blink
	blink-=1

	if(blink<0){
	if(blink>-5){
	image_index=1
	}else{
	if(blink>-10){
	image_index=2
	}else{
	if(blink>-15){
	image_index=1
	}else{
	blink=random_range(80,180)
	image_index=0
	}}}}

	//move
	//x
	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	}}
	//y
	if(ticktwo==0){
	if(y<starty+rangetwo){
	y+=sped
	}else{
	ticktwo=1
	}}else{
	if(y>starty-rangetwo){
	y-=sped
	}else{
	ticktwo=0
	}}

	//ATTACK
	if(attdelay<=0){
	attdelay=random_range(200,240)
	blink=0
	phase=2

	}else{
	attdelay-=1
	}
	if(alphaset<1){
	alphamulti=alphamulti*1.15
	alphaset+=alphamulti
	image_alpha+=(alphamulti/3)
	}else{
	alphamulti=0.005
	}}else{

	//***{PHASE:2}***
	if(phase==2){
	//**********************{Attack}**********************
	if(blink==0){
	//***{HANDS}***
	if(instance_exists(handone)||instance_exists(handtwo)){
	audio_play_sound_at(choose(snd_yeti_roar_1,snd_yeti_roar_2),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	//GRAB
	if(lastmove==0){
	lastmove=1
	if(atttick==0||!instance_exists(handtwo)){
	if(instance_exists(handone)){
	atttick=1
	handone.phase=1
	}else{
	atttick=0
	handtwo.phase=1
	}}else{
	atttick=0
	handtwo.phase=1
	}}else{
	//SLAM
	if(lastmove==1){
	lastmove=0
	if(instance_exists(handone)){
	handone.phase=4
	handone.tick=0
	handone.image_index=2
	}
	if(instance_exists(handtwo)){
	handtwo.phase=4
	handtwo.tick=0
	handtwo.delay=16
	handtwo.image_index=2
	}}}
	}else{

	//***{HEAD}***
	if(lastmove==0){
	lastmove=1
	ending=1
	phase=3
	option=0
	}else{
	if(lastmove==1){
	lastmove=0
	phase=4
	option=0
	}}

	}}

	//Blink
	blink-=1

	if(blink<0){
	if(blink>-7){
	image_index=3
	}else{
	if(blink>-30){
	image_index=4
	//x
	if(tick==0){
	if(x<startx+5){
	x+=2.5
	}else{
	tick=1
	}}else{
	if(x>startx-5){
	x-=2.5
	}else{
	tick=0
	}}
	//y
	if(ticktwo==0){
	if(y<starty+rangetwo){
	y+=sped
	}else{
	ticktwo=1
	}}else{
	if(y>starty-rangetwo){
	y-=sped
	}else{
	ticktwo=0
	}}

	}else{
	if(blink>-37){
	image_index=3
	}else{
	blink=random_range(190,270)
	image_index=0
	phase=1
	}}}}

	}else{

	//***{PHASE:3}***
	if(phase==3){
	//Frost Breath
	if(option==0){
	opt=choose(1,2)
	option=1
	}else{
	if(option==1){
	if(opt==1){
	if(x+sprite_width/2>1632){
	x-=4
	}else{
	opt=3
	}}else{
	if(opt==2){
	if(x+sprite_width/2<1872){
	x+=4
	}else{
	opt=4
	}}else{
	if(opt==3){
	if(x+sprite_width/2<1872){
	x+=2
	//Flakes
	if(delay<=0){
	delay=random_range(14,30)
	yspot=y+56
	xspot=0
	audio_play_sound_at(choose(snd_yeti_icebreath_1,snd_yeti_icebreath_2),x,y, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<5;i+=1){
	created=instance_create(x+27+(xspot*10),yspot,Dummy_object)
	with(created){
	startx=x
	damage=1
	range=random_range(1.25,2.5)
	sped=random_range(0.75,1.25)
	sprite_index=frostbreath_spr
	image_speed=0
	pin=61
	tick=0
	}
	xspot+=1
	if(i==2){
	yspot-=10
	xspot=1
	}}}
	}else{
	phase=5
	}}else{
	if(opt==4){
	if(x+sprite_width/2>1632){
	x-=2
	//Flakes
	if(delay<=0){
	delay=random_range(14,30)
	yspot=y+56
	xspot=0
	audio_play_sound_at(choose(snd_yeti_icebreath_1,snd_yeti_icebreath_2),x,y, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<5;i+=1){
	created=instance_create(x+27+(xspot*10),yspot,Dummy_object)
	with(created){
	startx=x
	damage=1
	range=random_range(1.25,2.5)
	sped=random_range(0.75,1.25)
	sprite_index=frostbreath_spr
	image_speed=0
	pin=61
	tick=0
	}
	xspot+=1
	if(i==2){
	yspot-=10
	xspot=1
	}}}
	}else{
	phase=5
	}}}
	}
	}}}

	}else{

	//***{PHASE:4}***
	if(phase==4){
	//Attack 2
	if(option==0){
	option=1
	spot=0
	spotticktotal=0
	spottick=0
	spotcheck=0
	delay=0
	spottype=choose(1,-1)
	}else{
	spot+=1
	if(spotticktotal<8){
	if(spot mod 18==0){
	spotticktotal+=1
	audio_play_sound_at(choose(snd_yeti_icehit_1,snd_yeti_icehit_2),x,y, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<2;i+=1){
	if(spottype==1){
	if(i==0){
	created=instance_create(1744-16+(spotticktotal*16),512,Dummy_object)
	}else{
	created=instance_create(1744+16-(spotticktotal*16),512,Dummy_object)
	}}else{
	if(i==0){
	created=instance_create(1744-(16*8)+(spotticktotal*16),512,Dummy_object)
	}else{
	created=instance_create(1744+(16*8)-(spotticktotal*16),512,Dummy_object)
	}}
	with(created){
	damage=1
	depth=1000001
	pin=62
	sprite_index=frostpillar_spr
	image_speed=0
	starty=y
	tick=0
	check=1
	duration=60
	image_index=irandom(2)
	}}}
	}else{
	phase=1
	}

	}

	}else{

	//***{PHASE:5}***
	if(phase==5){
	if(x<startx-6||x>startx+5){
	if(x<startx-6){
	x+=2
	}else{
	x-=2
	}}else{
	phase=1
	}
	}}}

	}
	}}

	if(phase>0){
	if(!instance_exists(handone)&&!instance_exists(handtwo)){
	if(image_alpha<1){
	alphamulti=alphamulti*1.15
	image_alpha+=(alphamulti/4)
	}}}

	//EYES
	if(eyes!=0){
	with(eyes){
	x=other.x
	y=other.y
	if((y+sprite_height/2)+25<Me.y+5){
	if((x+sprite_width/2)-30<Me.x+10&&(x+sprite_width/2)+30>Me.x+10){
	image_index=3
	}else{
	if(x+sprite_width/2>Me.x+10){
	image_index=4
	}else{
	if(x+sprite_width/2<Me.x+10){
	image_index=5
	}}}
	}else{
	if((x+sprite_width/2)-30<Me.x+10&&(x+sprite_width/2)+30>Me.x+10){
	image_index=0
	}else{
	if(x+sprite_width/2>Me.x+10){
	image_index=1
	}else{
	if(x+sprite_width/2<Me.x+10){
	image_index=2
	}}}
	}}
	}

	}else{

	//*******{Hand}*******
	if(enemytype==6){
	if(check==1){
	depth=1000001
	phase=0
	range=8
	rangetwo=4
	startx=x
	starty=y
	check=0
	option=5
	delay=0
	hp=80
	}
	//***{PHASE:0}***
	if(phase==0){
	//move
	//x
	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	}}
	//y
	if(ticktwo==0){
	if(y<starty+rangetwo){
	y+=sped
	}else{
	ticktwo=1
	}}else{
	if(y>starty-rangetwo){
	y-=sped
	}else{
	ticktwo=0
	}}
	}else{

	//***{PHASE:1}***
	if(phase==1){
	if(instance_place(x,y,Me)){
	phase=3
	image_index=1
	}
	if(type==1){
	if(y<475){
	y+=1.5
	x+=1
	}else{
	if(x<1872){
	x+=4
	}else{
	phase=2
	}}
	}else{
	if(type==2){
	if(y<475){
	y+=1.5
	x-=1
	}else{
	if(x>1632){
	x-=4
	}else{
	phase=2
	}}}
	}
	}else{
	//***{PHASE:2}***
	if(phase==2){
	image_index=1
	if(x<startx+5&&x>startx-5&&y<starty+5&&y>starty-5){
	phase=0
	image_index=0
	}else{
	if(y>starty+range){
	y-=2.5
	}else{
	if(y<starty-range){
	y+=2.5
	}else{
	y=starty
	}}
	if(x>startx+range){
	x-=2.5
	}else{
	if(x<startx-range){
	x+=2.5
	}else{
	x=startx
	}}}
	}else{

	//***{PHASE:3}***
	if(phase==3){
	depth=1
	Me.x=x+13
	Me.y=y+14
	Me.dmgsafety=12
	if(x<startx+5&&x>startx-5&&y<starty+5&&y>starty-5){
	phase=0
	depth=1000001
	image_index=0
	}else{
	if(y>starty+range){
	y-=2.5
	}else{
	if(y<starty-range){
	y+=2.5
	}else{
	y=starty
	}}
	if(x>startx+range){
	x-=2.5
	}else{
	if(x<startx-range){
	x+=2.5
	}else{
	x=startx
	}}}
	}else{

	//***{PHASE:4}***
	if(phase==4){
	if(delay<=0){
	if(option>0){
	if(tick==0){
	if(y>starty-20){
	y-=2
	}else{
	tick=1
	}}else{
	if(y<451){
	y+=6
	}else{
	y=464
	option-=1.5
	tick=0
	Control.screenshake=10

	audio_play_sound_at(choose(snd_yeti_slam_1,snd_yeti_slam_2,snd_yeti_slam_3),x,y, 0, 90, 150, 0.5, false, 1)
	created=instance_create(irandom_range(1664,1824),350,Dummy_object)
	with(created){
	delay=44
	check=1
	damage=1
	pin=60
	sprite_index=iceshard_spr
	image_speed=0
	image_index=irandom(2)
	tick=3
	}
	}}
	}else{
	phase=2
	option=5
	}}else{
	delay-=1
	}}}}}}
	image_alpha=creator.alphaset
	}else{

	//*******{Frost Turtle Type: TWO}*******
	if(enemytype==7){
	if(check==1){
	x-=4
	y+=8
	y+=4
	hp=6
	check=0
	tick=0
	startx=x 
	starty=y
	image_speed=0.15
	movespeed=0.3
	rangeone=40
	rangetwo=22
	sprite_index=frostturtletwo_spr
	mask_index=sprite_index
	xmid=0
	ymid=0
	toangle=0
	newx=x
	newy=y
	}
	if(image_angle!=toangle){
	image_angle-=5
	}
	//Right
	if(tick==0){
	if(x<newx+(rangeone-movespeed)){
	x+=movespeed
	if(x>newx+(rangeone-(movespeed*8))){
	image_angle-=0.75
	}}else{
	tick=1
	toangle=270
	image_angle=toangle
	newx=x
	}}else{
	//Down
	if(tick==1){
	if(y<newy+(rangetwo-movespeed)){
	y+=movespeed
	if(y>newy+(rangetwo-(movespeed*8))){
	image_angle-=0.75
	}}else{
	tick=2
	toangle=180
	image_angle=toangle
	newy=y
	}}else{
	//Left
	if(tick==2){
	if(x>newx-(rangeone-movespeed)){
	x-=movespeed
	if(x<newx-(rangeone-(movespeed*8))){
	image_angle-=0.75
	}}else{
	tick=3
	toangle=90
	image_angle=toangle
	newx=x
	}}else{
	//Up
	if(tick==3){
	if(y>newy-(rangetwo-movespeed)){
	y-=movespeed
	if(y<newy-(rangetwo-(movespeed*8))){
	image_angle-=0.75
	}}else{
	tick=0
	toangle=0
	image_angle=toangle
	newy=y
	}}}}}

	}

	}}

	}}}



}
