if(Control.pause==0){
if(point_distance(x,y,Me.x,Me.y)<200){
if(subtype<10){
if(check==2){
image_index=imgindex
check=1
mask_index=sprite_index
if(subtype>5){
if(place_meeting(x,y,Container)){
instance_destroy()
}}}else{

if(hp>0){
if(delay>0){
delay-=1
hurttick=0
}else{
if(hurttick==1){
if(hp==2){
if(!audio_is_playing(box1_snd)){
audio_play_sound(box1_snd,1,false)
}else{
audio_stop_sound(box1_snd)
audio_play_sound(box1_snd,1,false)
}
}else{
if(!audio_is_playing(box1_snd)){
audio_play_sound(box1_snd,1,false)
}else{
audio_stop_sound(box1_snd)
audio_play_sound(box1_snd,1,false)
}}
hp-=1
delay=30
if(hp==2){
image_index=imgindex
}else{
if(hp==1&&drop==1){
if(subtype=0){
chance=irandom(3)
chancetotal=chance
if(chance>0){
for(i=chance;i>0;i-=1){
created=instance_create(x+sprite_width/2,y,Item)
created.itemtype=2
}}
if(chance=irandom(100)<=Control.itemsArray[0,8]){
created=instance_create(x+8,y+6,Item)
created.itemtype=2
}
}else{
if(subtype==1){
created=instance_create(x+sprite_width/2,y,Item)
created.itemtype=2
created.subtype=1
}else{

chest_ore_scr()

}}
}
if(subtype<5){
image_index=imgindex-1
}else{
image_index=0
}}}}

if(nograv==0){
if(!place_meeting(x,y+1,Solid)){
y+=1
}}

}else{
instance_destroy()
}}
}else{

}}}

