solidtype=1
image_speed=0
if(image_index==0){
if(!instance_place(x,y-16,Solid)){
image_index=1
}
if(instance_place(x+16,y,Solid)&&!instance_place(x,y-16,Solid))&&!instance_place(x-16,y,Solid){
image_index=2
}
if(instance_place(x-16,y,Solid)&&!instance_place(x+16,y,Solid)&&!instance_place(x,y-16,Solid)){
image_index=3
}
if(room!=room0){
if(instance_place(x+16,y,Solid)&&instance_place(x+32,y,Solid)&&!instance_place(x-16,y,Solid)&&!instance_place(x,y-16,Solid)&&!instance_place(x+16,y-16,Solid)){
if(!instance_place(x+16,y,Solid_noslope)){
image_index=4
side=instance_place(x+16,y,Solid)
side.image_index=5
}}
if(instance_place(x-16,y,Solid)&&instance_place(x-32,y,Solid)&&!instance_place(x+16,y,Solid)&&!instance_place(x,y-16,Solid)&&!instance_place(x-16,y-16,Solid)){
if(!instance_place(x-16,y,Solid_noslope)){
image_index=6
side=instance_place(x-16,y,Solid)
side.image_index=7
}}}
if(instance_place(x,y-16,Solid)&&instance_place(x-16,y,Solid)&&!instance_place(x,y+16,Solid)&&!instance_place(x+16,y,Solid)){
image_index=9
}
if(instance_place(x,y-16,Solid)&&instance_place(x+16,y,Solid)&&!instance_place(x,y+16,Solid)&&!instance_place(x-16,y,Solid)){
image_index=10
}
}

