function abilstrig_skeleton_scr(argument0) {
	//-------------------------------------------------<<**********<<{Auto: BONEMERANG}>>**********>>-------------------------------------------------
	if(argument0==0){
	if(check==1){
	check=0
	x=creator.x+10
	y-=2
	hitsave=0
	hittolerance=0
	pull=1
	direction=creator.direction
	if(direction==0){
	hsp=1.25+(Me.hsp/6)
	}else{
	hsp=(1.25+(abs(Me.hsp)/6))*-1
	}
	duration=300
	durationtotal=duration
	tick=0
	range=70
	if(option==0){
	vsp=0
	}else{
	if(option==1){
	vsp=0.5
	}else{
	if(option==2){
	vsp=-0.5
	}}}
	image_speed=0
	sprite_index=abil_skel1
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	image_index=0
	}else{
	image_index=1
	}}

	if(phase>=0){

	//Horizontal Collision
	if (place_meeting(x+hsp,y,Solid)){
	if(tick==0){
	tick=1
	}else{
	if(tick==2){
	yplus=0
	slope=2
	if(hsp>1){
	hsp=1
	}
	if(hsp<-1){
	hsp=-1
	}
	while (place_meeting(x+hsp,y-yplus,Solid)&&yplus<=2)yplus+=1;
	if(place_meeting(x+hsp,y-yplus,Solid)){
	while (!place_meeting(x+sign(hsp+extsp),y,Solid))x += sign(hsp+extsp);
	if(tick==2){
	hsp=0
	vsp=0
	tick=3
	}
	}else{
	y-=yplus
	}}}}

	if(tick==0||tick==1){
	hit=instance_place(x+hsp+hsp,y,Container)
	if(hit!=noone){
	hit.hurttick=1
	}}
	//RANGE
	if(duration==durationtotal-range&&tick==0){
	tick=1
	}

	//ENEMY
	hit=instance_place(x,y,Enemy)
	if(hittolerance<damage/2||hit!=hitsave){
	if(hit!=noone){
	if(tick==0){
	with(hit){
	dr+=(other.damage)*Control.itemsArray[0,4]
	drdraw+=(other.damage)*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}
	tick=1
	hitsave=hit
	hittolerance=10
	}else{
	if(hitsave==0||hitsave!=hit){
	hitsave=hit
	hittolerance=0
	}else{
	if(hittolerance+damage/10>damage/2){
	damage=((damage/2)-hittolerance)*10
	}}
	hittolerance+=damage/10

	with(hit){
	dr+=(other.damage/10)*Control.itemsArray[0,4]
	drdraw+=(other.damage/10)*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}}
	}

	//RETURN
	if(tick==1){
	//hsp=hsp*-1
	move_towards_point(Me.x+10,Me.y+12,2)
	hsp=hspeed
	vsp=vspeed
	speed=0
	tick=2
	}else{
	if(tick>=2){
	//ME CATCH
	if(instance_position(x,y,Me)){
	Control.charcdArray[creator.charid,abil]=0
	if(Me.mana<(Me.manatotal+Control.itemsArray[0,3])-(Control.abilArray[argument0,0])){
	Me.mana+=Control.abilArray[argument0,0]
	}else{
	Me.mana=Me.manatotal+Control.itemsArray[0,3]
	}
	instance_destroy()
	}}}

	if(tick!=3){
	//ITEM
	with(Item){
	if(point_distance(x,y,other.x,other.y)<6){
	if(hsp>0){
	x=other.x+1
	}else{
	x=other.x-1
	}
	y=other.y
	}}}

	//ALWAYS 
	x+=hsp
	y+=vsp
	if(abs(hsp)>abs(vsp)){
	if(hsp>0){
	image_angle+=(hsp*10)*-1
	}else{
	image_angle+=(hsp*10)
	}}else{
	if(vsp>0){
	image_angle+=(vsp*10)*-1
	}else{
	image_angle+=(vsp*10)
	}}}

	if(duration<=90){
	if(duration==90){
	visible=false
	}else{
	if(duration==84){
	visible=true
	}else{
	if(duration==60){
	visible=false
	}else{
	if(duration==54){
	visible=true
	}else{
	if(duration==30){
	visible=false
	}else{
	if(duration==24){
	visible=true
	}}}}}}}

	if(phase==-1){
	deathphase=1
	}}else{

	//-------------------------------------------------<<**********<<{TWO: SWORD}>>**********>>-------------------------------------------------
	if(argument0==1){
	if(check==1){
	check=0
	dir=direction
	if(option==0){
	if(creator.nowep==0){
	image_index=0
	}else{
	image_index=1
	}
	if(creator.nowep==0){
	image_index=0
	}else{
	image_index=1
	}
	}else{
	if(option==1){
	creator.vsp=2
	image_index=2
	if(direction==0){
	creator.moveaction=12
	}else{
	creator.moveaction=13
	}

	}else{
	if(option==2){
		creator.vsp=-1.25
	}
	}
	}
	image_speed=0
	duration=Control.abilArray[abil,5]
	visible=false
	}

	image_xscale=creator.drawflip

	if(option==0){
	x=creator.x+1
	y=creator.y
	if(creator.drawflip==-1){
	x+=20-2
	}
	hit=instance_place(x,y,Container)
	if(hit!=noone){
	hit.hurttick=1
	}

	if(duration<=((Control.abilArray[abil,5]/2)-2)){
	sprite_index=abil_skel2
	hitenemy=instance_place(x,y,Enemy)
	if(hitenemy!=noone){
	if(creator.nowep==0){
	hitenemy.dr+=damage*Control.itemsArray[0,4]
	hitenemy.drdraw+=damage*Control.itemsArray[0,4]
	}else{
	hitenemy.dr+=(damage*.75)*Control.itemsArray[0,4]
	hitenemy.drdraw+=(damage*.75)*Control.itemsArray[0,4]
	}
	if(hitenemy.hurt<=0){
	hitenemy.hurttick=1
	}
	deathphase=1
	}}
	}else{
	if(option==1){
	if(Control.charcdArray[creator.charid,0]<=1){
	Control.charcdArray[creator.charid,0]=4
	}
	if(Control.charcdArray[creator.charid,1]<=1){
	Control.charcdArray[creator.charid,1]=4
	}
	if(Control.charcdArray[creator.charid,2]<=1){
	Control.charcdArray[creator.charid,2]=4
	}
	if(Control.charcdArray[creator.charid,3]<=1){
	Control.charcdArray[creator.charid,3]=4
	}
	creator.animdel=4
	x=creator.x
	y=creator.y+2
	if(creator.drawflip==-1){
	x+=20
	}
	sprite_index=abil_skel2
	hit=instance_place(x,y+creator.vsp+1,Container)
	if(hit!=noone){
	hit.hurttick=1
	}
	hitenemy=instance_place(x,y+creator.vsp+2,Enemy)
	if(hitenemy!=noone){
	if(creator.nowep==0){
	hitenemy.dr+=damage*Control.itemsArray[0,4]
	hitenemy.drdraw+=damage*Control.itemsArray[0,4]
	if(hitenemy.hurt<=0){
	hitenemy.hurttick=1
	}
	creator.vsp=-2
	}
	deathphase=1
	}
	if(creator.grounded==0){
	duration=4
	}else{
	phase=-1
	}}
	}

	if(phase=-1){
	deathphase=1
	}

	}else{

	//-------------------------------------------------<<**********<<{THREE: SHIELD}>>**********>>-------------------------------------------------
	if(argument0==2){
	if(phase==0){
	if(check==1){
	for(i=0;i<6;i+=1){
	created=instance_create(x,y,Dummy_two_object)
	with(created){
	image_angle=irandom(360)
	creator=other.id
	num=other.i
	damage=1
	option=0
	dir1=num*60
	phase=0
	pin=100
	if(other.i<=9){
	ringtype=0
	}else{
	ringtype=1
	}
	sped=1.25
	Me.justhurt=0
	check=0
	hostile=0
	damage=0.1
	hsp=0
	vsp=0
	image_speed=0
	sprite_index=abil_skel3
	//image_xscale=0.8
	//image_yscale=0.8
	mask_index=sprite_index
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	image_index=0
	}else{
	image_index=1
	}}}
	ringsize=14
	ringsizemin=14
	ringsizetotal=28
	ringtick=0
	ringrange=8
	ringstart=8
	ringsped=0.01
	ringdelay=0
	ringdelayspeed=0.25
	check=0
	shield=0
	sped=0.5
	delay=4
	duration=400
	}
	x=creator.x+10
	y=creator.y+10

	if(Control.con_p_w||Control.conp_p_w){
	if(ringtick==0){
	ringtick=1
	}else{
	ringtick=0
	}}

	if(ringtick==1){
	if(ringsize<ringsizetotal){
	ringsize+=ringdelayspeed
	}}else{
	if(ringsize>ringsizemin){
	ringsize-=ringdelayspeed
	}}

	//--------------------------------****{BONES}****--------------------------------
	with(Dummy_two_object){
	if(pin==100){
	if(creator=other.id){
	//ALWAYS
	image_angle-=10
	if(phase==0){
	visible=other.visible
	dir2=(dir1+3+360)mod(360)
	dir1=dir2

	x=lengthdir_x(other.ringsize,dir2)+other.x
	y=lengthdir_y(other.ringsize,dir2)+other.y+3

	xspot=other.x
	yspot=other.y

	hitenemy=instance_place(x,y,Enemy)
	if(hitenemy!=noone){
	hitenemy.dr+=damage*Control.itemsArray[0,4]
	hitenemy.drdraw+=damage*Control.itemsArray[0,4]
	if(hitenemy.hurt<=0){
	hitenemy.hurttick=1
	}}
	}else{
	if(phase==2){
	visible=true
	if(duration<=90){
	if(duration==90){
	visible=false
	}else{
	if(duration==84){
	visible=true
	}else{
	if(duration==60){
	visible=false
	}else{
	if(duration==54){
	visible=true
	}else{
	if(duration==30){
	visible=false
	}else{
	if(duration==24){
	visible=true
	}}}}}}}
	//SHOOT
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	if(delay>0){
	delay-=1
	if(y<Me.y+10){
	y+=1
	}else{
	if(y>Me.y+14){
	y-=1
	}}}else{
	hitenemy=instance_place(x,y+creator.vsp,Enemy)
	if(hitenemy!=noone){
	hitenemy.dr+=damage*Control.itemsArray[0,4]
	hitenemy.drdraw+=damage*Control.itemsArray[0,4]
	if(hitenemy.hurt<=0){
	hitenemy.hurttick=1
	}
	instance_destroy()
	}
	y+=vsp
	if(instance_position(x,y,Solid)){
	instance_destroy()
	}}}}
	}}}

	//Shoot press
	if(delay>0){
	delay-=1
	}

	if(duration>1){
	if(duration<=90){
	if(duration==90){
	visible=false
	}else{
	if(duration==84){
	visible=true
	}else{
	if(duration==60){
	visible=false
	}else{
	if(duration==54){
	visible=true
	}else{
	if(duration==30){
	visible=false
	}else{
	if(duration==24){
	visible=true
	}}}}}}}
	}else{
	checkbone=1
	with(Dummy_two_object){
	if(pin==100){
	if(creator=other.id){
	checkbone=0
	if(phase==2){
	checkbone=1
	}else{
	instance_destroy()
	}}}}
	if(checkbone==1){
	duration=4
	}else{
	duration=0
	}}

	if(phase=-1){
	deathphase=1
	}}}}
	}



}
