with(Control){
if(snow!=0){
part_system_destroy(snow)
snow=0
}}

if(Control.pause==0){
if(delay>0){
delay-=1
}
if(animdraw<31.925){
animdraw+=0.0375
}else{
animdraw=0
}
if(animdraw2<63.8){
animdraw2+=0.1
}else{
animdraw2=0
}
if(animdraw3<127.9){
animdraw3+=0.05
}else{
animdraw3=0
}
if(animdraw4<63.75){
animdraw4+=0.125
}else{
animdraw4=0
}
if(animdraw5<127.85){
animdraw5+=0.075
}else{
animdraw5=0
}
if(animdraw6<20){
animdraw6+=0.15
}else{
animdraw6=0
}
if(animdraw7<3.98){
animdraw7+=0.01
}else{
animdraw7=0
}
if(animdraw8<24.25){
animdraw8+=0.0375
}else{
animdraw8=0
}

//**Movement**
if(moving==0){
if(check==1){
chance=0
animdel=irandom_range(124,240)
check=0
image_index=0
sprite_index=memap_idl
}
x=(mex*gridx)+borderx
y=(mey*gridy)+bordery

Control.charArray[Control.charselected,6]=mex
Control.charArray[Control.charselected,7]=mey

if(animdel>0){
animdel-=1
if(chance>0){
if(animdel==chancetime){
image_index-=1
}else{
if(animdel==chancetime-chancecd){
image_index=0
}}}
}else{
if(chance==0){
chance=choose(2,4,6)
}else{
if(chance==2){
chance=choose(4,6)
}else{
if(chance==4){
chance=choose(2,6)
}else{
if(chance==6){
chance=choose(2,4)
}else{

}}}}
if(chance==2){
chancecd=10
}else{
chancecd=irandom_range(30,50)
}
image_index=chance
animdel=irandom_range(124,240)
chancetime=animdel-chancecd
}

//***{Movement Checks}***
locked=0
overworldlevels_scr(1)


//MOVEMENT OVERWORLD
if(Control.actchoose==0){
if(Control.con_p_up||Control.conp_p_up){
if(mey>0){
if(Control.owLevels[mex,mey-1]<100){
if(Control.owLevels[mex,mey-1]==99){
toy=y-gridy
tox=(mex*gridx)+borderx
mey-=1
moving=1
Control.charArray[Control.charselected,5]=13
Control.charArray[Control.charselected,7]=Control.charArray[Control.charselected,7]-1
}else{
if(Control.levelsArray[Control.owLevels[mex,mey-1],4]==0){
toy=y-gridy
tox=(mex*gridx)+borderx
mey-=1
moving=1
Control.charArray[Control.charselected,5]=13
Control.charArray[Control.charselected,7]=Control.charArray[Control.charselected,7]-1
}}}}}else{
if(Control.con_p_right||Control.conp_p_right){
if(mex<3){
if(Control.owLevels[mex+1,mey]<100){
if(Control.owLevels[mex+1,mey]==99){
tox=x+gridx
toy=(mey*gridy)+bordery
mex+=1
moving=1
Control.charArray[Control.charselected,5]=15
Control.charArray[Control.charselected,6]=Control.charArray[Control.charselected,6]+1
}else{
if(Control.levelsArray[Control.owLevels[mex+1,mey],4]==0){
tox=x+gridx
toy=(mey*gridy)+bordery
mex+=1
moving=1
Control.charArray[Control.charselected,5]=15
Control.charArray[Control.charselected,6]=Control.charArray[Control.charselected,6]+1
}}}}}else{
if(Control.con_p_down||Control.conp_p_down){
if(mey<3){
if(Control.owLevels[mex,mey+1]<100){
if(Control.owLevels[mex,mey+1]==99){
toy=y+gridy
tox=(mex*gridx)+borderx
mey+=1
moving=1
Control.charArray[Control.charselected,5]=2
Control.charArray[Control.charselected,7]=Control.charArray[Control.charselected,7]+1
}else{
if(Control.levelsArray[Control.owLevels[mex,mey+1],4]==0){
toy=y+gridy
tox=(mex*gridx)+borderx
mey+=1
moving=1
Control.charArray[Control.charselected,5]=2
Control.charArray[Control.charselected,7]=Control.charArray[Control.charselected,7]+1
}}}}}else{
if(Control.con_p_left||Control.conp_p_left){
if(mex>0){
if(Control.owLevels[mex-1,mey]<100){
if(Control.owLevels[mex-1,mey]==99){
tox=x-gridx
toy=(mey*gridy)+bordery
mex-=1
moving=1
Control.charArray[Control.charselected,5]=9
Control.charArray[Control.charselected,6]=Control.charArray[Control.charselected,6]-1
}else{
if(Control.levelsArray[Control.owLevels[mex-1,mey],4]==0){
tox=x-gridx
toy=(mey*gridy)+bordery
mex-=1
moving=1
Control.charArray[Control.charselected,5]=9
Control.charArray[Control.charselected,6]=Control.charArray[Control.charselected,6]-1
}}}}}}}}
}else{

//ACT CHOOSE
with(Control){
if(actchar==0){
if(other.mex==2&&other.mey==1&&world==1||other.mex==2&&other.mey==0&&world==2){
actchoose=1
}else{
if(con_p_left||conp_p_left){
actchoose=1
}else{
if(con_p_right||conp_p_right){
actchoose=2
}}
	}
}
if(con_p_w||conp_p_q){
if(actchoose>0){
actchoose=0
actchar=0
}}}

}

}else{
check=1
}

if(y!=toy){
if(y<toy){
y+=0.5
}else{
y-=0.5
}}

if(x!=tox){
if(x<tox){
x+=0.5
}else{
x-=0.5
}}

if(abs(x-tox)<0.5&&abs(y-toy)<0.5){
x=tox
y=toy
moving=0
}

if(moving==1){
//Right
if(x<tox){
sprite_index=memap_r
}else{
//Left
if(x>tox){
sprite_index=memap_l
}else{
//Up
if(y>toy){
sprite_index=memap_u
}else{
//Down
if(y<toy){
sprite_index=memap_d
}}}}
}

if(moving==0){
image_speed=0
}else{
image_speed=0.1
}

}


/* */
/*  */
