function abilstrig_robot_scr(argument0) {
	//-------------------------------------------------<<**********<<{Auto: Plasma Shot}>>**********>>------------------------------------------------
	if(argument0==0){
	if(phase==0){
	if(check==1){
	check=0
	mask_index=abil_robo_imgmask_spr
	counter=0
	sfx_play(snd_yeti_icehit_2, 8, false) 
	type=1
	imgsave=-1
	modamount=-1
	}
	if(Me.direction==0){
	x=Me.x+12
	y=Me.y+15.5
	xpos=3
	}else{
	x=Me.x+8
	y=Me.y+15.5
	xpos=-9
	}
	duration=20
	counter+=1

	if(counter<30){
	type=1
	}else{
	if(counter<60){
	type=2
	if(counter==30){
	sfx_play(snd_yeti_icehit_2, 8, false) 
	}
	}else{
	type=3
	if(counter==60){
	sfx_play(snd_yeti_icehit_1, 8, false) 
	}
	}}
	if(!Control.con_h_e&&!Control.conp_h_e){
	phase=1
	check=1
	}

	//ChargeTrail
	for(i=0;i<type;i+=1){
	created=instance_create(x+xpos+irandom(2)*choose((type*.5),-(type*.5)),y+irandom(2)*choose((type*.5),-(type*.5)),Dummy_two_object)
	with(created){
	if(Me.direction!=0){
	image_xscale=-1
	}
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=irandom(3)+other.type*1
	durationtotal=duration
	move_towards_point(other.x,other.y,0.25)
	hsp=hspeed
	vsp=vspeed
	speed=0
	}}
	}else{


	//SHOOT PHASE 1
	if(check==1){
	check=0
	with(Me){
	animdel=Control.abilArray[other.abil,7]
	if(direction==0){
	moveaction=Control.abilArray[other.abil,6]
	}else{
	moveaction=Control.abilArray[other.abil,6]+1
	}}
	duration=90
	modamount=2
	if(type==1){
	imgsave=0
	damage=1.5
	useaudio=1
	if(Me.mana<=(Me.manatotal+Control.itemsArray[0,3])-10){
	Me.mana+=10
	}else{
	Me.mana=Me.manatotal+Control.itemsArray[0,3]
	}
	spellsnd=audio_emitter_create()
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play_on(spellsnd,snd_robot_plasmashot1,false,8) 
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play_on(spellsnd,snd_robot_plasmashot1_alt1,false,8) 
	}else{
	sfx_play_on(spellsnd,snd_robot_plasmashot1,false,8) 
	}}
	}else{
	if(type==2){
	imgsave=3
	damage=4
	useaudio=1
	if(Me.mana<=(Me.manatotal+Control.itemsArray[0,3])-5){
	Me.mana+=5
	}else{
	Me.mana=Me.manatotal+Control.itemsArray[0,3]
	}
	spellsnd=audio_emitter_create()
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play_on(spellsnd,snd_robot_plasmashot2,false,8) 
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play_on(spellsnd,snd_robot_plasmashot2_alt1,false,8) 
	}else{
	sfx_play_on(spellsnd,snd_robot_plasmashot2,false,8) 
	}}
	}else{
	if(type==3){
	imgsave=6
	damage=7
	useaudio=1
	if(Me.mana>=18){
	Me.mana-=18
	}else{
	Me.mana=0
	}
	spellsnd=audio_emitter_create()
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sfx_play_on(spellsnd,snd_robot_plasmashot3,false,8) 
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sfx_play_on(spellsnd,snd_robot_plasmashot3_alt1,false,8) 
	}else{
	sfx_play_on(spellsnd,snd_robot_plasmashot3,false,8) 
	}}
	}}}
	image_index=imgsave
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_spr
	}}
	image_speed=0
	if(Me.direction==0){
	dir=0
	hsp=1.625
	x=Me.x+12
	y=Me.y+15.5
	}else{
	dir=1
	hsp=-1.625
	image_xscale=-1
	x=Me.x+8
	y=Me.y+15.5
	}
	option=0
	if(Control.con_h_down||Control.conp_h_down){
	option=1
	vsp=0.625
	if(dir==0){
	image_angle-=20
	}else{
	image_angle+=20
	}}else{
	if(Control.con_h_up||Control.conp_h_up){
	option=1
	vsp=-0.625
	if(dir==0){
	image_angle+=20
	}else{
	image_angle-=20
	}}else{
	vsp=0
	}}
	if(type>1){
	if(dir==0){
	with(Me){
	debuff=1
	if(other.option==0){
	debufftimer=4*other.type
	debuffopt=-0.5*other.type
	vsp=-other.type*0.5
	}else{
	if(other.option==2){
	debufftimer=2*other.type
	debuffopt=-0.5*other.type
	vsp=1
	}else{
	debufftimer=2*other.type
	debuffopt=-0.25*other.type
	vsp=-0.75*other.type
	}}}}else{
	with(Me){
	debuff=1
	if(other.option==0){
	debufftimer=4*other.type
	debuffopt=0.5*other.type
	vsp=-other.type*0.5
	}else{
	if(other.option==2){
	debufftimer=2*other.type
	debuffopt=0.5*other.type
	vsp=1
	}else{
	debufftimer=2*other.type
	debuffopt=0.25*other.type
	vsp=-0.75*other.type
	}}
	}}}
	}

	if(imgsave==-1||modamount==-1){
	instance_destroy()
	}

	if(duration mod 10==0){
	if(image_index<imgsave+2){
	if(image_index<imgsave){
	image_index=imgsave
	}else{
	image_index+=1
	}}else{
	image_index=imgsave
	}}

	if(phase=-1){
	phase=-2
	//sprite_index=abil_robo_plasmashot_break_spr
	visible=false
	image_speed=0.1
	//End Explode Trail
	for(i=0;i<13;i+=1){
	if(duration mod modamount==0){
	created=instance_create(x+irandom(2)*choose((type*.5),-(type*.5)),y+irandom(2)*choose((type*.75),-(type*.75)),Dummy_two_object)
	with(created){
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=3+irandom(11)+other.type*7
	durationtotal=duration
	speed=random_range(0.05,0.3)
	direction=other.i*28
	hsp=hspeed
	vsp=vspeed
	speed=0
	}}}
	}
	if(phase==-2){
	if(image_index>=image_number-1){
	instance_destroy()
	}}

	if(phase>-1){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	Me.passivetarget=hit
	if(type==3){
	}else{
	if(type==1){
	if(Me.mana<(Me.manatotal+Control.itemsArray[0,3])-5){
	Me.mana+=5
	}else{
	Me.mana=(Me.manatotal+Control.itemsArray[0,3])
	}
	if(Me.passivetarget!=0){
	if(instance_exists(Me.passivetarget)){
	if(hit==Me.passivetarget){
	if(Me.mana<(Me.manatotal+Control.itemsArray[0,3])-10){
	Me.mana+=10
	}else{
	Me.mana=Me.manatotal+Control.itemsArray[0,3]
	}}}}
	}}
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	passivetarget=hit
	phase=-1
	with(hit){
	grav=0
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	phase=-1
	}
	//Leaf Trail
	for(i=0;i<type;i+=1){
	if(duration mod modamount==0){
	created=instance_create(x+irandom(2)*choose((type*.5),-(type*.5)),y+irandom(2)*choose((type*.75),-(type*.75)),Dummy_two_object)
	with(created){
	if(other.dir!=0){
	image_xscale=-1
	}
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=1+irandom(7)+other.type*3
	durationtotal=duration

	hsp=other.hsp*-1/8
	vsp=other.vsp*-1/8
	}}}
	x+=hsp
	y+=vsp

	if(duration>0){
	duration-=1
	}else{
	phase=-1
	}}


	}}else{
	//-------------------------------------------------<<**********<<{TWO: Ion Missile}>>**********>>-------------------------------------------------
	if(argument0==1){
	//SHOOT PHASE 1
	if(check==1){
	check=0

	delayedfire=20
	duration=70
	modamount=2
	useaudio=1

	spellsnd=audio_emitter_create()
	sfx_play_on(spellsnd,choose(snd_robot_ionmissile1,snd_robot_ionmissile2,snd_robot_ionmissile3),false,8) 
	damage=6
	image_index=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	//sprite_index=abil_robo_missile1_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	//sprite_index=abil_robo_missile1_alt1_spr
	}else{
	//sprite_index=abil_robo_missile1_spr
	}}
	image_speed=0.05
	if(Me.direction==0){
	dir=0
	hsp=2.5
	x=Me.x+12
	y=Me.y+15.5
	}else{
	dir=1
	hsp=-2.5
	image_xscale=-1
	x=Me.x+8
	y=Me.y+15.5
	}
	if(option==1){
	vsp=0.875
	if(dir==0){
	image_angle-=20
	}else{
	image_angle+=20
	}}else{
	if(option==2){
	vsp=-0.875
	if(dir==0){
	image_angle+=20
	}else{
	image_angle-=20
	}}else{
	vsp=0
	}}
	}

	x=Me.x+10
	y=Me.y+13

	//Delayed Missiles
	if(delayedfire>0){
	delayedfire-=1
	}else{
	instance_destroy()
	}
	if(delayedfire mod 6==0){
	i=irandom(3)
	created=instance_create(x,y+(i*2)-2,Dummy_two_object)
	with(created){
	dir=other.dir
	type=1
	pin=109
	damage=2.5
	image_angle=other.image_angle
	if(other.dir==0){
	image_xscale=1
	hsp=other.hsp+0.25
	vsp=other.vsp
	}else{
	image_xscale=-1
	hsp=other.hsp-0.25
	vsp=other.vsp
	}
	yoffset=other.i*2
	stall=10
	phase=1
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_missile2_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_missile2_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=40
	durationtotal=duration
	sped=1
	target=Me.passivetarget
	}}

	if(phase=-1){
	phase=-2
	sfx_play_on(spellsnd,choose(snd_robot_ionexp1,snd_robot_ionexp2),false,8) 
	Control.screenshake+=12
	//sprite_index=abil_robo_plasmashot_break_spr
	visible=false
	image_speed=0.1

	}
	/*
	if(phase>-1){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	passivetarget=hit
	phase=-1
	with(hit){
	grav=0
	if(Me.passivetarget!=0){
	if(instance_exists(Me.passivetarget)){
	if(id==Me.passivetarget){
	other.damage=other.damage*1.5
	}}}
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	phase=-1
	}
	//Leaf Trail
	for(i=0;i<2;i+=1){
	if(duration mod modamount==0){
	created=instance_create(x+((0.5+irandom(2))*choose(1,-1)),y+((0.5+irandom(2))*choose(1,-1)),Dummy_two_object)
	with(created){
	if(other.dir!=0){
	image_xscale=-1
	}
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=3+irandom(5)
	durationtotal=duration

	hsp=other.hsp*-1/8
	vsp=other.vsp*-1/8
	}}}
	x+=hsp
	y+=vsp

	if(duration>0){
	duration-=1
	}else{
	phase=-1
	}}
	*/

	}else{
	//-------------------------------------------------<<**********<<{THREE: Phaser Shield}>>**********>>-------------------------------------------------
	if(argument0==2){
	if(check==1){
	check=0

	if(Me.direction==0){
	dir=0
	}else{
	dir=1
	}

	if(Control.con_h_down||Control.conp_h_down||Control.con_h_up||Control.conp_h_up||Control.con_h_left||Control.conp_h_left||Control.con_h_right||Control.conp_h_right){
	with(Me){
	if(!Control.con_h_down&&!Control.conp_h_down&&!Control.con_h_up&&!Control.conp_h_up){
	debuff=1
	vsp=-1.5
	grav=0
	if(other.dir==0){
	debufftimer=18
	debuffopt=2.5
	}else{
	debufftimer=18
	debuffopt=-2.5
	}}else{
	if(Control.con_h_up||Control.conp_h_up){
	vsp=-2.5
	grav=0
	}else{
	vsp+=2.75
	}}}}

	sfx_play(snd_robot_blip1,8,false)
	duration=120
	image_speed=0.125
	image_index=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_shield_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_shield_alt1_spr
	}else{
	sprite_index=abil_robo_shield_spr
	}}
	}
	Me.immune=1
	x=Me.x+10
	y=Me.y+14
	Me.dr=0
	if(Me.hurttick>0){
	Me.hurttick=0
	sfx_play(snd_robot_blip2,8,false)
	Me.mana=Me.manatotal+Control.itemsArray[0,3]
	}
	if(duration>0){
	duration-=1

	}else{
	Me.immune=0
	instance_destroy()
	}

	}else{

	}}
	}




}
