function worldtwo_boss_enemy_scr() {
	//______________________________________________________________________------------------<<***{SKell}***>>------------------<________________________________________________________________________________
	if(enemytype==1){
	//____________________--------{PHASE:0}--------____________________
	if(phase==0){
	if(check==1){
	merange=600
	check=0
	delay=100
	image_speed=0.15
	option=-1
	tick=0
	sped=0.1
	range=2
	target=skullone
	skullleft=0
	hp=600
	hptotal=hp
	attlast=0
	ending=1

	Control.enemytarget=id
	name="Skell"
	hpbuffer=0

	endingx=512
	endingy=222-16
	extragold=100
	}

	if(option==-1){
	if(Me.x>352){
	option=0
	with(Control){
	rmcheck=1
	musicchange=music_boss_theme5
	}
	}}
	if(option==0){
	option=1
	visible=true
	sprite_index=skell_hover
	}else{
	if(option==1){
	if(y>starty-64){
	y-=2
	}else{
	option=2
	savey=y
	}}else{
	if(option==2){
	if(tick==0){
	if(y<savey+range){
	y+=sped
	}else{
	tick=1
	}}else{
	if(y>savey-range){
	y-=sped
	}else{
	tick=0
	}}

	if(image_index>=9){
	option=3
	audio_play_sound_at(choose(bat_snd1,bat_snd2),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	created=instance_create(x,y,Dummy_object)
	with(created){
	duration=99999
	pin=1
	xoffset=0
	yoffset=0
	xpos=0
	ypos=0
	damage=1
	sped=1
	sprite_index=skell_butterfly
	sped=1
	image_speed=0.2
	type=0
	target=other.target
	}}}else{
	if(option==3){
	sprite_index=skell_transfer
	image_index=1
	option=4
	}else{
	if(option==4){
	if(image_index>=image_number-1){
	option=5
	visible=false
	}
	}else{
	if(option==5){
	image_blend=c_blue
	if(skullleft==0){
	if(!instance_exists(skullone)){
	skullleft=1
	target=skulltwo
	option=6
	}}else{
	if(skullleft==1){
	if(!instance_exists(skulltwo)){
	skullleft=2
	target=skullthree
	option=6
	}}else{
	if(skullleft==2){
	if(!instance_exists(skullthree)){
	skullleft=3
	target=skullfour
	option=6
	}}else{
	if(skullleft==3){
	if(!instance_exists(skullfour)){
	skullleft=4
	target=0
	option=6
	}}}}}}else{
	if(option==6){
	delay=100
	image_speed=0.15
	tick=0
	sped=0.1
	range=2
	visible=true
	phase=1
	check=1
	option=0
	}}}}}}
	}
	delay-=1
	}else{
	//____________________--------{PHASE:1}--------____________________
	if(phase==1){
	if(check==1){
	check=0
	option=0
	times=0
	attopt=choose(0,1)
	attlast=attopt
	visible=false
	immune=0
	telex=choose(0,1)
	moveop=0
	if(telex==3){
	moveop=1
	}}
	//hpcheck
	if(option>0&&option<4){
	mask_index=sprite_index
	if(skullleft==1){
	if(hp<=hptotal*0.75){
	hp=hptotal*0.75
	option=4
	visible=false
	mask_index=dummy_spr
	immune=1
	dr=0
	hurttick=0

	}}else{
	if(skullleft==2){
	if(hp<=hptotal*0.5){
	hp=hptotal*0.5
	option=4
	visible=false
	mask_index=dummy_spr
	immune=1
	dr=0
	hurttick=0
	}
	}else{
	if(skullleft==3){
	if(hp<=hptotal*0.25){
	hp=hptotal*0.25
	option=4
	visible=false
	mask_index=dummy_spr
	immune=1
	dr=0
	hurttick=0
	}}}
	}}

	//Move Walls
	if(option==0){
	with(wallone){
	if(x<startx+48){
	x+=1
	if(instance_place(x+1,y,Me)){
	Me.x+=1
	}}}
	with(walltwo){
	if(x>startx-48){
	x-=1
	if(instance_place(x,y,Me)){
	Me.x-=1
	}}}
	with(wallthree){
	if(y>starty-64-16-32){
	y-=1
	if(instance_place(x,y,Me)){
	Me.y-=1
	}}else{
	other.option=1
	}}
	with(wallfour){
	if(y>starty-64-16-32){
	y-=1
	if(instance_place(x,y,Me)){
	Me.y-=1
	}}}
	with(wallfive){
	if(y>starty-64-16){
	y-=1
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}
	with(wallsix){
	if(y>starty-64-16){
	y-=1
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}}else{

	//TELEPORT
	if(option==1){
	visible=true
	immune=0
	if(telex==0){
	x=wallthree.x-20
	y=wallthree.y-40
	telex=choose(1,2)
	moveop=0
	}else{
	if(telex==1){
	x=wallfour.x-20
	y=wallfour.y-40
	telex=choose(0,2)
	moveop=0
	}else{
	if(telex==2){
	x=startx
	y=starty
	telex=choose(0,1)
	moveop=0
	}else{
	if(telex==3){
	x=startx
	y=starty-64
	telex=choose(0,1,2)
	moveop=1
	}}}}
	sprite_index=skell_appear
	image_index=0
	option=2
	delay=15
	opt=0
	}else{
	//Movement and Attack
	if(option==2){
	if(opt==0){
	if(delay>0){
	delay-=1
	}else{
	opt=1
	option=3
	savex=x
	savey=y
	if(skullleft==1){
	delay=210
	extra=0
	}else{
	if(skullleft==2){
	delay=170
	extra=1
	}else{
	if(skullleft==3){
	delay=130
	extra=2
	}else{
	if(skullleft==4){
	delay=75
	extra=3
	}}}
	}
	if(moveop==0){
	sprite_index=skell_w
	image_index=0
	tick=choose(0,1)
	if(tick==1){
	dir=1
	}
	image_speed=0.3
	range=32
	}else{
	sprite_index=skell_hover
	image_index=0
	range=8
	}}}
	}else{
	//carry out move
	if(option==3){
	if(delay>0){
	delay-=1
	if(delay>15){
	if(moveop==0){
	if(tick==0){
	if(x<savex+range){
	x+=1
	}else{
	tick=1
	dir=1
	}}else{
	if(x>savex-range){
	x-=1
	}else{
	tick=0
	dir=0
	}}
	}else{
	if(image_index>=9){
	delay=0
	}
	if(tick==0){
	if(y<savey+range){
	y+=0.025
	}else{
	tick=1
	}}else{
	if(y>savey-range){
	y-=0.025
	}else{
	tick=0
	}}}
	}else{
	if(delay==15){
	sprite_index=skell_transfer
	image_index=0
	}}}else{
	if(times==2){
	times=9
	telex=3
	}else{
	if(times==10){
	times=0
	if(attopt==0){
	attopt=1
	audio_play_sound_at(choose(bat_snd1,bat_snd2),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<3+extra;i+=1){
	created=instance_create(x+random_range(-2,2),y+random_range(-2,2),Dummy_object)
	with(created){
	xoffset=choose(random_range(0.5,2),random_range(0.5,2)*-1)
	yoffset=choose(random_range(0.5,2),random_range(0.5,2)*-1)
	pin=1
	damage=1
	duration=120
	sprite_index=skell_butterfly
	sped=1+(other.extra*0.2)+(other.i*0.1)
	image_speed=0.2
	image_index=irandom(image_number)
	type=1
	target=Me
	xpos=10
	ypos=12
	}}}else{
	attopt=0
	xpos=choose(92,804)
	ypos=choose(240,240,240-48,240-48-32)
	audio_play_sound_at(choose(snd_yeti_roar_1,snd_yeti_roar_2),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<9+(extra*3);i+=1){
	created=instance_create(xpos,ypos,Dummy_object)
	with(created){
	depth=20
	pin=4
	damage=1
	duration=120
	if(x==92){
	dir=0
	hsp=3
	x-=other.i*19
	endx=804
	image_xscale=-1
	}else{
	dir=1
	hsp=-3
	x+=other.i*19
	endx=92
	}
	vsp=0
	sprite_index=boss_skell_dragon_spr
	if(other.i==0){
	image_index=0
	y-=3
	}else{
	if(other.i==8+other.extra*3){
	image_index=2
	}else{
	image_index=1
	}}
	starty=y
	tick=0
	delay=other.i*2
	image_speed=0
	type=1
	xpos=10
	ypos=12
	}}
	}}}
	times+=1
	option=1
	dir=0
	image_speed=0.15
	}}else{
	//RESET WALLS
	if(option==4){
	with(wallone){
	if(x>startx){
	x-=1
	}}
	with(walltwo){
	if(x<startx){
	x+=1
	}}
	with(wallthree){
	if(y<starty){
	y+=1
	}else{
	other.option=5
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}
	with(wallfour){
	if(y<starty){
	y+=1
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}
	with(wallfive){
	if(y<starty){
	y+=1
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}
	with(wallsix){
	if(y<starty){
	y+=1
	}
	if(instance_place(x,y,Me)){
	Me.y=y-20
	}}
	}else{
	//RESET
	if(option==5){
	delay=100
	image_speed=0.15
	option=0
	tick=0
	sped=0.1
	range=2
	visible=true
	mask_index=dummy_spr

	created=instance_create(x+sprite_width/2,y,Item)
	created.itemtype=2
	created.subtype=1

	x=startx
	y=starty-64-16
	phase=0
	}}}}}}

	}else{

	}}}else{
	//______________________________________________________________________------------------<<***{Skulls}***>>------------------<________________________________________________________________________________
	if(enemytype==2){
	//____________________--------{PHASE:0}--------____________________
	if(phase==0){
	if(check==1){
	merange=600
	xmid=0
	ymid=0
	dir=0
	check=0
	tick=0
	range=2
	startx=x
	starty=y
	sped=1
	hp=150
	immune=1
	}

	}else{

	//____________________--------{PHASE:1}--------____________________
	if(phase==1){
	if(check==1){
	check=0
	option=0
	immune=0
	}

	if(option<3){
	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	option+=1
	}}}else{
	image_index=3
	if(type==1){
	phase=2
	}else{
	phase=3
	ringsize=12
	ringrange=15
	ringsizetotal=ringsize
	ringtick=0
	for(i=0;i<11;i+=1){

	created=instance_create(x,y,Dummy_object)
	with(created){
	creator=other.id
	delay=other.i*7
	zonex=irandom_range(-2,2)
	zoney=random_range(1,2.5)*choose(1,-1)
	range=10
	option=0
	visible=false

	imgsped=20
	image_angle=irandom(360)
	dir1=0
	ringtype=0
	ringsize=150
	ringtick=0
	ringrange=8
	ringstart=8
	ringsped=0.2

	sprite_index=skell_bone
	sped=4
	damage=1
	duration=12

	vsp=0
	hsp=sped
	diedelay=0

	//useaudio=1
	image_speed=0
	pin=5
	}}}
	check=1
	}

	}else{
	//____________________--------{PHASE:2}--------____________________
	if(phase==2){
	if(check==1){
	check=0
	option=0
	savex=x
	savey=y-8
	spedtwo=1
	delay=5
	mecheck=0
	opt=0
	tick=0
	mask_index=sprite_index
	if(id==creator.skullone){
	extra=0
	}else{
	extra=1
	}}


	if(opt==0){
	if(y>savey){
	y-=spedtwo
	}else{
	opt=1
	}}else{
	if(opt==1){

	if(justhurt==1){
		justhurt=0
	Control.screenshake=3
	for(i=0;i<8+(extra*5);i+=1){
	created=instance_create(irandom_range(224,672),3,Dummy_object)
	with(created){
	pin=2
	delay=irandom(50)
	damage=0.5
	sprite_index=skell_brick
	image_index=irandom(image_number)
	image_speed=0
	sped=choose(2,2.5,3,3.5)
	image_angle=random(360)
	}}
	}

	if(delay>0){
	if(mecheck==1){
	delay-=1
	}else{
	image_index=3
	}
	if(x>Me.x&&x<Me.x+20){
	image_index=3
	mecheck=1
	}else{
	if(x<Me.x){
	image_index=5
	}else{
	image_index=6
	}}
	if(x<Me.x+8){
	x+=spedtwo
	savex=x
	}else{
	if(x>Me.x+12){
	x-=spedtwo
	savex=x
	}}}else{
	opt=2
	image_index=4
	mask_index=sprite_index
	}}else{
	if(opt==2){
	if(!instance_place(x,y+1,Solid)){
	y+=6
	}else{
	opt=3
	savex=x
	delay=30
	image_index=0
	immune=1
	mask_index=sprite_index
	Control.screenshake=12
	audio_play_sound_at(choose(snd_yeti_slam_1,snd_yeti_slam_2,snd_yeti_slam_3),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<35+(extra*32);i+=1){
	created=instance_create(irandom_range(224,672),3,Dummy_object)
	with(created){
	pin=2
	delay=irandom(50)
	damage=0.5
	sprite_index=skell_brick
	image_index=irandom(image_number)
	image_speed=0
	sped=choose(2,2.5,3,3.5)
	image_angle=random(360)
	}}

	}}else{
	if(opt==3){
	if(delay>0){
	if(tick==0){
	if(x<savex+range){
	x+=sped
	}else{
	tick=1
	}}else{
	if(x>savex-range){
	x-=sped
	}else{
	tick=0
	}}
	delay-=1
	}else{
	opt=4
	dr=0
	drdraw=0
	hurt=0
	hurttick=0
	immune=0
	delay=15
	image_index=3
	}}else{
	if(opt==4){
	if(delay>0){
	delay-=1
	}else{
	opt=0
	mecheck=0
	delay=5
	}
	}}}}
	}


	}else{
	//____________________--------{PHASE:3}--------____________________
	if(phase==3){
	if(check==1){
	hp=100
	check=0
	option=0
	attdelay=40
	attopt=choose(0,1)
	savey=y-8
	spedtwo=1
	delay=5
	mecheck=0
	opt=0
	tick=0
	sped=1
	atttick=0
	mask_index=sprite_index
	move=1
	movex=irandom_range(224,672)
	movey=irandom_range(160,224)
	times=0
	movefb=0
	if(id==creator.skullfour){
	extra=0.6
	}else{
	extra=0
	}
	}

	if(attdelay>0){
	attdelay-=1
	if(x>Me.x&&x<Me.x+20){
	image_index=3
	}else{
	if(x<Me.x){
	image_index=5
	}else{
	image_index=6
	}}
	}else{
	//CHOMP CHARGE
	if(option==0){
	if(attopt==0){
	attopt=1
	option=1
	move=1
	atttick=1
	movex=choose(224,672)
	movey=starty
	mecheck=0
	sped=3
	}else{
	attopt=0
	option=10
	}}else{
	if(option==2){
	movey=224+20
	image_index=7
	}else{
	if(option==3){
	if(instance_place(x,y,Me)){
	option=4
	move=0
	tick=1
	savey=y
	}}else{
	if(option==4){
	Me.x=x-10
	Me.y=y-10
	if(times<2){
	if(tick==0){
	if(y<savey+8){
	y+=8
	}else{
	tick=1
	}}else{
	if(y>savey-8){
	y-=8
	}else{
	tick=0
	times+=1
	}}}else{
	option=0
	attdelay=120
	atttick=0
	sped=1
	times=0
	move=1
	}}else{
	//FIRE BREATH
	if(option==10){
	option=11
	move=1
	atttick=2
	movex=choose(224,672)
	if(movex==224){
	movedir=0
	}else{
	movedir=1
	}
	movey=starty
	mecheck=0
	sped=3
	}else{
	if(option==12){
	if(delay>0){
	delay-=1
	if(delay==8){
	image_index=7
	}else{
	if(delay==4){
		audio_play_sound_at(choose(snd_yeti_icebreath_1,snd_yeti_icebreath_2),x+sprite_width/2,y+sprite_height/2, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<25+(extra*10);i+=1){
	//FIRE
	created=instance_create(x+random_range((4+other.extra)*-1,4+other.extra),y+3+random_range(-4+extra,4+extra),Dummy_object)
	with(created){
	pin=3
	duration=120+(irandom(35))+(other.extra*20)
	durationtotal=duration
	damage=0.1
	sprite_index=skell_fire
	image_index=irandom(image_number)
	image_speed=random_range(0.15,0.30)
	vsp=2+random(0.5)+other.extra
	if(other.movedir==0){
	hsp=random_range((0.2+(other.extra*0.5))*-1,(0.2+(other.extra*0.5)))
	image_angle=270+10
	}else{
	hsp=random_range((0.2+(other.extra*0.5))*-1,(0.2+(other.extra*0.5)))*-1
	image_angle=270-10
	}}}}}}else{
	delay=30
	image_index=3
	}}}}}}}
	}
	if(move==1){

	if(x<=movex+sped&&x>=movex-sped&&y<=movey+sped&&y>=movey-sped){
	//Regular Move
	if(atttick==0){
	movex=irandom_range(224,672)
	movey=irandom_range(160,224)
	}else{
	//CHOMP CHARGE MOVE
	if(atttick==1){
	if(option==1){
	option=2
	}else{
	if(option==2){
	option=3
	sped=6
	if(x<300){
	movex=672
	}else{
	movex=224
	}}else{
	if(option==3){
	option=0
	attdelay=120
	atttick=0
	sped=1
	times=0
	}
	}}}else{
	//CHOMP CHARGE MOVE
	if(atttick==2){
	if(option==11){
	option=12
	sped=2
	if(x<300){
	movex=672
	}else{
	movex=224
	}
	}else{
	if(option==12){
	option=0
	attdelay=120
	atttick=0
	sped=1
	times=0
	}}}}}}

	if(x>=movex+sped){
	x-=sped
	}else{
	if(x<=movex-sped){
	x+=sped
	}}
	if(y>=movey+sped){
	y-=sped
	}else{
	if(y<=movey-sped){
	y+=sped
	}}}
	}

	}}}}

	}



}
