function abilstrig_miner_scr(argument0) {
	//-------------------------------------------------<<**********<<{Auto: BOMB}>>**********>>-------------------------------------------------
	if(abil==0){
	if(phase==0){
	if(check==1){
	trigger=0
	check=0
	cdcheck=0
	grav=0.0625
	slope=0
	if(option==0){
	vsp=-1
	hsp=0.9
	}else{
	if(option==1){
	vsp=1
	hsp=1.3
	}else{
	if(option==2){
	vsp=-1.875
	hsp=0.5
	}}}

	slope=0
	stopped=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb11
	}else{
	sprite_index=abil_pump1
	}
	mask_index=abil_pump1
	image_speed=0.1
	diddamage=0
	targettotal=0
	targetcheck=0
	if(direction!=0){
	hsp*=-1
	while(place_meeting(x,y,Solid)){
	x+=1
	}}else{
	while(place_meeting(x,y,Solid)){
	x-=1
	}}
	}

	//------------------------------------{REGULAR}------------------------------------
	gravity_scr()
	cdcheck+=1
	image_angle+=hsp*-10
	if(hsp>0){
	hsp-=0.0025
	}else{
	if(hsp<0){
	hsp+=0.0025
	}}
	if(hsp>0){
	hspot=-2
	}else{
	hspot=+2
	}
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	hit.dr+=damage*Control.itemsArray[0,4]
	hit.drdraw+=damage*Control.itemsArray[0,4]
	if(hit.hurt<=0){
	hit.hurttick=1
	}
	targetArray[targettotal]=hit
	targettotal+=1
	targetcheck=1
	phase=-1
	}

	if(Control.con_p_e||Control.conp_p_e||place_meeting(x+hsp+1,y+vsp,Container)||place_meeting(x+hsp-1,y+vsp,Container)){
	phase=-1
	}}else{

	//------------------------------------{BLOW UP}------------------------------------
	if(phase==-1){
	image_index=0
	phase=-2
	grav=0
	image_speed=0.5
	cdamount=40-cdcheck
	if(cdamount<0){
	cdamount=0
	}
	Control.charcdArray[creator.charid,abil]=cdamount
	if(point_distance(x,y,Me.x,Me.y)<275){
	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)
	}
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb1exp
	}else{
	sprite_index=abil_pump1exp
	}
	image_angle=0
	mask_index=abil_bomb1_mask
	}else{
	//------------------------------------{DEATH PHASE}------------------------------------
	if(phase==-2){
	if(image_index<image_number-1){

	//***HIT ENEMY***
	targetadd=0
	targetcheck=1
	with(Enemy){
	if(point_distance(x+xmid,y+ymid,other.x,other.y)<90){
	if(other.targettotal!=0){
	for(i=0;i<other.targettotal;i+=1){
	if(other.targetArray[i]==id){
	other.targetcheck=0
	}}}
	if(other.targetcheck==1){
	if(instance_place(x,y,other.id)){
	other.targetArray[other.targettotal]=id
	other.targettotal+=1
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}}}

	with(Container){
	if(point_distance(x+(sprite_width/2),y+(sprite_height/2),other.x,other.y)<14){
	hurttick=1
	}}
	}else{
	deathphase=1
	}}}}

	}else{
	//-------------------------------------------------<<**********<<{Mini bombs}>>**********>>-------------------------------------------------
	if(abil==1){
	if(check==1){
	check=0
	checks=0
	grav=0.025
	if(option==0){
	vsp=-1
	hsp=0.75

	}else{
	if(option==1){
	vsp=-0.075
	hsp=1
	}else{
	if(option==2){
	vsp=-1.5
	hsp=0.25
	}}}
	if(direction==0){
	}else{
	hsp*=-1
	}
	slope=0
	stopped=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb21
	}else{
	sprite_index=abil_pump2
	}
	option=3
	image_speed=0.1
	if(direction!=0){
	while(place_meeting(x,y,Solid)){
	x+=1
	}}else{
	while(place_meeting(x,y,Solid)){
	x-=1
	}}
	}

	if(vsp<0){
	if(instance_place(x+hsp,y+vsp,Solid)){
	vsp=0.5
	y+=0.5
	}}

	gravity_scr()

	if(x>firstx+125||x<firstx-125){
	duration=0
	}
	if(y>firsty+80||y<firsty-80){
	duration=0
	}
	enemyhit=instance_place(x,y,Enemy)
	if(enemyhit!=noone){
	if(duration!=0){
	phase=-1
	}
	duration=0
	}

	enemyhit=instance_place(x,y,ProjEn)
	if(enemyhit!=noone){
	if(enemyhit.abil==2){
	enemyhit.phase=-1
	phase=-1
	}}
	hit=instance_place(x,y-1,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1

	if(duration!=0){
	phase=-1
	}
	duration=0
	}}

	if(grounded==1){
	vsp-=impact*.75
	if(checks!=1){
	option-=1
	}
	checks=1
	}else{
	checks=0
	}

	if(option<=0){
	if(duration!=0){
	phase=-1
	}
	duration=0
	}
	if(duration>0){
	image_angle+=hsp*-10
	}
	if(hsp>0){
	hsp-=0.0025
	}
	if(hsp<0){
	hsp+=0.0025
	}
	if(phase==-1){
	image_index=0
	image_speed=0.55
	hsp=0
	vsp=0
	if(point_distance(x,y,Me.x,Me.y)<275){
	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)
	}
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb2exp
	mask_index=abil_pump2exp
	}else{
	sprite_index=abil_pump2exp
	}
	phase=-2
	}
	if(phase==-2){
	mask_index=sprite_index
	image_angle=irandom(360)
	if(image_index<10){

	//***HIT ENEMY***
	with(Enemy){
	if(place_meeting(x,y,other.id)){
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}
	}else{
	deathphase=1
	}}
	}else{

	//-------------------------------------------------<<**********<<{Charge BOMB}>>**********>>-------------------------------------------------
	if(abil==2){
	if(check==1){
	damage=5
	check=0
	knocksped=0.5
	hsp=0
	vsp=0
	held=1
	grav=0.025
	diddamage=0
	targettotal=0
	targetcheck=0
	xpos=0
	xtick=0
	startx=x
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb32
	}else{
	sprite_index=abil_pump3
	}
	image_speed=0
	image_index=1
	imgtick=0
	}

	if(phase>=0){
	image_index=imgtick
	imgtick+=0.075
	if(damage<8){
	damage+=0.025
	}else{
	damage=8
	}
	if(instance_place(x,y,Enemy)){
	phase=-1
	}}
	mask_index=sprite_index

	if(held==0){
	if(grounded==0){
	gravity_scr()
	}
	x=startx+xpos
	}else{

	//HELD
	if(Control.conp_p_w||Control.con_p_w){
	held=0
	startx=x
	}
	if(phase>=0){
	x=Me.x+10+xpos
	y=Me.y+17
	}
	}
	if(image_index>9&&phase>=0){
	duration=0
	phase=-1
	}
	if(hsp>0){
	hsp-=0.0025
	}
	if(hsp<0){
	hsp+=0.0025
	}
	if(phase==-1){
	image_index=0
	image_speed=0.55
	if(point_distance(x,y,Me.x,Me.y)<275){
	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)
	}
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_bomb3exp
	}else{
	sprite_index=abil_pump3exp
	}
	Control.screenshake=6
	phase=-2
	mecheck=1
	//initial burst

	}else{
	image_speed=0.3
	if(image_index>=7){
	if(xtick==0){
	if(xpos<1.75){
	xpos+=0.875
	}else{
	xtick=1
	}}else{
	if(xpos>-1.75){
	xpos-=0.875
	}else{
	xtick=0
	}}
	}else{
	if(image_index>=3){
	if(xtick==0){
	if(xpos<1){
	xpos+=0.25
	}else{
	xtick=1
	}}else{
	if(xpos>-1){
	xpos-=0.25
	}else{
	xtick=0
	}}}else{
	//under4
	if(xtick==0){
	if(xpos<0.8){
	xpos+=0.1
	}else{
	xtick=1
	}}else{
	if(xpos>-0.8){
	xpos-=0.1
	}else{
	xtick=0
	}}}
	}
	}
	if(phase==-2){
	mask_index=sprite_index
	image_angle=irandom(360)
	if(image_index<10){
	//***HIT ENEMY***
	targetadd=0
	targetcheck=1
	with(Enemy){
	if(point_distance(x+xmid,y+ymid,other.x,other.y)<90){
	if(other.targettotal!=0){
	for(i=0;i<other.targettotal;i+=1){
	if(other.targetArray[i]==id){
	other.targetcheck=0
	}}}
	if(other.targetcheck==1){
	if(instance_place(x,y,other.id)){
	other.targetArray[other.targettotal]=id
	other.targettotal+=1
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}}}
	with(Container){
	if(solidtype==3){
	hit=instance_place(x,y,other.id)
	if(hit!=noone){
	hurttick=1
	}}}
	if(mecheck==1){
	hit=instance_place(x,y,Me)
	if(hit!=noone){
	mecheck=0
	//hitme.y-=1
	with(Me){
	if(x+10<other.x+12&&x+12>other.x-12){
	vsp=-3.25
	}else{
	vsp=-2.25
	}}}}
	//Me.x=x-10

	}else{
	deathphase=1
	}}
	}else{
	}}}



}
