function abilpassive_scr(argument0) {
	if(Control.pause==0&&room!=Overworld_rm){
	if(Control.maskArray[Control.charArray[Control.charselected,8],0]>=999){
	pet_scr(argument0)
	}

	//Control.charArray[Control.charselected,11]=1000
	//Control.charArray[Control.charselected,12]=1000

	//-------------------------------------------------<<**********<<{MINER}>>**********>>-------------------------------------------------
	if(argument0==0){
	if(abilpassive==1){
	manaregen=0.25
	abilpassive=0
	abilpassivedraw=0
	}

	}else{
	//-------------------------------------------------<<**********<<{WIZARD}>>**********>>-------------------------------------------------
	if(argument0==1){
	if(abilpassive==1){
	manaregen=0.25
	abilpassive=0
	abilpassivedraw=0
	}

	with(Dummy_two_object){
	//Spell Trail
	if(pin==555){
	x+=hsp
	y+=vsp
	if(duration>0){
	duration-=1

	if(duration==floor(durationtotal/2)){
	image_index+=1
	}
	}else{
	instance_destroy()
	}}
	}

	}else{
	//-------------------------------------------------<<**********<<{SKELETON}>>**********>>-------------------------------------------------
	if(argument0==2){
	if(abilpassive==1){
	manaregen=0.25
	abilpassive=0
	abilpassivedraw=0
	}

	}else{
	//-------------------------------------------------<<**********<<{BEE}>>**********>>-------------------------------------------------
	if(argument0==3){
	if(abilpassive==1){
	manaregen=0.25
	abilpassive=0
	abilpassivedraw=0
	abilpassivespell=instance_create(x,y,Dummy_two_object)
	with(abilpassivespell){
	updown=0
	abilspelly=0
	abilspelltick=0
	pin=120
	ticksavex=0
	ticksavey=0
	for(i=0;i<11;i+=1){
	if(i==0){
	xoffset=-1+random(2)
	yoffset=-6+random(2)
	ticksavex=-1
	ticksavey=0
	}else{
	if(i==1){
	xoffset=-1+random(2)
	yoffset=-1+random(2)
	ticksavex=-1
	ticksavey=-1
	}else{
	if(i==2){
	xoffset=-1+random(2)
	yoffset=4+random(2)
	ticksavex=-1
	ticksavey=1
	}else{
	if(i==3){
	xoffset=-6+random(2)
	yoffset=-3.5+random(2)
	ticksavex=0
	ticksavey=0
	}else{
	if(i==4){
	xoffset=-6+random(2)
	yoffset=1.5+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==5){
	xoffset=4+random(2)
	yoffset=-3.5+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==6){
	xoffset=4+random(2)
	yoffset=1.5+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==7){
	xoffset=-4.25+random(2)
	yoffset=-2.25+random(2)
	ticksavex=1
	ticksavey=0
	}else{
	if(i==8){
	xoffset=2.25+random(2)
	yoffset=0.25+random(2)
	ticksavex=0
	ticksavey=1
	}else{
	if(i==9){
	xoffset=1.25+random(2)
	yoffset=-3.25+random(2)
	ticksavex=1
	ticksavey=1
	}else{
	if(i==10){
	xoffset=-3.25+random(2)
	yoffset=1.25+random(2)
	ticksavex=0
	ticksavey=0
	}}}}}}}}}}}
	created=instance_create(x+xoffset+8,y+yoffset,Dummy_two_object)
	with(created){
	if(other.i==1){
	instance_destroy()
	}
	damage=0.0175
	target=Me

	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=beesmall_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_bee_witch_swarm
	image_speed=random_range(0.1,0.125)
	}else{
	sprite_index=abil_bee2
	}}
	pin=100
	hp=1
	duration=340+(other.i*22)
	creator=other.id
	targetsave=0
	yoffset=other.yoffset
	xoffset=other.xoffset
	tickx=other.ticksavex
	ticky=other.ticksavey
	ticksavex=tickx
	ticksavey=ticky
	spellduration=0
	actualx=x
	actualy=y
	dmgsafety=0
	pace=0.05
	targettype=2
	itemhit=0
	damageextra=0
	leash=0
	}}}
	}

	if((abilpassivespell)!=0){
	if(instance_exists((abilpassivespell))){
	with(abilpassivespell){

	if(updown>0){
	updown-=1
	//Up Down
	if(abilspelltick==0){
	if(abilspelly<10){
	if(abilspelly<5){
	Me.vsp=(0.03)*-1
	}else{
	Me.vsp=0
	}
	abilspelly+=1
	}else{
	abilspelltick=1
	}}else{
	if(abilspelly>-10){
	if(abilspelly>-5){
	Me.vsp=0.005
	}else{
	Me.vsp=0
	}
	abilspelly-=1
	}else{
	abilspelltick=0
	}}
	}

	//BEE HIVE BEE
	with(Dummy_two_object){
	if(pin==100){
	if(dmgsafety>0){
	dmgsafety-=1
	}

	if(point_distance(x,y,Me.x+10,Me.y+10)>300){
	if(x>Me.x){
	if(x-Me.x>300){
	x=Me.x+300+10+xoffset
	actualx=x
	tickx=ticksavex
	ticky=ticksavey
	}}else{
	if(Me.x-x>300){
	x=Me.x-300+10+xoffset
	actualx=x
	tickx=ticksavex
	ticky=ticksavey
	}}
	if(y>Me.y){
	if(y-Me.y>300){
	y=Me.y+300+10+yoffset
	actualy=y
	tickx=ticksavex
	ticky=ticksavey
	}}else{
	if(Me.y-y>300){
	y=Me.y-300+10+yoffset
	actualy=y
	tickx=ticksavex
	ticky=ticksavey
	}}
	}
	if(x<__view_get( e__VW.XView, 0 )||x>__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )||y<__view_get( e__VW.YView, 0 )-16||y>__view_get( e__VW.YView, 0 )+__view_get( e__VW.HView, 0 )+16){
	if(leash<40){
	leash+=1
	}else{
	leash=0
	//target reset
	target=Me
	targettype=2
	}}else{
	leash=0
	}

	if(!instance_exists(target)){
	target=Me
	targettype=2
	}

	//ME
	if(targettype==2){
	movespeed=1.25
	tox=target.x+10
	toy=target.y-15
	pace=0.05
	other.damageextra=0
	}else{

	//SWARM LIFT
	if(targettype==3){
	if(Me.grounded==1){
	targettype=2
	target=Me
	}else{
	if(point_distance(x,y,Me.x+10,Me.y+20)>15){
	movespeed=7
	}else{
	movespeed=1.25
	}
	tox=target.x+10
	toy=target.y+20
	pace=0.5
	other.damageextra=1
	if(place_meeting(x,y,Me)){
	if(Me.vsp!=-0.05&&Me.grounded==0){
	if(spellduration>0){
	Me.vsp=-0.6
	}else{
	other.updown=6
	}}
	if(Control.con_p_space||Control.conp_p_space){
	Me.vsp=-2.5
	}}}
	}else{

	//HONEY
	movespeed=3
	other.damageextra=0
	tox=target.x
	toy=target.y
	if(target.hsp==0){
	target.eat=2
	}
	if(point_distance(x,y,tox,toy)>20){
	pace=0.25
	}else{
	pace=0.625
	}}}
	extrarange=35
	if(tox<__view_get( e__VW.XView, 0 )-extrarange||tox>__view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )+extrarange||toy<__view_get( e__VW.YView, 0 )-extrarange||toy>__view_get( e__VW.YView, 0 )+__view_get( e__VW.HView, 0 )+extrarange||target.immune==1){
	//target=Me
	//targettype=2
	}

	if(duration>0){
	duration-=1
	}else{
	//instance_destroy()
	}
	if(actualx<tox+xoffset-movespeed){
	x+=movespeed
	actualx+=movespeed
	image_xscale=1
	}else{
	if(actualx>tox+xoffset+movespeed){
	x-=movespeed
	actualx-=movespeed
	image_xscale=-1
	}}
	if(actualy<toy+yoffset-movespeed){
	y+=movespeed
	actualy+=movespeed
	}else{
	if(actualy>toy+yoffset+movespeed){
	y-=movespeed
	actualy-=movespeed
	}}

	if(tickx!=-1){
	if(tickx==0){
	if(x<actualx+4){
	x+=pace
	}else{
	tickx=1
	}}else{
	if(x>actualx-4){
	x-=pace
	}else{
	tickx=0
	}}}

	if(ticky!=-1){
	if(ticky==0){
	if(y<actualy+4){
	y+=pace
	}else{
	ticky=1
	}}else{
	if(y>actualy-4){
	y-=pace
	}else{
	ticky=0
	}}}

	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	if(other.dmgsafety<=0){
	other.dmgsafety=6
	//DAMAGE
	debuff=1
	debufftimer=6
	if(x+10<other.x){
	debuffopt=-1.5
	}else{
	debuffopt=1.5
	}
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}
	//instance_destroy()
	}}else{

	//BEE SWARM FLOAT NEW PASSIVE
	if(pin==105){
	if(hsp>0){
	image_xscale=1
	}else{
	image_xscale=-1
	}

	if(delay>0&&!instance_place(x,y,Solid)){
	delay-=1
	}else{
	instance_destroy()
	}

	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	dr+=1*Control.itemsArray[0,4]
	drdraw+=1*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}
	instance_destroy()
	}
	if(target==-2){
	x+=hsp
	y+=vsp

	}}}}
	}}}


	//GROUNDED
	if(grounded==1){
	Control.charcdArray[charid,2]=0
	}

	}else{
	//-------------------------------------------------<<**********<<{TREE}>>**********>>-------------------------------------------------
	if(argument0==4){
	if(abilpassive==1){
	manaregen=0.25
	abilpassive=0
	abilpassivedraw=0

	spellcreated=instance_create(x+(sprite_width/2)+2,y+(sprite_height/2)+5.5,Projectile)
	with(spellcreated){
	num=0
	enemy=0
	abil=0
	option=0
	creator=other.id
	direction=other.direction
	duration=Control.abilArray[0,5]
	damage=Control.abilArray[0,2]

	}
	}

	//Acorns
	with(Dummy_two_object){
	if(pin==110){
	duration-=1

	if(duration<=0){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	for(i=0;i<8;i+=1){
	image_angle=other.image_angle
	created=instance_create(x,y,Dummy_two_object)
	with(created){
	pin=111
	creator=other.id
	speed=0.25+random_range(0,0.25)
	direction=other.i*45
	hsp=hspeed
	vsp=vspeed
	speed=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_tree1_exp1
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_tree1_exp1
	}else{
	sprite_index=abil_tree1_exp1
	}}
	image_speed=0

	image_index=irandom(3)
	//OVER HALF HP
	if(other.image_index==1){
	image_index=4+irandom(3)
	}

	duration=28+irandom(10)
	durationtotal=duration
	}}
	instance_destroy()
	}else{

	//ACORN Trail
	if(duration mod 10==0){
	created=instance_create(x+irandom(3)*choose(1,-1),y+irandom(3)*choose(1,-1),Dummy_two_object)
	with(created){
	pin=113
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_tree1_exp1_2
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_tree1_exp1_2
	}else{
	sprite_index=abil_tree1_exp1_2
	}}
	image_speed=0
	image_index=choose(0,3)
	/*
	//OVER HALF HP
	if(other.version==1){
	image_index=choose(0,1)
	}else{
	image_index=choose(2,3)
	}
	*/
	hsp=other.hsp*-1/8
	vsp=other.vsp*-1/8
	duration=14+irandom(6)
	}}
	}
	if(dir==0){
	image_angle+=4
	}else{
	image_angle-=4
	}
	gravamount+=grav
	x+=hsp
	y+=vsp+gravamount
	if(duration>0){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	with(hit){
	grav=0
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}
	duration=0
	}}
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	instance_destroy()
	}}
	if(delay<=0){
	if(bounce>0){
	if(instance_place(x+hsp,y+vsp+gravamount,Solid)){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	//bounce-=1
	delay=0
	if(instance_place(x,y+vsp+gravamount,Solid)){
	vsp=(vsp+gravamount)*-choose(0.75,0.80)
	hsp=hsp*choose(0.8,0.85,0.9)
	gravamount=0
	if(instance_place(x,y+1,Solid)){
	y-=1
	}
	}else{
	if(instance_place(x+hsp,y,Solid)){
	hsp=hsp*-0.9
	if(dir==0){
	dir=1
	}else{
	dir=0
	}}}}}else{
	}}else{
	delay-=1
	}}else{
	//acornparts
	if(pin==111){
	if(duration<=durationtotal-2){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	grav=0
	dr+=0.01*Control.itemsArray[0,4]
	drdraw+=0.01*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}
	//instance_destroy()
	}
	if(instance_place(x,y,Solid)){
	instance_destroy()
	}}
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	y+=vsp
	image_angle-=7.5
	}else{

	//ACORN LEAVES
	if(pin==113){
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	y+=vsp
	image_angle-=7.5
	other.duration=4
	}
	}}}

	if(hp>=hptotal/2){
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	Control.helmanimspr=tree_anim1_spr
	Control.charEquip[Control.charselected,6]=6
	Control.charEquip[Control.charselected,2]=7
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	Control.helmanimspr=0
	Control.charEquip[Control.charselected,6]=8
	Control.charEquip[Control.charselected,2]=0
	}else{
	Control.helmanimspr=tree_anim1_spr
	Control.charEquip[Control.charselected,6]=6
	Control.charEquip[Control.charselected,2]=7
	}}
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	Control.helmanimspr=tree_anim2_spr
	Control.charEquip[Control.charselected,6]=7
	Control.charEquip[Control.charselected,2]=8
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	Control.helmanimspr=0
	Control.charEquip[Control.charselected,6]=9
	Control.charEquip[Control.charselected,2]=0
	}else{
	Control.helmanimspr=tree_anim2_spr
	Control.charEquip[Control.charselected,6]=7
	Control.charEquip[Control.charselected,2]=8
	}}
	}

	}else{
	//-------------------------------------------------<<**********<<{BURGER BOY}>>**********>>-------------------------------------------------
	if(argument0==5){
	if(abilpassive==1){
	manaregen=0.175
	abilpassive=2
	passivetick=0
	abilpassivedraw=1
	passiveticktwo=0
	passivetickthree=0
	passivetarget=0
	onpassive=0

	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	passivespr=abil_burger_passive_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	passivespr=abil_burger_passive_alt1_spr
	}else{
	passivespr=abil_burger_passive_spr
	}}

	}else{
	if(abilpassive==2){
	if(justhurt==1){
	passiveticktwo=1
	}
	if(passiveticktwo==1){
	justhurt=0
	passivehit=instance_place(x,y+1,Solid)
	passivehittwo=instance_place(x,y+1,Dummy_three_object)
	if(passivehit!=noone&&passivehittwo==noone){
	if(passivehit.sprite_index=solid_spr||passivehit.sprite_index=noslope_spr){
	passiveticktwo=0
	created=instance_create(x+10+1+hsp,y+20,Dummy_three_object)
	with(created){
	sfx_play_at(choose(snd_burger_ketchup1,snd_burger_ketchup2,snd_burger_ketchup3),x,y, 0, 90, 150, 0.5, false, 1) 
	if(other.passivetickthree==1){
	type=2
	other.passivetickthree=0
	}else{
	type=1
	}
	ypos=0
	passivehit=other.passivehit
	pin=110
	depth=50
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	if(passivehit.image_index==3){
	sprite_index=burger_ketchup_slant2_spr
	}else{
	if(passivehit.image_index==6){
	sprite_index=burger_ketchup_slant_spr
	ypos=9
	}else{
	if(passivehit.image_index==7){
	sprite_index=burger_ketchup_slant_spr
	}else{
	if(passivehit.image_index==2){
	sprite_index=burger_ketchup_slant2_spr
	image_xscale=-1
	}else{
	if(passivehit.image_index==4){
	sprite_index=burger_ketchup_slant_spr
	image_xscale=-1
	ypos=9
	}else{
	if(passivehit.image_index==5){
	sprite_index=burger_ketchup_slant_spr
	image_xscale=-1
	}else{
	sprite_index=burger_ketchup_spr
	}}}}}}
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	chance=choose(0,1)
	if(chance==0){
	if(passivehit.image_index==3){
	sprite_index=burger_ketchup_slant2_alt1_spr
	}else{
	if(passivehit.image_index==6){
	sprite_index=burger_ketchup_slant_alt1_spr
	ypos=9
	}else{
	if(passivehit.image_index==7){
	sprite_index=burger_ketchup_slant_alt1_spr
	}else{
	if(passivehit.image_index==2){
	sprite_index=burger_ketchup_slant2_alt1_spr
	image_xscale=-1
	}else{
	if(passivehit.image_index==4){
	sprite_index=burger_ketchup_slant_alt1_spr
	image_xscale=-1
	ypos=9
	}else{
	if(passivehit.image_index==5){
	sprite_index=burger_ketchup_slant_alt1_spr
	image_xscale=-1
	}else{
	sprite_index=burger_ketchup_alt1_1_spr
	}}}}}}
	}else{
	if(passivehit.image_index==3){
	sprite_index=burger_ketchup_slant2_alt1_2_spr
	}else{
	if(passivehit.image_index==6){
	sprite_index=burger_ketchup_slant_alt1_2_spr
	ypos=9
	}else{
	if(passivehit.image_index==7){
	sprite_index=burger_ketchup_slant_alt1_2_spr
	}else{
	if(passivehit.image_index==2){
	sprite_index=burger_ketchup_slant2_alt1_2_spr
	image_xscale=-1
	}else{
	if(passivehit.image_index==4){
	sprite_index=burger_ketchup_slant_alt1_2_spr
	image_xscale=-1
	ypos=9
	}else{
	if(passivehit.image_index==5){
	sprite_index=burger_ketchup_slant_alt1_2_spr
	image_xscale=-1
	}else{
	sprite_index=burger_ketchup_alt1_2_spr
	}}}}}}
	}
	}else{
	sprite_index=burger_ketchup_alt1_2_spr
	}}
	image_speed=0
	image_index=0
	duration=0
	safety=6
	x=passivehit.x+8
	y=passivehit.y+ypos
	}}}else{
	if(passivehittwo!=noone){
	passivehittwo.duration=0
	passivehittwo.image_index=0
	passivehitthree=0
	passiveticktwo=0
	}}}
	onpassive=0
	if(instance_exists(Dummy_three_object)){
	checkpin=instance_place(x,y+2,Dummy_three_object)
	if(checkpin!=noone){
	if(checkpin.pin=110){
	onpassive=1
	manaregen=0.35
	if(Control.charcdArray[Me.charid,1]>=1){
	Control.charcdArray[Me.charid,1]-=1
	}}else{
	manaregen=0.175
	}}else{
	manaregen=0.175
	}}else{
	manaregen=0.175
	}

	//Ketchup
	with(Dummy_three_object){
	if(pin==110){
	if(type==2){
	duration+=0.1
	}else{
	duration+=0.5
	}
	if(duration>=320){
	instance_destroy()
	}
	if(duration mod 40==0){
	image_index+=1
	}}}

	with(Dummy_two_object){
	//Burger parts
	if(pin==108){
	if(duration<=durationtotal-2){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	grav=0
	dr+=0.01*Control.itemsArray[0,4]
	drdraw+=0.01*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}
	//instance_destroy()
	}
	if(type==2){
	if(instance_place(x,y,Solid)){
	instance_destroy()
	}}}
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	y+=vsp
	image_angle-=7.5
	}else{
	//FRIES
	if(pin==109){
	image_angle=direction
	duration-=1
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	passivetarget=hit
	with(hit){
	grav=0
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hp-dr<=0){
	Control.charcdArray[Me.charid,1]=0
	}
	if(hurt<=0){
	hurttick=1
	}}
	instance_destroy()
	}
	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	instance_destroy()
	}
	if(instance_place(x,y,Solid)||duration<=0){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	instance_destroy()
	}
	}}}
	}}


	}else{
	//-------------------------------------------------<<**********<<{ROBOT}>>**********>>-------------------------------------------------
	if(argument0==6){
	if(abilpassive==1){
	manaregen=0.125
	abilpassivedraw=1
	abilpassive=2
	passivetarget=0
	passivetargetduration=0
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	passivespr=abil_robo_target_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	passivespr=abil_robo_target_alt1_spr
	}else{
	passivespr=abil_robo_target_spr
	}}
	passivetargetimgsave=0
	passivecounter=0
	}else{
	if(abilpassive==2){

	if(passivetarget!=0){
	if(instance_exists(passivetarget)){
	if(passivetargetduration<280){
	if(passivetargetduration==0){
	sfx_play(snd_burger_burger_passiveready1,1,false) 
	}
	if(passivecounter<1&&Control.charcdArray[Me.charid,1]!=0){
	//Control.charcdArray[Me.charid,1]=0
	passivecounter+=1
	}
	passivetargetduration+=1
	if(passivetargetduration mod 12==0){
	passivetargetimgsave+=1
	}
	}else{
	passivetarget=0
	passivetargetduration=0
	passivecounter=0
	}}else{
	passivetarget=0
	passivetargetduration=0
	passivecounter=0
	}}

	with(Dummy_two_object){
	//Particle
	if(pin==108){
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	y+=vsp
	//image_angle-=7.5
	}else{


	//MINI ROCKETS
	if(pin==109){
	if(duration>0){
	duration-=1

	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	sfx_play_at(choose(snd_burger_fries_hit1,snd_burger_fries_hit2),x,y, 0, 90, 150, 0.5, false, 1) 
	passivetarget=hit
	duration=0
	with(hit){
	grav=0
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]
	if(hurt<=0){
	hurttick=1
	}}}

	x+=hsp
	y+=vsp

	if(stall<=0){

	hit=instance_place(x,y,Solid)
	if(hit!=noone){
	if(hit.solidtype==3){
	hit.hurttick=1
	}
	duration=0
	}

	if(target!=0){
	if(instance_exists(target)){
	image_angle=0
	if(y<target.y+target.ymid-3+yoffset){
	y+=1
	if(dir==0){
	image_angle=347
	}else{
	image_angle=180+13
	}}else{
	if(y>target.y+target.ymid+3+yoffset){
	y-=1
	if(dir==0){
	image_angle=13
	}else{
	image_angle=180-13
	}}}

	}else{
	image_angle=0
	}}
	}else{
	stall-=1
	}
	//Leaf Trail
	for(i=0;i<2;i+=1){
	created=instance_create(x+((0.5+irandom(2))*choose(1,-1)),y+((0.5+irandom(2))*choose(1,-1)),Dummy_two_object)
	with(created){
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=6+irandom(10)
	durationtotal=duration

	hsp=0
	vsp=0
	}}
	}else{
	//End Explode Trail
	for(i=0;i<9;i+=1){
	created=instance_create(x+((2+irandom(2))*choose(1,-1)),y+((2+irandom(2))*choose(1,-1)),Dummy_two_object)
	with(created){
	type=1
	pin=108
	creator=other.id
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_robo_plasmashot_pieces_spr
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_robo_plasmashot_pieces_alt1_spr
	}else{
	sprite_index=abil_robo_plasmashot_pieces_spr
	}}
	image_speed=0
	image_index=irandom(image_number)
	duration=16+irandom(20)
	durationtotal=duration
	speed=random_range(0.05,0.3)
	direction=other.i*40
	hsp=hspeed
	vsp=vspeed
	speed=0
	}}
	instance_destroy()
	}

	}}}


	}

	}}else{
	//-------------------------------------------------<<**********<<{Santa}>>**********>>-------------------------------------------------
	if(argument0==7){
	if(abilpassive==1){
	//manaregen=0.25
	abilpassive=2
	abilopt=4
	abilregen=80
	}

	//ALWAYS
	if(abilpassive>1){

	if(abilopt<4&&abilopt>=1){
	if(abilregen>0){
	abilregen-=1
	}else{
	abilopt+=1
	abilregen=120
	}}

	if(abilopt>=2){
	Control.charcdArray[Me.charid,0]=0
	}else{
	if(abilopt<=0){
	if(Control.charcdArray[Me.charid,0]<=0){
	abilopt=4
	abilregen=120
	}}else{
	if(abilopt==1){
	abilopt=0
	Control.charcdArray[Me.charid,0]=200
	}}
	}


	with(Dummy_two_object){
	//Present confetti
	if(pin==50){
	vsp+=0.015
	x+=hsp
	y+=vsp
	if(duration>0){
	duration-=1
	if(diddmg==0){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	dr+=0.01*Control.itemsArray[0,4]
	drdraw+=0.01*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}
	diddmg=1
	}}
	}else{
	instance_destroy()
	}}else{

	//Tree Slam
	if(pin==51){
	if(timer<6){
	timer+=1
	if(timer==6){
	visible=true
	}}else{
	x+=hsp
	y+=vsp
	if(duration>0){
	duration-=1

	if(duration<60){
	if(instance_place(x,y,Solid)){
	duration=0
	}}

	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	dr+=2*Control.itemsArray[0,4]
	drdraw+=2*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}
	duration=0
	}
	}else{
	sfx_play_at(choose(snd_christmas_hit1,snd_christmas_hit2),x,y, 0, 90, 150, 0.5, false, 1)
	//effect
	for(i=0;i<18;i+=1){
	created=instance_create(x+choose(-3,-1.5,0,1.5,3),y-4+choose(-3,-1.5,0,1.5,3),Dummy_two_object)
	with(created){
	diddmg=0
	direction=other.i*20+choose(-3,-1.5,0,1.5,3)+other.i
	pin=50
	depth=5
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_santa_slam_dis
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_king_slam_dis
	}}
	image_index=irandom(image_number)
	image_speed=0
	image_angle=irandom(360)
	speed=random_range(0.05,0.1)
	hsp=hspeed
	vsp=vspeed
	speed=0
	duration=irandom_range(30,60)
	}}

	instance_destroy()
	}
	}}}
	}

	}
	}else{

	//-------------------------------------------------<<**********<<{Gingerbread}>>**********>>-------------------------------------------------
	if(argument0==8){
	if(abilpassive==1){
	abilpassive=2
	abilopt=0
	abilopttwo=0
	abiloptthree=0
	abiloptfour=0
	}else{
	if(abilpassive==2){

	//Turret Safety
	if(abiloptfour!=0){
	if(instance_exists(abiloptfour)){
	}else{
	//abiloptthree=0
	//abiloptfour=0
	}}

	with(Dummy_two_object){
	//Present confetti
	if(pin==50){
	x+=hsp
	y+=vsp
	if(duration>0){
	duration-=1
	if(diddmg==0){
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	dr+=0.15*Control.itemsArray[0,4]
	drdraw+=0.15*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}
	diddmg=1
	}}
	}else{
	instance_destroy()
	}}else{

	//gingerbread candycane throw
	if(pin==52){
	if(phase==0){

	created=instance_create(x+(random_range(-2,2)),y+(random_range(-2,2)),Dummy_two_object)
	with(created){
	diddmg=0
	pin=50
	depth=5
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_santa_slam_dis
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_santa_slam_dis
	}}
	image_speed=0
	image_index=irandom(image_number)
	image_angle=irandom(360)
	speed=random_range(0.05,0.25)
	hsp=0
	vsp=0
	duration=irandom_range(4,10)
	}

	x+=hsp
	y+=vsp
	if(hsp>0){
	image_angle+=5
	}else{
	image_angle-=5
	}
	if(duration>0&&!instance_place(x,y,Solid)){
	duration-=1
	hit=instance_place(x,y,Enemy)
	if(hit!=noone){
	with(hit){
	dr+=other.damage*Control.itemsArray[0,4]
	drdraw+=other.damage*Control.itemsArray[0,4]

	if(hurt<=0){
	hurttick=1
	}}

	phase=-1
	}
	}else{
	phase=-1
	}
	}else{
	if(phase==-1){
	sfx_play_at(choose(snd_christmas_hit1,snd_christmas_hit2),x,y, 0, 90, 150, 0.5, false, 1)
	phase=-2
	for(i=0;i<9;i+=1){
	created=instance_create(x,y,Dummy_two_object)
	with(created){
	diddmg=0
	direction=other.i*40+random(5)
	pin=50
	depth=4

	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_santa_slam_dis
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_santa_slam_dis
	}}

	image_index=irandom(image_number)
	image_speed=0
	image_angle=irandom(360)
	speed=random_range(0.4,0.6)
	hsp=hspeed
	vsp=vspeed
	speed=0
	duration=irandom_range(8,16)
	}}}else{
	if(phase==-2){
	instance_destroy()
	}}}}
	}}

	//Gumdrop Jump Part
	if(abilopttwo>0){
	for(i=0;i<2;i+=1){
	created=instance_create(Me.x+10+(random_range(-3.5,3.5)),Me.y+14+(random_range(-3.5,3.5)),Dummy_two_object)
	with(created){
	diddmg=0
	pin=50
	depth=5
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_ginger_dis
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_snowman_disthree
	}}
	image_speed=0
	image_index=irandom(image_number)
	image_angle=irandom(360)
	speed=random_range(0.05,0.25)
	hsp=Me.hsp*-1
	vsp=Me.vsp*-1
	hsp=0
	vsp=0
	duration=irandom_range(6,14)
	}}
	}

	//Gumdrop
	with(Me){
	hit=instance_place(x,y+1,Solid)
	if(hit!=noone){
	abilopttwo-=1
	if(hit.solidtype!=50){
	Control.charcdArray[Me.charid,2]=0
	}}
	if(vsp>0){
	hit=instance_place(x+hsp,y+vsp,Dummy_solid)
	if(hit!=noone){
	if(hit.solidtype==50&&hit.jumpdel<=0){
	sfx_play(choose(snd_christmas_block1,snd_christmas_block2),1, false)
	sfx_play_at(choose(snd_christmas_sound1,snd_christmas_sound2),x,y, 0, 90, 150, 0.5, false, 1)
	abilopttwo=1
	if(Control.con_p_space||Control.conp_p_space||Control.con_h_space||Control.conp_h_space){
	vsp=-2
	}else{
	vsp=-2.5
	}
	hit.image_index+=1
	hit.jumpdel=20
	hit.hurttick=1
	}}}}

	with(Dummy_solid){
	if(solidtype==50){
	duration+=1
	if(hurttick==1||duration mod 160 == 0){
	hp-=1
	if(hp==1){
	image_index=imgsave+4
	}
	hurttick=0
	duration=1
	//gumdrop particle
	for(i=0;i<10;i+=1){
	chance=floor(image_index/8)
	created=instance_create(x+i+random_range(-1.5,1.5),y+2+random(3),Dummy_two_object)
	with(created){
	diddmg=0
	pin=50
	depth=4

	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==0){
	sprite_index=abil_ginger_block_dis
	image_index=(other.chance*2)+irandom(1)
	}else{
	if(Control.maskArray[Control.charArray[Control.charselected,8],2]==1){
	sprite_index=abil_snowman_block_dis
	image_index=irandom(image_number)
	}}

	image_speed=0
	image_angle=irandom(360)
	hsp=0
	vsp=random_range(0.6,1)

	duration=irandom_range(10,20)
	}}
	}
	if(jumpdel>0){
	jumpdel-=1
	if(jumpdel==0){
	image_index+=1
	}}
	if(hp<=0){
	instance_destroy()
	}}}}

	}
	}}}}}}}}}
	}



}
