function worldtwo_rm1_enemy_scr() {
	if(check==1){
	imgnum=0
	}

	//--------------------------------------------------------------------*****************{Anchor Pirate}*****************--------------------------------------------------------------------
	if(enemytype==2){
	//*****{PHASE:0}*****
	if(x+8>Me.x-10&&x+8<Me.x+20){
	sprite_index=pirate_four_climb2_spr
	}else{
	if(x+8<Me.x+10){
	sprite_index=pirate_four_climb1_spr
	}else{
	sprite_index=pirate_four_climb3_spr
	}}
	if(phase==0){
	if(check==1){
	image_speed=0.05
	check=0
	phase=0
	selfcreated=instance_create(x+15,y+9,Dummy_object)
	with(selfcreated){
	depth=8
	direction=270
	image_angle=direction
	sprite_index=anchor_spr
	pin=70
	creator=id
	durationtotal=120
	duration=0
	startx=x
	starty=y
	damage=1
	}
	sprite_index=pirate_four_climb1_spr
	mask_index=sprite_index
	attcd=60
	}


	if(attcd>0){
	attcd-=1
	}else{
	phase=1
	check=1
	}
	}else{

	//*****{PHASE:1}*****
	if(phase==1){
	if(check==1){
	if(point_distance(x+8,y+8,Me.x+10,Me.y+10)<90){
	check=0
	with(selfcreated){
	direction=point_direction(x,y,Me.x,Me.y)
	endx=Me.x+10
	endy=Me.y+10
	endx+=Me.hsp*6
	endy+=Me.vsp*2
	if(x<Me.x){
	endx+=5
	}else{
	if(x>Me.x+20){
	endx-=5
	}}
	if(y<Me.y){
	endy+=5
	}else{
	if(y>Me.y+20){
	endy-=5
	}}
	image_angle=direction
	duration=80
	tick=0
	durationtotal=duration
	}}}else{

	with(selfcreated){
	if(duration>0){
	duration-=1
	if(duration>=floor(durationtotal*.75)){
	if(x<endx-7){
	x+=3
	}else{
	if(x>endx+7){
	x-=3
	}}
	if(y<endy-7){
	y+=3
	}else{
	if(y>endy+7){
	y-=3
	}}
	image_angle=direction
	if(x<startx-5){
	//x+=2
	y+=0.5
	}else{
	if(x>startx+5){
	//x-=2
	y+=0.5
	}}
	}else{
	if(duration==floor(durationtotal*.75)-1){
	}else{
	if(duration<=floor(durationtotal*.75)-1){
	direction=point_direction(x,y,startx,starty)+180
	image_angle=direction
	if(y<starty-4){
	y+=0.875
	}else{
	if(y>starty+4){
	y-=0.875
	}}
	if(x<startx-4){
	x+=2
	}else{
	if(x>startx+4){
	x-=2
	}}}
	}}}else{
	other.phase=0
	other.attcd=120
	direction=270
	image_angle=direction
	duration=0
	x=startx
	y=starty
	}}}}}
	}else{

	//--------------------------------------------------------------------*****************{Swordsman Pirate}*****************--------------------------------------------------------------------
	if(enemytype==1){
	//Walk Phase
	if(phase==0){
	if(check==1){
	check=0
	y+=1
	hp=5
	tick=0
	startx=x 
	image_speed=0.125
	sped=0.75
	range=64
	sprite_index=pirate_two_spr
	mask_index=sprite_index
	attcd=240
	phase=0
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	damage=1
	sprite_index=pirate_sword_spr
	depth=other.depth-1
	image_index=0
	pin=61
	}}
	if(room==Worldtwo_rm1_part2){
	hit=instance_place(x+8,y+1,Solid)
	if(hit==noone){
	if(tick==0){
	tick=1
	dir=1
	selfcreated.image_xscale=-1
	x-=sped
	}else{
	tick=0
	dir=0
	selfcreated.image_xscale=1
	x+=sped
	}}else{
	if(hit.image_index!=0&&hit.image_index!=1&&hit.image_index!=8){
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}}}

	with(selfcreated){
	if(other.image_index<1){
	if(other.dir==0){
	x=other.x+6
	image_angle=355
	}else{
	x=other.x+9
	image_angle=5
	}
	y=other.y+13
	}else{
	if(other.image_index<2&&other.image_index>=1){
	if(other.dir==0){
	x=other.x+4
	image_angle=5
	}else{
	x=other.x+11
	image_angle=355
	}
	y=other.y+12
	}else{
	if(other.image_index<3&&other.image_index>=2){
	if(other.dir==0){
	x=other.x+6
	image_angle=350
	}else{
	x=other.x+9
	image_angle=10
	}
	y=other.y+14
	}else{
	if(other.image_index<4&&other.image_index>=3){
	if(other.dir==0){
	x=other.x+8
	image_angle=345
	}else{
	x=other.x+7
	image_angle=15
	}
	y=other.y+12
	}}}}
	sprite_index=pirate_sword_spr
	image_index=0
	}

	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	dir=1
	selfcreated.image_xscale=-1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	dir=0
	selfcreated.image_xscale=1
	}}

	if(attcd==0){
	phase=1
	check=1
	}

	}else{
	//Lunge Phase
	if(phase==1){

	}}
	}else{

	//--------------------------------------------------------------------*****************{Parrot}*****************--------------------------------------------------------------------
	if(enemytype==3){
	//Walk Phase
	if(phase==0){
	if(check==1){
	check=0
	y+=1
	hp=15
	tick=0
	startx=x 
	image_speed=0.125
	sped=0.25
	range=32
	sprite_index=pirate_three_spr
	mask_index=sprite_index
	attcd=160
	phase=0
	}

	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	dir=1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	dir=0
	}}

	if(attcd>0){
	attcd-=1
	}else{
	phase=1
	check=1
	}

	}else{

	//Shoot Phase
	if(phase==1){
	if(check==1){
	if(point_distance(x+8,y+8,Me.x+10,Me.y+10)<200){
	check=0
	attcd=22
	if(Me.x>x){
	dir=0
	}else{
	dir=1
	}}}else{
	if(attcd>0){
	attcd-=1
	if(attcd==20||attcd==16||attcd==12||attcd==8||attcd==4||attcd==0){
	created=instance_create(x+10,y+10,Dummy_object)
	with(created){
	pin=72
	damage=1
	sprite_index=pirate_bullet_spr
	speed=1.15
	duration=240
	dir=other.dir
	direction=point_direction(x,y,Me.x+10,Me.y+10)
	direction+=irandom(10)*choose(1,-1)
	image_angle=direction
	image_speed=0
	image_index=irandom(image_number)
	}}
	}else{
	attcd=240
	phase=0
	dir=tick
	image_index=0
	if(Me.x>x){
	dir=0
	}else{
	dir=1
	}
	}}}}
	}else{

	//--------------------------------------------------------------------*****************{Parrot Cage}*****************--------------------------------------------------------------------
	if(enemytype==4){
	if(check==1){
	dir=0
	check=0
	hp=115
	hptotal=hp
	x+=8
	image_speed=0
	image_index=0
	sprite_index=pirate_cage_spr
	mask_index=sprite_index
	selfcreated=instance_create(x,y,Dummy_two_object)
	with(selfcreated){
	image_speed=0.05
	pin=81
	sprite_index=pirate_cage_parrot_spr
	depth=other.depth+1
	y+=17
	}
	anglecheck=0
	anglerange=10
	tick=3
	cagebottom=0
	while(instance_place(x,y,Solid)){
	y+=1
	}}

	if(hp<=hptotal-5&&hp>hptotal-10){
	image_index=1
	}else{
	if(hp<=hptotal-10&&hp>hptotal-15){
	image_index=2
	}else{
	if(hp<=hptotal-15&&hp>50){
	image_index=3
	hp=50
	with(selfcreated){
	instance_destroy()
	}
	selfcreated=0
	created=instance_create(x+16,y+30,Enemy)
	created.enemytype=3
	created.hp=25
	creator.roomenemy=created
	cagebottom=instance_create(x,y,Dummy_object)
	with(cagebottom){
	sprite_index=pirate_cage_spr
	image_index=4
	image_speed=0
	damage=1
	pin=81
	}}}
	}

	if(cagebottom!=0){
	with(cagebottom){
	y+=1
	if(instance_place(x,y+2,Solid)){
	instance_destroy()
	}
	if(instance_place(x,y,Me)){
	with(Me){
	if(dmgsafety<=0){
	dmgsafety=6
	//DAMAGE
	debuff=1
	debufftimer=6
	if(x+10<other.x){
	debuffopt=-1.5
	}else{
	debuffopt=1.5
	}
	dr+=other.damage
	drdraw+=other.damage
	if(hurt<=0){
	hurttick=1
	}}}
	}}}

	if(justhurt==1){
	justhurt=0
	anglerange=15
	anglesped=3
	option=20
	if(x>Me.x+10){
	tick=0
	}else{
	tick=1
	}}

	if(anglecheck==0){
	if(option>0){
	option-=1
	}else{
	tick=3
	image_angle=0
	anglecheck=0
	}}

	if(tick==0){
	if(anglecheck<0+anglerange){
	anglecheck+=anglesped/3
	image_angle+=anglesped
	}else{
	tick=1
	anglerange=anglerange*0.8
	anglesped=anglesped*0.8
	}}else{
	if(tick==1){
	if(anglecheck>0-anglerange){
	anglecheck-=anglesped/3
	image_angle-=anglesped
	}else{
	tick=0
	anglerange=anglerange*0.8
	anglesped=anglesped*0.8
	}}
	}

	if(selfcreated!=0){
	selfcreated.image_angle=image_angle
	}

	}else{

	//--------------------------------------------------------------------*****************{Bomb}*****************--------------------------------------------------------------------
	if(enemytype==5){
	if(check==1){
	check=0
	sprite_index=bombenemy_spr
	sped=1.2
	hp=22
	range=16
	startx=x
	sped=0.375
	tick=choose(0,1)
	y+=2
	}
	mask_index=sprite_index

	if(tick==0){
	if(x<startx+range){
	x+=sped
	}else{
	tick=1
	}}else{
	if(x>startx-range){
	x-=sped
	}else{
	tick=0
	}}

	if(point_distance(x+8,y+8,Me.x+10,Me.y+10)<20||hp<20){
	sprite_index=abil_bomb3exp
	image_speed=0.3
	}

	if(image_index>10){
	instance_destroy()
	}

	}else{

	//--------------------------------------------------------------------*****************{Crab}*****************--------------------------------------------------------------------
	if(enemytype==6){
	if(check==1){
	hp=125
	key=1
	check=0
	y+=5
	tick=0
	xlocation=0
	range=16*4
	sped=0.5
	delay=0
	starty=y
	sprite_index=crab_spr
	mask_index=sprite_index
	image_speed=0
	depth+=1
	rider=instance_create(x,y,Enemy)
	with(rider){
	creator=other.id
	enemytype=7
	image_speed=0.05
	xpos=6
	ypos=-20
	}
	blinkdelay=irandom_range(200,270)
	legone=instance_create(x,y,Dummy_two_object)
	with(legone){
	xpos=3
	ypos=0
	sprite_index=other.sprite_index
	image_index=3
	image_speed=0.1
	pin=82
	depth=other.depth-1
	}
	legtwo=instance_create(x,y,Dummy_two_object)
	with(legtwo){
	xpos=3
	ypos=0
	sprite_index=other.sprite_index
	image_index=4
	image_speed=0.1
	pin=82
	depth=other.depth+1
	}
	armone=instance_create(x,y,Dummy_object)
	with(armone){
	xpos=0
	ypos=0
	sprite_index=other.sprite_index
	image_index=8
	image_speed=0
	pin=88
	blinkdelay=irandom_range(80,120)
	depth=other.depth-1
	}
	armtwo=instance_create(x,y,Dummy_object)
	with(armtwo){
	xpos=-3
	ypos=-2
	sprite_index=other.sprite_index
	image_index=8
	image_speed=0
	pin=88
	blinkdelay=irandom_range(80,120)
	depth=other.depth+1
	}}
	mask_index=sprite_index

	if(hp<60){
	hp=-1
	with(rider){
	instance_destroy()
	}
	with(legone){
	instance_destroy()
	}
	with(legtwo){
	instance_destroy()
	}
	with(armone){
	instance_destroy()
	}
	with(armtwo){
	instance_destroy()
	}
	}else{
	mask_index=sprite_index

	//Phase One
	if(phase==1){
	if(tick==0){
	if(xlocation<0+range){
	xlocation+=sped
	x+=sped
	}else{
	tick=1

	dir=1
	if(instance_exists(rider)){
	rider.dir=1
	}
	armone.image_xscale=-1
	armtwo.image_xscale=-1
	legone.image_xscale=-1
	legtwo.image_xscale=-1
	}}else{
	if(tick==1){
	if(xlocation>0-range){
	xlocation-=sped
	x-=sped
	}else{
	tick=0

	dir=0
	if(instance_exists(rider)){
	rider.dir=0
	}
	armone.image_xscale=1
	armtwo.image_xscale=1
	legone.image_xscale=1
	legtwo.image_xscale=1
	}}}


	with(legone){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y
	if(image_index>=7){
	image_index=3
	}}
	with(legtwo){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y-2
	if(image_index>=7){
	image_index=3
	}}

	with(armone){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y+ypos

	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index=11
	blinkdelay=irandom_range(80,120)
	}}
	with(armtwo){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y+ypos

	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index=11
	blinkdelay=irandom_range(80,120)
	}}

	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index-=2
	blinkdelay=irandom_range(200,270)
	}

	if(delay>0){
	delay-=1
	}else{
	delay=100
	phase=0
	armone.image_index=8
	armtwo.image_index=8
	}


	}else{

	//Phase Other

	if(delay>0){
	delay-=1
	}else{
	delay=200
	if(instance_exists(rider)){
	phase=1
	armone.image_index=11
	armtwo.image_index=11
	}}

	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index-=2
	blinkdelay=irandom_range(200,270)
	}

	with(legone){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y
	if(image_index>=4&&image_index<7){
	image_index=7
	}
	if(image_index>=8){
	image_index=3
	}}
	with(legtwo){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y-2
	if(image_index>=4&&image_index<7){
	image_index=7
	}
	if(image_index>=8){
	image_index=3
	}}

	with(armone){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y+ypos

	if(image_index<8){
	image_index=8
	}
	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index-=2
	blinkdelay=irandom_range(80,120)
	}}
	with(armtwo){
	if(image_xscale==1){
	x=other.x+xpos
	}else{
	x=other.x-sprite_width-xpos
	}
	y=other.y+ypos

	if(image_index<8){
	image_index=8
	}
	if(blinkdelay>0){
	blinkdelay-=1
	if(blinkdelay==32||blinkdelay==16){
	image_index+=1
	}}else{
	image_index-=2
	blinkdelay=irandom_range(80,120)
	}}}
	}

	}else{

	//--------------------------------------------------------------------*****************{Pirate Fisher}*****************--------------------------------------------------------------------
	if(enemytype==7){
	if(check==1){
	check=0
	hp=90
	sprite_index=pirate_fisher_spr
	image_speed=0.05
	mask_index=sprite_index
	attdelay=400
	attdelaytotal=attdelay
	y=creator.y+6
	if(creator.dir==0){
	x=creator.x+27
	}else{
	x=creator.x-27
	}

	}

	mask_index=sprite_index

	y=creator.y+6
	if(creator.dir==0){
	x=creator.x+27
	}else{
	x=creator.x+5
	}


	if(attdelay>0){
	attdelay-=1
	if(attdelay==40){
	sprite_index=pirate_fisher_throw_spr
	image_index=0
	}else{
	if(attdelay==20){
	if(dir==0){
	xpos=2
	}else{
	xpos=-2
	}
	for(i=0;i<6;i+=1){
	created=instance_create(x+2,y-4,Dummy_object)
	with(created){
	delay=irandom(3)
	dir=other.dir
	grav=0.0125
	gravamount=0
	sprite_index=pirate_fisher_proj_spr
	pin=75
	direction=other.i*40
	speed=1.25
	image_angle=direction
	hsp=hspeed
	vsp=vspeed
	speed=0
	damage=1
	bounce=3
	duration=240
	}}}}

	}else{
	attdelay=attdelaytotal
	sprite_index=pirate_fisher_spr
	}

	}else{

	//--------------------------------------------------------------------*****************{Lever}*****************--------------------------------------------------------------------
	if(enemytype==8){
	if(phase==0){
	if(check==1){
	duration=6000
	check=0
	phase=1
	sprite_index=dummy_spr
	mask_index=sprite_index
	image_speed=0.05
	answer=irandom(2)
	one=instance_create(x-64,y+25,Enemy)
	with(one){
	enemytype=9
	creator=other.id
	answer=other.answer
	correct=0
	}
	three=instance_create(x+64,y+25,Enemy)
	with(three){
	enemytype=9
	creator=other.id
	answer=other.answer+irandom(2)
	correct=0
	}}}else{

	duration-=1
	if(one.correct==1&&three.correct==1||duration<=0){
	with(one){
	instance_destroy()
	}
	with(three){
	instance_destroy()
	}
	instance_destroy()
	}else{
	if(one.correct==1||one.correct==2){
	if(three.correct==1||three.correct==2){
	one.phase=3
	three.phase=3
	}}}}

	}else{

	//--------------------------------------------------------------------<<<<<<{Room Opener}>>>>>>--------------------------------------------------------------------
	if(enemytype==9){
	if(phase==0){
	if(check==1){
	correct=0
	tick=choose(0,1)
	movingcheck=0
	mecheck=0
	hp=10
	check=0
	damaging=0
	duration=240
	image_speed=0
	sprite_index=barrelback_spr
	mask_index=dummy_spr
	range=0.5
	movespeed=0.005
	moving=0

	selfcreated=instance_create(x-9,y+16,Container)
	with(selfcreated){
	imagemax=3
	hp=100
	imagesave=irandom(imagemax)
	image_index=imagesave
	clock=0
	clockcheck=imagesave
	for(i=0;i<imagemax;i+=1){
	loot_array[i]=i
	}
	depth=other.depth
	imagelevel=0
	delay=0
	delaytotal=80
	subtype=70
	creator=other.id
	nograv=1
	startx=x
	starty=y
	bomb=0
	sprite_index=barrel_spr
	selfcreated=instance_create(x+8,y+8,Dummy_two_object)
	with(selfcreated){
	depth=other.depth
	pin=70
	starty=2
	image_speed=0
	sprite_index=barrel_randomitem_spr
	}
	mask_index=sprite_index
	}
	depth=selfcreated.depth+2
	}
	if(mecheck==0){
	simplemove_scr(1)
	selfcreated.y=y+16
	}else{
	mecheck=0
	}
	if(selfcreated.hp>1){
	with(selfcreated){
	if(instance_place(x,y+1,Me)){
	hurttick=1
	}
	//ROLL
	if(delay<=0){
	if(hurttick==0){
	if(imagesave<imagemax-0.07+imagelevel){
	imagesave+=0.035
	//imagesave+=0.05+imagelevel
	}else{
	imagesave=0
	}
	imagecheck=floor(imagesave)
	if(imagecheck!=clockcheck){
	clock=0
	clockcheck=imagecheck
	}else{
	clock+=0.15
	}
	selfcreated.image_index=loot_array[imagecheck]
	selfcreated.y=y+9+clock
	}else{
	if(!audio_is_playing(box1_snd)){
	audio_play_sound(box1_snd,1,false)
	}else{
	audio_stop_sound(box1_snd)
	audio_play_sound(box1_snd,1,false)
	}
	hurttick=0
	delay=delaytotal
	}}else{
	//Loot
	delay-=1
	if(selfcreated.y>y+12-0.15&&selfcreated.y<y+12+0.15){
	selfcreated.y=y+12
	}else{
	if(selfcreated.y<y+12-0.15){
	selfcreated.y+=0.15
	}else{
	if(selfcreated.y>y+12+0.15){
	selfcreated.y-=0.15
	}}}
	imagecheck=floor(imagesave)
	if(delay==delaytotal/2){

	if(other.answer==imagecheck){
	other.correct=1
	}else{
	other.correct=2
	}
	other.phase=4
	}else{
	if(delay==0){
	}}}

	}
	if(!instance_exists(selfcreated)){
	phase=1
	duration=60
	image_index=1
	selfcreated=0
	}

	}}else{
	if(phase==3){
	correct=0
	hurttick=0
	phase=0
	selfcreated.delay=0
	selfcreated.hurttick=0
	selfcreated.correct=0
	}
	}}else{

	//--------------------------------------------------------------------<<<<<<{RANDOM BLOCK}>>>>>>--------------------------------------------------------------------
	if(enemytype==10){
	if(phase==0){
	if(check==1){
	tick=choose(0,1)
	movingcheck=0
	mecheck=0
	hp=10
	check=0
	damaging=0
	duration=240
	image_speed=0
	sprite_index=present_randomballoon_spr
	mask_index=dummy_spr
	range=0.5
	movespeed=0.005
	moving=0

	selfcreated=instance_create(x-9,y+16,Container)
	with(selfcreated){
	if(other.subtype==0){
	imagemax=3
	}else{
	imagemax=4
	}
	imagesave=irandom(imagemax)
	image_index=imagesave
	clock=0
	clockcheck=imagesave
	for(i=0;i<imagemax;i+=1){
	loot_array[i]=i
	}
	depth=other.depth
	imagelevel=0
	delay=0
	delaytotal=80
	subtype=70
	creator=other.id
	nograv=1
	startx=x
	starty=y
	bomb=0
	sprite_index=present_randomblock_spr
	selfcreated=instance_create(x+8,y+8,Dummy_two_object)
	with(selfcreated){
	depth=other.depth
	pin=70
	starty=2
	image_speed=0
	sprite_index=present_randomitem_spr
	}
	mask_index=sprite_index
	}
	depth=selfcreated.depth+2
	}
	if(mecheck==0){
	simplemove_scr(1)
	selfcreated.y=y+16
	}else{
	mecheck=0
	}
	if(selfcreated.hp>1){
	with(selfcreated){
	//ROLL
	if(delay<=0){
	if(hurttick==0){
	if(imagesave<imagemax-0.07+imagelevel){
	imagesave+=0.035
	//imagesave+=0.05+imagelevel
	}else{
	imagesave=0
	}
	imagecheck=floor(imagesave)
	if(imagecheck!=clockcheck){
	clock=0
	clockcheck=imagecheck
	}else{
	clock+=0.15
	}
	selfcreated.image_index=loot_array[imagecheck]
	selfcreated.y=y+9+clock
	}else{
	if(!audio_is_playing(box1_snd)){
	audio_play_sound(box1_snd,1,false)
	}else{
	audio_stop_sound(box1_snd)
	audio_play_sound(box1_snd,1,false)
	}
	hurttick=0
	delay=delaytotal
	}}else{
	//Loot
	delay-=1
	if(selfcreated.y>y+12-0.15&&selfcreated.y<y+12+0.15){
	selfcreated.y=y+12
	}else{
	if(selfcreated.y<y+12-0.15){
	selfcreated.y+=0.15
	}else{
	if(selfcreated.y>y+12+0.15){
	selfcreated.y-=0.15
	}}}
	imagecheck=floor(imagesave)
	if(delay==delaytotal/2){
	//Bomb
	if(loot_array[imagecheck]==0){
	bomb=5
	}else{
	//Coin
	if(loot_array[imagecheck]==1){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	}else{
	//Tri Coin
	if(loot_array[imagecheck]==2){
	for(i=0;i<3;i+=1){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	}
	}else{
	//Heart
	if(loot_array[floor(imagecheck)]==3){
	created=instance_create(x+(sprite_width/2)-1,y+sprite_height+3,Item)
	created.itemtype=2
	created.subtype=1
	}}}
	}
	loot_array[imagecheck]=0
	selfcreated.image_index=0
	hurttick=0
	selfcreated.image_index=loot_array[imagecheck]
	}else{
	if(delay==0){
	}}}
	if(bomb!=0){
	//BLOWS UP
	if(bomb>1){
	Control.screenshake+=8
	bomb-=1
	audio_play_sound_at(choose(pump_abil1_snd1,pump_abil1_snd2),x,y, 0, 90, 150, 0.5, false, 1)

	chance=irandom(sprite_get_number(present_fetti_spr))
	for(i=20;i>0;i-=1){
	//CONFETTI BLAST
	created=instance_create(x+5,y+5,Dummy_object)
	with(created){
	sprite_index=present_fetti_spr
	mask_index=sprite_index
	image_speed=0
	image_index=other.chance+other.i
	direction=other.i*20
	direction+=(other.delay-1)*10
	tick=0
	angle=random(10)*choose(-1,1)
	startangle=0
	image_angle=direction
	speed=random_range(0.55,0.8)
	duration=120+random(80)
	damage=1
	pin=73
	}}}else{
	with(selfcreated){
	instance_destroy()
	}
	instance_destroy()
	}}
	}
	if(!instance_exists(selfcreated)){
	phase=1
	duration=120
	image_index=1
	selfcreated=0
	}

	}}else{
	if(duration>0){
	duration-=1
	y-=1
	}else{
	instance_destroy()
	}
	}}else{

	//--------------------------------------------------------------------<<<<<<{Pirate Para}>>>>>>--------------------------------------------------------------------
	if(enemytype==11){
	if(check==1){
	check=0
	sprite_index=pirate_two_para_spr
	mask_index=sprite_index
	image_speed=0.1
	}
	if(!instance_place(x,y+1,Solid)){
	y+=1
	}else{
	created=instance_create(x,y,Enemy)
	with(created){
	enemytype=1
	y+=7
	}
	instance_destroy()
	}

	}}}}}}}}}}
	}





}
