if(locked==1){
if(check==1){
check=0
sprite_index=door_spr
image_index=imgsave
}
if(point_distance(x,y,Me.x,Me.y)<150){
if(hp<=0){
if(delay>16){
image_index=imgsave+1
}else{
image_index=imgsave+2
}
if(delay>0){
delay-=1
}else{
instance_destroy()
}}else{
if(instance_place(x-1,y,Me)||instance_place(x+1,y,Me)){
close=1
if(tick==0){
tick=1
if(Dummy_obj.key>0){
Dummy_obj.key-=1
hp=0
audio_play_sound(key_snd1,1,false)
audio_play_sound(doorlock_snd1,1,false)
}else{
audio_play_sound(doorlock_snd1,1,false)
}}}else{
tick=0
close=0
}
}}
}else{
if(check==1){
sprite_index=door_spr
image_index=imgsave+3
}}

