function worldtwo_boss_control_scr() {
	//______________________________________________________________________------------------<<***{Control}***>>------------------<________________________________________________________________________________
	if(check==1){
	check=0
	xpos=0
	//Me.x=448
	//Me.y=208
	girltickcheck=1

	girlbubble=instance_create(512-60-1,222-40,Dummy_four_object)
	with(girlbubble){
	sprite_index=bubble_spr
	image_speed=0.1
	depth=55
	}
	girl=instance_create(512-60-1-8,222-40-8,Dummy_four_object)
	with(girl){
	sprite_index=sister_levitate_spr
	image_speed=0.1
	depth=55
	girlbubble=other.girlbubble
	}

	Control.bottles=0

	//CHEST LOOTS
	with(Control){
	chestitemone=8
	chestitemtwo=8
	chestoptforce=1

	rmcheck=1
	musicchange=cath1_music
	}

	//Skell
	created=instance_create(416+15,208+8,Enemy)
	with(created){
	startx=x
	starty=y
	enemytype=1
	xpos=0
	sprite_index=skell_organ
	image_speed=0.2
	//SKulls
	for(i=0;i<4;i+=1){
	dir=0
	created=instance_create(300+xpos,150,Enemy)
	with(created){
	creator=other.id
	num=other.i
	sprite_index=skell_skull
	image_speed=0
	enemytype=2
	if(num==0){
	other.skullone=id
	type=1
	}else{
	if(num==1){
	other.skulltwo=id
	type=2
	}else{
	if(num==2){
	other.skullthree=id
	type=1
	}else{
	if(num==3){
	other.skullfour=id
	type=2
	}}}}
	if(other.i==1){
	other.xpos+=88
	}else{
	other.xpos+=106
	}}}
	xpos=128+32-6
	//Walls
	for(i=0;i<2;i+=1){
	created=instance_create(xpos,0,Solid_plat)
	with(created){
	sprite_index=skell_wall_spr
	other.xpos=688+64-5
	if(other.i==0){
	other.wallone=id
	}else{
	other.walltwo=id
	}
	visible=true
	depth=50
	startx=x
	}}
	xpos=353
	//Platform
	for(i=0;i<2;i+=1){
	created=instance_create(xpos,room_height,Solid_plat)
	with(created){
	sprite_index=skell_platform_spr
	other.xpos=548
	if(other.i==0){
	other.wallthree=id
	}else{
	other.wallfour=id
	}
	visible=true
	depth=50
	starty=y
	}}
	xpos=353-64-16
	//Platform Small
	for(i=0;i<2;i+=1){
	created=instance_create(xpos,room_height,Solid_plat)
	with(created){
	sprite_index=skell_platform_two_spr
	other.xpos=548+64+16
	if(other.i==0){
	other.wallfive=id
	}else{
	other.wallsix=id
	}
	visible=true
	depth=50
	starty=y
	}}
	}

	//Organ
	created=instance_create(450,192,Dummy_four_object)
	with(created){
	sprite_index=skell_organ_spr
	enemytype=1
	pin=0
	image_speed=0.1
	depth=50
	}
	}

	if(instance_exists(Goal)){
	with(girl){
	if(y<235){
	depth=10
	girlbubble.depth=30
	girlbubble.y+=0.25
	y+=0.25
	if(y==232){
		image_alpha=0.25
	}
	if(y>=232){
		image_alpha+=0.1
	sprite_index=lightblast_spr
	image_xscale=100
	image_yscale=100

	}
	}else{
	if(instance_exists(girlbubble)){
		sprite_index=sister_idle_spr
		image_speed=0.9
		image_xscale=1
		image_yscale=1
	
	with(girlbubble){
	instance_destroy()
	}}
	}

	}
	}

	with(Me){
	hit=instance_place(x,y,Dummy_object)
	if(hit!=noone){
	dr+=hit.damage
	drdraw+=hit.damage
	if(hurt<=0){
	hurttick=1
	}
	with(hit){
	if(pin==2){
	instance_destroy()
	}}}}

	//ALWAYS
	with(Dummy_object){
	if(pin==1){
	if(target.x>x){
	image_xscale=1
	}else{
	image_xscale=-1
	}
	if(duration>0){
	duration-=1
	}
	if(point_distance(x,y,target.x+xpos+xoffset,target.y+ypos+yoffset)>1&&duration>0){
	move_towards_point(target.x+xpos+xoffset,target.y+ypos+yoffset,sped)
	}else{
	//Hit Poof
	for(i=0;i<8;i+=1){
	created=instance_create(x+irandom(2)*choose(1,-1),y+irandom(2)*choose(1,-1),Dummy_two_object)
	with(created){
	type=2
	pin=1
	speed=0.75+random_range(0,0.5)
	direction=other.i*40
	hsp=hspeed
	vsp=vspeed
	speed=0
	sprite_index=skell_butterfly_trail_spr
	image_speed=0
	image_index=irandom(image_number)
	duration=10+irandom(5)
	durationtotal=duration
	}}
	target.phase=1
	target.check=1
	instance_destroy()
	}}else{
	//BRICK
	if(pin==2){
	if(delay<=0){
	y+=sped
	if(y>room_height-5){
	instance_destroy()
	}}else{
	delay-=1
	}}else{
	//Fire
	if(pin==3){
	if(y<254+vsp&&x<678&&x>224){
	x+=hsp
	y+=vsp
	}else{
	if(duration>0&&x<678&&x>224){
	if(duration==durationtotal){
	image_angle=270
	y=254
	}
	duration-=1
	}else{
	instance_destroy()
	}}}else{
	//Bone Serpent
	if(pin==4){
	x+=hsp
	y+=vsp
	if(image_index!=0){
	created=instance_create(x+(choose(1,-1)*irandom(1)),y+(choose(1,-1)*irandom(2))+8,Dummy_two_object)
	with(created){
	if(other.dir!=0){
	image_xscale=-1
	}
	type=1
	pin=1
	creator=other.id
	sprite_index=skell_fire
	depth=other.depth+1
	image_speed=0.3
	image_index=irandom(image_number)
	duration=1+irandom(5)+other.type*2
	durationtotal=duration

	hsp=other.hsp*-1/8
	vsp=other.vsp*-1/8
	}}
	if(delay<=0){
	if(tick==0){
	if(y<starty+3){
	y+=1
	}else{
	tick=1
	}}else{
	if(y>starty-3){
	y-=1
	}else{
	tick=0
	}}}else{
	delay-=1
	}
	if(dir==0){
	if(x>endx){
	instance_destroy()
	}
	}else{
	if(x<endx){
	instance_destroy()
	}}}else{
	//BONE SHIELD
	if(pin==5){
	if(instance_exists(creator)){
	if(delay>0){
	delay-=1
	if(delay==0){
	visible=true
	}}else{
	image_angle+=imgsped
	dir2=(dir1+5+360)mod(360)
	dir1=dir2

	x=lengthdir_x(20,dir2)+creator.x
	y=lengthdir_y(20,dir2)+creator.y

	xspot=creator.x
	yspot=creator.y
	}}else{
	instance_destroy()
	}}}}}}
	}

	//Particle Effect
	with(Dummy_two_object){
	//butterfly
	if(pin==1){
	if(duration>0){
	duration-=1
	}else{
	instance_destroy()
	}
	x+=hsp
	y+=vsp
	}}

	__background_set( e__BG.X, 1, (__view_get( e__VW.XView, 0 )/6)-48 )



}
